---
to: generated/.pollux-go-staging/internal/app/app.go
force: true
---
// Code generated by Pollux (go backend). DO NOT EDIT.
package app

import (
	"context"
	"log/slog"
	"net/http"
	"strings"
	"time"

	"github.com/gin-gonic/gin"
	"github.com/uptrace/bun"

	"pollux-go/internal/auth"
	"pollux-go/internal/config"
	"pollux-go/internal/database"
	"pollux-go/internal/idempotency"
	"pollux-go/internal/middleware"
	"pollux-go/internal/server"
	"pollux-go/internal/v2"
)

// Deps groups the shared dependencies passed to every generated entity.
type Deps struct {
	Config *config.Config
	DB     *bun.DB
	Auth   auth.Client
	Logger *slog.Logger
}

// NewEngine assembles the Gin engine; exported for handler contract tests.
func NewEngine(deps *Deps) *gin.Engine {
	gin.SetMode(gin.ReleaseMode)
	engine := gin.New()
	// Trusting all proxies is forbidden; nil means "trust none".
	_ = engine.SetTrustedProxies(deps.Config.TrustedProxies)

	engine.Use(
		middleware.RequestIDMiddleware(),
		middleware.Recovery(deps.Logger),
		middleware.AccessLog(deps.Logger),
		middleware.Timeout(deps.Config.RequestTimeout),
	)

	if len(deps.Config.CORSAllowedOrigins) > 0 {
		engine.Use(corsMiddleware(deps.Config.CORSAllowedOrigins))
	}

	// Health is process-only; readiness performs a bounded database ping.
	engine.GET("/healthz", func(c *gin.Context) {
		c.JSON(http.StatusOK, gin.H{"status": "ok"})
	})
	engine.GET("/readyz", func(c *gin.Context) {
		if err := database.Ping(c.Request.Context(), deps.DB); err != nil {
			c.JSON(http.StatusServiceUnavailable, gin.H{"status": "unavailable"})
			return
		}
		c.JSON(http.StatusOK, gin.H{"status": "ready"})
	})

	// Entities mount both /api/generated/v1/<entity> (unchanged legacy
	// contract) and /api/generated/v2/<entity> (SPEC-003 standalone
	// contract) below this shared prefix.
	api := engine.Group("/api/generated")
	registerGeneratedRoutes(api, deps)

	// Unknown v2 entity codes are NOT_FOUND envelopes per the v2 contract.
	// Every other unmatched path keeps Gin's default empty 404 so v1
	// behavior is untouched.
	engine.NoRoute(func(c *gin.Context) {
		if strings.HasPrefix(c.Request.URL.Path, "/api/generated/v2/") {
			v2.NotFoundEntity(c)
			return
		}
		c.Status(http.StatusNotFound)
	})

	return engine
}

func corsMiddleware(allowed []string) gin.HandlerFunc {
	allowedSet := make(map[string]bool, len(allowed))
	for _, origin := range allowed {
		allowedSet[origin] = true
	}
	return func(c *gin.Context) {
		origin := c.GetHeader("Origin")
		if origin != "" && allowedSet[origin] {
			c.Header("Access-Control-Allow-Origin", origin)
			c.Header("Access-Control-Allow-Credentials", "true")
			c.Header("Vary", "Origin")
			c.Header("Access-Control-Allow-Methods", "GET, POST, PATCH, DELETE, OPTIONS")
			c.Header("Access-Control-Allow-Headers", "Content-Type, X-Request-Id")
		}
		if c.Request.Method == http.MethodOptions {
			c.AbortWithStatus(http.StatusNoContent)
			return
		}
		c.Next()
	}
}

// Run wires configuration, database, auth client and the HTTP server.
func Run(cfg *config.Config, logger *slog.Logger) error {
	db, err := database.Open(context.Background(), cfg)
	if err != nil {
		return err
	}
	defer func() { _ = db.Close() }()

	deps := &Deps{
		Config: cfg,
		DB:     db,
		Auth:   auth.NewHTTPClient(cfg.AuthBaseURL, cfg.AuthTimeout),
		Logger: logger,
	}

	// v2 idempotency: the Go service owns the pollux_idempotency table and
	// creates it on boot (there is no separate migration pipeline).
	idempotency.Configure(cfg.IdempotencyRetention, cfg.IdempotencyWaitBound)
	if err := idempotency.EnsureSchema(context.Background(), db); err != nil {
		return err
	}

	// Periodic cleanup deletes only expired completed idempotency records.
	cleanupCtx, cancelCleanup := context.WithCancel(context.Background())
	defer cancelCleanup()
	go func() {
		ticker := time.NewTicker(cfg.IdempotencyCleanupInterval)
		defer ticker.Stop()
		for {
			select {
			case <-cleanupCtx.Done():
				return
			case <-ticker.C:
				if removed, err := idempotency.Cleanup(cleanupCtx, db); err != nil {
					logger.Warn("idempotency cleanup failed", "err", err.Error())
				} else if removed > 0 {
					logger.Info("idempotency cleanup", "removed", removed)
				}
			}
		}
	}()

	logger.Info("pollux go backend listening", "port", cfg.Port)
	return server.Run(cfg, logger, NewEngine(deps))
}
