---
to: generated/.pollux-go-staging/internal/audit/audit.go
force: true
---
// Code generated by Pollux (go backend). DO NOT EDIT.
package audit

import (
	"context"
	"sort"
	"time"

	"github.com/google/uuid"
	"github.com/uptrace/bun"
)

// Event mirrors the generated_crud_audit table used by the TypeScript
// backend. Field *names* only, never values. Append-only.
type Event struct {
	bun.BaseModel `bun:"table:generated_crud_audit"`

	ID            string    `bun:"id,pk"`
	OccurredAt    time.Time `bun:"occurred_at,nullzero,default:now()"`
	RequestID     string    `bun:"request_id"`
	ActorUserID   string    `bun:"actor_user_id"`
	Entity        string    `bun:"entity"`
	Operation     string    `bun:"operation"`
	RecordID      *string   `bun:"record_id"`
	RecordCount   int       `bun:"record_count"`
	ChangedFields []string  `bun:"changed_fields,type:jsonb"`
	Outcome       string    `bun:"outcome"`
}

// Insert must be called inside the mutation's transaction: an audit failure
// rolls the whole mutation back.
func Insert(ctx context.Context, tx bun.IDB, event Event) error {
	if event.ID == "" {
		event.ID = uuid.NewString()
	}
	if event.RecordCount == 0 {
		event.RecordCount = 1
	}
	if event.Outcome == "" {
		event.Outcome = "success"
	}
	if event.ChangedFields == nil {
		event.ChangedFields = []string{}
	}
	sort.Strings(event.ChangedFields)

	_, err := tx.NewInsert().Model(&event).ExcludeColumn("occurred_at").Exec(ctx)
	return err
}
