---
to: generated/.pollux-go-staging/internal/auth/client_test.go
force: true
---
// Code generated by Pollux (go backend). DO NOT EDIT.
package auth

import (
	"context"
	"errors"
	"net/http"
	"net/http/httptest"
	"testing"
	"time"

	"pollux-go/internal/httperr"
)

func codeOf(t *testing.T, err error) httperr.Code {
	t.Helper()
	var typed *httperr.E
	if !errors.As(err, &typed) {
		t.Fatalf("expected *httperr.E, got %T (%v)", err, err)
	}
	return typed.Code
}

func TestSessionMissingCookie(t *testing.T) {
	client := NewHTTPClient("http://127.0.0.1:0", time.Second)
	_, err := client.Session(context.Background(), "")
	if codeOf(t, err) != httperr.Unauthenticated {
		t.Fatal("missing cookie must be UNAUTHENTICATED without a network call")
	}
}

func TestSessionNullBody(t *testing.T) {
	server := httptest.NewServer(http.HandlerFunc(func(w http.ResponseWriter, _ *http.Request) {
		_, _ = w.Write([]byte("null"))
	}))
	defer server.Close()

	client := NewHTTPClient(server.URL, time.Second)
	_, err := client.Session(context.Background(), "session=x")
	if codeOf(t, err) != httperr.Unauthenticated {
		t.Fatal("null session must be UNAUTHENTICATED")
	}
}

func TestSessionSuccessForwardsCookie(t *testing.T) {
	var seenCookie string
	server := httptest.NewServer(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		seenCookie = r.Header.Get("Cookie")
		_, _ = w.Write([]byte(`{"user":{"id":"user-1"}}`))
	}))
	defer server.Close()

	client := NewHTTPClient(server.URL, time.Second)
	session, err := client.Session(context.Background(), "better-auth.session_token=abc")
	if err != nil {
		t.Fatalf("unexpected error: %v", err)
	}
	if session.UserID != "user-1" {
		t.Fatalf("wrong user: %+v", session)
	}
	if seenCookie != "better-auth.session_token=abc" {
		t.Fatalf("cookie not forwarded: %q", seenCookie)
	}
}

func TestSessionTimeoutIsServiceUnavailable(t *testing.T) {
	server := httptest.NewServer(http.HandlerFunc(func(w http.ResponseWriter, _ *http.Request) {
		time.Sleep(200 * time.Millisecond)
		_, _ = w.Write([]byte(`{"user":{"id":"u"}}`))
	}))
	defer server.Close()

	client := NewHTTPClient(server.URL, 20*time.Millisecond)
	_, err := client.Session(context.Background(), "session=x")
	if codeOf(t, err) != httperr.ServiceUnavailable {
		t.Fatal("auth timeout must be SERVICE_UNAVAILABLE")
	}
}

func TestSessionMalformedUpstream(t *testing.T) {
	server := httptest.NewServer(http.HandlerFunc(func(w http.ResponseWriter, _ *http.Request) {
		_, _ = w.Write([]byte("this is not json"))
	}))
	defer server.Close()

	client := NewHTTPClient(server.URL, time.Second)
	_, err := client.Session(context.Background(), "session=x")
	if codeOf(t, err) != httperr.ServiceUnavailable {
		t.Fatal("malformed upstream must be SERVICE_UNAVAILABLE")
	}
}

func TestSessionUnexpectedStatusIsInternal(t *testing.T) {
	server := httptest.NewServer(http.HandlerFunc(func(w http.ResponseWriter, _ *http.Request) {
		w.WriteHeader(http.StatusTeapot)
	}))
	defer server.Close()

	client := NewHTTPClient(server.URL, time.Second)
	_, err := client.Session(context.Background(), "session=x")
	if codeOf(t, err) != httperr.Internal {
		t.Fatal("unexpected upstream status must be INTERNAL")
	}
}

func TestRequirePermissionDenied(t *testing.T) {
	server := httptest.NewServer(http.HandlerFunc(func(w http.ResponseWriter, _ *http.Request) {
		_, _ = w.Write([]byte(`{"success":false}`))
	}))
	defer server.Close()

	client := NewHTTPClient(server.URL, time.Second)
	err := client.RequirePermission(context.Background(), "session=x", "act", "update")
	if codeOf(t, err) != httperr.Forbidden {
		t.Fatal("denied permission must be FORBIDDEN")
	}
}

func TestCapabilitiesFailClosed(t *testing.T) {
	server := httptest.NewServer(http.HandlerFunc(func(w http.ResponseWriter, _ *http.Request) {
		w.WriteHeader(http.StatusInternalServerError)
	}))
	defer server.Close()

	client := NewHTTPClient(server.URL, time.Second)
	caps := client.Capabilities(context.Background(), "session=x", "act")
	if caps.CanRead || caps.CanCreate || caps.CanUpdate || caps.CanDelete {
		t.Fatalf("capabilities must fail closed on dependency failure: %+v", caps)
	}
}

// ---- v2 bearer boundary ---------------------------------------------------

func TestSessionBearerMissingToken(t *testing.T) {
	client := NewHTTPClient("http://127.0.0.1:0", time.Second)
	_, err := client.SessionBearer(context.Background(), "")
	if codeOf(t, err) != httperr.Unauthenticated {
		t.Fatal("missing bearer token must be UNAUTHENTICATED without a network call")
	}
}

func TestSessionBearerForwardsAuthorization(t *testing.T) {
	var seenAuthorization string
	server := httptest.NewServer(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		seenAuthorization = r.Header.Get("Authorization")
		_, _ = w.Write([]byte(`{"user":{"id":"user-1"}}`))
	}))
	defer server.Close()

	client := NewHTTPClient(server.URL, time.Second)
	session, err := client.SessionBearer(context.Background(), "token-abc")
	if err != nil {
		t.Fatalf("unexpected error: %v", err)
	}
	if session.UserID != "user-1" {
		t.Fatalf("wrong user: %+v", session)
	}
	if seenAuthorization != "Bearer token-abc" {
		t.Fatalf("bearer token not forwarded: %q", seenAuthorization)
	}
}

func TestSessionBearerUnauthorized(t *testing.T) {
	server := httptest.NewServer(http.HandlerFunc(func(w http.ResponseWriter, _ *http.Request) {
		w.WriteHeader(http.StatusUnauthorized)
	}))
	defer server.Close()

	client := NewHTTPClient(server.URL, time.Second)
	_, err := client.SessionBearer(context.Background(), "expired")
	if codeOf(t, err) != httperr.Unauthenticated {
		t.Fatal("invalid bearer token must be UNAUTHENTICATED")
	}
}

func TestSessionBearerOutageIsRetryable(t *testing.T) {
	server := httptest.NewServer(http.HandlerFunc(func(w http.ResponseWriter, _ *http.Request) {
		w.WriteHeader(http.StatusBadGateway)
	}))
	defer server.Close()

	client := NewHTTPClient(server.URL, time.Second)
	_, err := client.SessionBearer(context.Background(), "token")
	if codeOf(t, err) != httperr.ServiceUnavailable {
		t.Fatal("auth outage must be SERVICE_UNAVAILABLE (fail closed, retryable)")
	}
}

func TestRequirePermissionBearerForwardsSameToken(t *testing.T) {
	var seenAuthorization, seenPath string
	server := httptest.NewServer(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		seenAuthorization = r.Header.Get("Authorization")
		seenPath = r.URL.Path
		_, _ = w.Write([]byte(`{"success":true}`))
	}))
	defer server.Close()

	client := NewHTTPClient(server.URL, time.Second)
	if err := client.RequirePermissionBearer(context.Background(), "token-abc", "act", "update"); err != nil {
		t.Fatalf("unexpected error: %v", err)
	}
	if seenAuthorization != "Bearer token-abc" {
		t.Fatalf("the SAME bearer token must reach the authz boundary: %q", seenAuthorization)
	}
	if seenPath != "/api/rest/authz/has-permission" {
		t.Fatalf("wrong authz path: %q", seenPath)
	}
}

func TestRequirePermissionBearerDenied(t *testing.T) {
	server := httptest.NewServer(http.HandlerFunc(func(w http.ResponseWriter, _ *http.Request) {
		_, _ = w.Write([]byte(`{"success":false}`))
	}))
	defer server.Close()

	client := NewHTTPClient(server.URL, time.Second)
	err := client.RequirePermissionBearer(context.Background(), "token", "act", "delete")
	if codeOf(t, err) != httperr.Forbidden {
		t.Fatal("denied permission must be FORBIDDEN")
	}
}

func TestRequirePermissionBearerOutageFailsClosedRetryable(t *testing.T) {
	server := httptest.NewServer(http.HandlerFunc(func(w http.ResponseWriter, _ *http.Request) {
		w.WriteHeader(http.StatusInternalServerError)
	}))
	defer server.Close()

	client := NewHTTPClient(server.URL, time.Second)
	err := client.RequirePermissionBearer(context.Background(), "token", "act", "read")
	if codeOf(t, err) != httperr.ServiceUnavailable {
		t.Fatal("authz outage must be retryable SERVICE_UNAVAILABLE, never allow")
	}
}
