---
to: generated/.pollux-go-staging/internal/authz/authz.go
force: true
---
// Code generated by Pollux (go backend). DO NOT EDIT.
package authz

import (
	"github.com/gin-gonic/gin"

	"pollux-go/internal/auth"
	"pollux-go/internal/middleware"
	"pollux-go/internal/response"
)

const actorKey = "pollux.actorUserId"

// Require authenticates the session and checks the exact entity/action
// permission before any handler or repository code runs. Entity and action
// are static generated strings — a request can never choose them.
func Require(client auth.Client, entity, action, operation string) gin.HandlerFunc {
	return func(c *gin.Context) {
		middleware.SetEntityAction(c, entity, action, operation)
		cookie := c.GetHeader("Cookie")

		session, err := client.Session(c.Request.Context(), cookie)
		if err != nil {
			response.Fail(c, err)
			return
		}
		middleware.SetUserID(c, session.UserID)
		c.Set(actorKey, session.UserID)

		if err := client.RequirePermission(c.Request.Context(), cookie, entity, action); err != nil {
			response.Fail(c, err)
			return
		}
		c.Next()
	}
}

// Authenticate resolves the session without a permission requirement
// (capabilities endpoint).
func Authenticate(client auth.Client, entity string) gin.HandlerFunc {
	return func(c *gin.Context) {
		middleware.SetEntityAction(c, entity, "read", "capabilities")
		session, err := client.Session(c.Request.Context(), c.GetHeader("Cookie"))
		if err != nil {
			response.Fail(c, err)
			return
		}
		middleware.SetUserID(c, session.UserID)
		c.Set(actorKey, session.UserID)
		c.Next()
	}
}

// Actor returns the authenticated user ID set by Require/Authenticate.
func Actor(c *gin.Context) string {
	return c.GetString(actorKey)
}
