---
to: generated/.pollux-go-staging/internal/auth/client.go
force: true
---
// Code generated by Pollux (go backend). DO NOT EDIT.
package auth

import (
	"bytes"
	"context"
	"encoding/json"
	"errors"
	"fmt"
	"io"
	"net/http"
	"time"

	"pollux-go/internal/httperr"
)

// Better Auth remains the identity and permission authority. This client
// forwards the caller's session cookie to the configured base URL; no role
// statement or table layout is duplicated in Go.

type Session struct {
	UserID string
}

type Capabilities struct {
	CanRead   bool `json:"canRead"`
	CanCreate bool `json:"canCreate"`
	CanUpdate bool `json:"canUpdate"`
	CanDelete bool `json:"canDelete"`
}

// Client is an interface so handlers and services are testable without a
// live Better Auth server.
type Client interface {
	// Session resolves the session for the given Cookie header value.
	// Returns UNAUTHENTICATED when missing or expired.
	Session(ctx context.Context, cookie string) (*Session, error)
	// RequirePermission checks the exact entity/action permission for the
	// session user. Returns FORBIDDEN on denial.
	RequirePermission(ctx context.Context, cookie, entity, action string) error
	// Capabilities performs the four checks independently and fails closed.
	Capabilities(ctx context.Context, cookie, entity string) Capabilities

	// SessionBearer resolves the session for a bearer access token (v2
	// standalone contract). Returns UNAUTHENTICATED when missing/invalid.
	SessionBearer(ctx context.Context, token string) (*Session, error)
	// RequirePermissionBearer forwards the SAME bearer token to the
	// TypeScript authz boundary (POST /api/rest/authz/has-permission).
	// FORBIDDEN on denial; retryable SERVICE_UNAVAILABLE on outage.
	RequirePermissionBearer(ctx context.Context, token, entity, action string) error
}

type HTTPClient struct {
	baseURL string
	client  *http.Client
}

func NewHTTPClient(baseURL string, timeout time.Duration) *HTTPClient {
	return &HTTPClient{
		baseURL: baseURL,
		client:  &http.Client{Timeout: timeout},
	}
}

const maxAuthResponseBytes = 1 << 20

func classifyTransport(err error) error {
	if errors.Is(err, context.DeadlineExceeded) || errors.Is(err, context.Canceled) {
		return httperr.New(httperr.ServiceUnavailable, httperr.WithCause(err))
	}
	return httperr.New(httperr.ServiceUnavailable, httperr.WithCause(err))
}

func (h *HTTPClient) do(ctx context.Context, method, path, cookie string, body any) (int, []byte, error) {
	return h.doWith(ctx, method, path, cookie, "", body)
}

func (h *HTTPClient) doWith(ctx context.Context, method, path, cookie, bearer string, body any) (int, []byte, error) {
	var reader io.Reader
	if body != nil {
		encoded, err := json.Marshal(body)
		if err != nil {
			return 0, nil, httperr.New(httperr.Internal, httperr.WithCause(err))
		}
		reader = bytes.NewReader(encoded)
	}
	req, err := http.NewRequestWithContext(ctx, method, h.baseURL+path, reader)
	if err != nil {
		return 0, nil, httperr.New(httperr.Internal, httperr.WithCause(err))
	}
	if cookie != "" {
		req.Header.Set("Cookie", cookie)
	}
	if bearer != "" {
		req.Header.Set("Authorization", "Bearer "+bearer)
	}
	if body != nil {
		req.Header.Set("Content-Type", "application/json")
		// Better Auth CSRF protection requires a trusted Origin on POSTs.
		req.Header.Set("Origin", h.baseURL)
	}

	resp, err := h.client.Do(req)
	if err != nil {
		return 0, nil, classifyTransport(err)
	}
	defer func() { _ = resp.Body.Close() }()

	payload, err := io.ReadAll(io.LimitReader(resp.Body, maxAuthResponseBytes))
	if err != nil {
		return 0, nil, classifyTransport(err)
	}
	return resp.StatusCode, payload, nil
}

func (h *HTTPClient) Session(ctx context.Context, cookie string) (*Session, error) {
	if cookie == "" {
		return nil, httperr.New(httperr.Unauthenticated)
	}
	status, payload, err := h.do(ctx, http.MethodGet, "/api/auth/get-session", cookie, nil)
	if err != nil {
		return nil, err
	}
	if status == http.StatusUnauthorized {
		return nil, httperr.New(httperr.Unauthenticated)
	}
	if status != http.StatusOK {
		return nil, httperr.New(httperr.Internal,
			httperr.WithCause(fmt.Errorf("auth session endpoint returned %d", status)))
	}

	var parsed struct {
		User *struct {
			ID string `json:"id"`
		} `json:"user"`
	}
	// Better Auth returns `null` for an anonymous request.
	if len(bytes.TrimSpace(payload)) == 0 || bytes.Equal(bytes.TrimSpace(payload), []byte("null")) {
		return nil, httperr.New(httperr.Unauthenticated)
	}
	if err := json.Unmarshal(payload, &parsed); err != nil {
		return nil, httperr.New(httperr.ServiceUnavailable, httperr.WithCause(err))
	}
	if parsed.User == nil || parsed.User.ID == "" {
		return nil, httperr.New(httperr.Unauthenticated)
	}
	return &Session{UserID: parsed.User.ID}, nil
}

func (h *HTTPClient) RequirePermission(ctx context.Context, cookie, entity, action string) error {
	// Grant-aware endpoint: role ACL + pergrp/perusr grant tables, resolved by
	// the TS app's grant resolver (single source of truth). Same contract as
	// better-auth's /api/auth/admin/has-permission ({permissions} -> {success}).
	status, payload, err := h.do(ctx, http.MethodPost, "/api/rest/authz/has-permission", cookie, map[string]any{
		"permissions": map[string][]string{entity: {action}},
	})
	if err != nil {
		return err
	}
	if status == http.StatusUnauthorized {
		return httperr.New(httperr.Unauthenticated)
	}
	if status == http.StatusForbidden {
		return httperr.New(httperr.Forbidden)
	}
	if status != http.StatusOK {
		return httperr.New(httperr.Internal,
			httperr.WithCause(fmt.Errorf("auth permission endpoint returned %d", status)))
	}

	var parsed struct {
		Success bool `json:"success"`
	}
	if err := json.Unmarshal(payload, &parsed); err != nil {
		return httperr.New(httperr.ServiceUnavailable, httperr.WithCause(err))
	}
	if !parsed.Success {
		return httperr.New(httperr.Forbidden)
	}
	return nil
}

// SessionBearer resolves the session for a v2 bearer access token. The
// token is forwarded as Authorization: Bearer; Better Auth's bearer boundary
// validates it (the SPEC-003 PKCE token service is the SPEC-007 integration
// step — until it ships on the TypeScript side, every real token resolves
// through the same endpoint contract).
func (h *HTTPClient) SessionBearer(ctx context.Context, token string) (*Session, error) {
	if token == "" {
		return nil, httperr.New(httperr.Unauthenticated)
	}
	status, payload, err := h.doWith(ctx, http.MethodGet, "/api/auth/get-session", "", token, nil)
	if err != nil {
		return nil, err
	}
	if status == http.StatusUnauthorized || status == http.StatusForbidden {
		return nil, httperr.New(httperr.Unauthenticated)
	}
	if status != http.StatusOK {
		// Fail closed and retryable: the authority is unavailable.
		return nil, httperr.New(httperr.ServiceUnavailable,
			httperr.WithCause(fmt.Errorf("auth session endpoint returned %d", status)))
	}

	var parsed struct {
		User *struct {
			ID string `json:"id"`
		} `json:"user"`
	}
	if len(bytes.TrimSpace(payload)) == 0 || bytes.Equal(bytes.TrimSpace(payload), []byte("null")) {
		return nil, httperr.New(httperr.Unauthenticated)
	}
	if err := json.Unmarshal(payload, &parsed); err != nil {
		return nil, httperr.New(httperr.ServiceUnavailable, httperr.WithCause(err))
	}
	if parsed.User == nil || parsed.User.ID == "" {
		return nil, httperr.New(httperr.Unauthenticated)
	}
	return &Session{UserID: parsed.User.ID}, nil
}

// RequirePermissionBearer checks one entity/action permission for the
// bearer token's actor through the grant-aware TypeScript boundary. Grant
// precedence lives only there; Go never infers permissions from metadata.
func (h *HTTPClient) RequirePermissionBearer(ctx context.Context, token, entity, action string) error {
	if token == "" {
		return httperr.New(httperr.Unauthenticated)
	}
	status, payload, err := h.doWith(ctx, http.MethodPost, "/api/rest/authz/has-permission", "", token, map[string]any{
		"permissions": map[string][]string{entity: {action}},
	})
	if err != nil {
		return err
	}
	if status == http.StatusUnauthorized {
		return httperr.New(httperr.Unauthenticated)
	}
	if status == http.StatusForbidden {
		return httperr.New(httperr.Forbidden)
	}
	if status != http.StatusOK {
		// Outage (5xx or unexpected shape) fails closed but retryable.
		return httperr.New(httperr.ServiceUnavailable,
			httperr.WithCause(fmt.Errorf("auth permission endpoint returned %d", status)))
	}

	var parsed struct {
		Success bool `json:"success"`
	}
	if err := json.Unmarshal(payload, &parsed); err != nil {
		return httperr.New(httperr.ServiceUnavailable, httperr.WithCause(err))
	}
	if !parsed.Success {
		return httperr.New(httperr.Forbidden)
	}
	return nil
}

func (h *HTTPClient) Capabilities(ctx context.Context, cookie, entity string) Capabilities {
	check := func(action string) bool {
		return h.RequirePermission(ctx, cookie, entity, action) == nil
	}
	// Fail closed: any error counts as denied.
	return Capabilities{
		CanRead:   check("read"),
		CanCreate: check("create"),
		CanUpdate: check("update"),
		CanDelete: check("delete"),
	}
}
