---
to: generated/.pollux-go-staging/internal/config/config_test.go
force: true
---
// Code generated by Pollux (go backend). DO NOT EDIT.
package config

import (
	"strings"
	"testing"
)

func base() []string {
	return []string{
		"POLLUX_DATABASE_URL=postgres://x",
		"POLLUX_AUTH_BASE_URL=http://localhost:3000/",
	}
}

func TestLoadDefaults(t *testing.T) {
	cfg, err := Load(base())
	if err != nil {
		t.Fatalf("unexpected error: %v", err)
	}
	if cfg.Port != 8080 || cfg.DBMaxOpenConns != 10 {
		t.Fatalf("unexpected defaults: %+v", cfg)
	}
	if cfg.AuthBaseURL != "http://localhost:3000" {
		t.Fatalf("base url not normalized: %q", cfg.AuthBaseURL)
	}
	if len(cfg.CORSAllowedOrigins) != 0 {
		t.Fatal("CORS must be disabled by default")
	}
}

func TestLoadAggregatesErrors(t *testing.T) {
	_, err := Load([]string{
		"POLLUX_PORT=notaport",
		"POLLUX_AUTH_TIMEOUT=-3s",
	})
	if err == nil {
		t.Fatal("expected aggregated error")
	}
	message := err.Error()
	for _, expected := range []string{"POLLUX_PORT", "POLLUX_AUTH_TIMEOUT", "POLLUX_DATABASE_URL", "POLLUX_AUTH_BASE_URL"} {
		if !strings.Contains(message, expected) {
			t.Fatalf("error %q missing %q", message, expected)
		}
	}
}

func TestLoadRejectsWildcards(t *testing.T) {
	_, err := Load(append(base(),
		"POLLUX_CORS_ALLOWED_ORIGINS=*",
		"POLLUX_TRUSTED_PROXIES=0.0.0.0/0",
	))
	if err == nil {
		t.Fatal("expected wildcard rejection")
	}
}
