---
to: generated/.pollux-go-staging/internal/config/config.go
force: true
---
// Code generated by Pollux (go backend). DO NOT EDIT.
package config

import (
	"errors"
	"fmt"
	"strconv"
	"strings"
	"time"
)

// Config is parsed explicitly from the environment; every invalid value is
// reported together in one aggregated startup error.
type Config struct {
	Port            int
	DatabaseURL     string
	AuthBaseURL     string
	AuthTimeout     time.Duration
	RequestTimeout  time.Duration
	ShutdownTimeout time.Duration

	DBMaxOpenConns    int
	DBMaxIdleConns    int
	DBConnMaxLifetime time.Duration
	DBConnMaxIdleTime time.Duration

	// v2 idempotency bounds (SPEC-003): completed-record retention, the
	// bounded wait applied to concurrent in-progress duplicates, and the
	// periodic cleanup interval.
	IdempotencyRetention       time.Duration
	IdempotencyWaitBound       time.Duration
	IdempotencyCleanupInterval time.Duration

	MaxBodyBytes   int64
	TrustedProxies []string
	// CORS is disabled unless explicit origins are configured.
	CORSAllowedOrigins []string
}

func env(environ []string, key string) (string, bool) {
	prefix := key + "="
	for _, kv := range environ {
		if strings.HasPrefix(kv, prefix) {
			return strings.TrimPrefix(kv, prefix), true
		}
	}
	return "", false
}

func Load(environ []string) (*Config, error) {
	var problems []string

	str := func(key, fallback string, required bool) string {
		value, ok := env(environ, key)
		if !ok || value == "" {
			if required {
				problems = append(problems, key+" is required")
			}
			return fallback
		}
		return value
	}
	num := func(key string, fallback, min, max int) int {
		value, ok := env(environ, key)
		if !ok || value == "" {
			return fallback
		}
		parsed, err := strconv.Atoi(value)
		if err != nil || parsed < min || parsed > max {
			problems = append(problems, fmt.Sprintf("%s must be an integer in [%d, %d]", key, min, max))
			return fallback
		}
		return parsed
	}
	dur := func(key string, fallback time.Duration) time.Duration {
		value, ok := env(environ, key)
		if !ok || value == "" {
			return fallback
		}
		parsed, err := time.ParseDuration(value)
		if err != nil || parsed <= 0 {
			problems = append(problems, key+" must be a positive Go duration")
			return fallback
		}
		return parsed
	}
	list := func(key string) []string {
		value, ok := env(environ, key)
		if !ok || value == "" {
			return nil
		}
		var out []string
		for _, item := range strings.Split(value, ",") {
			item = strings.TrimSpace(item)
			if item != "" {
				out = append(out, item)
			}
		}
		return out
	}

	cfg := &Config{
		Port:            num("POLLUX_PORT", 8080, 1, 65535),
		DatabaseURL:     str("POLLUX_DATABASE_URL", "", true),
		AuthBaseURL:     strings.TrimRight(str("POLLUX_AUTH_BASE_URL", "", true), "/"),
		AuthTimeout:     dur("POLLUX_AUTH_TIMEOUT", 3*time.Second),
		RequestTimeout:  dur("POLLUX_REQUEST_TIMEOUT", 15*time.Second),
		ShutdownTimeout: dur("POLLUX_SHUTDOWN_TIMEOUT", 10*time.Second),

		DBMaxOpenConns:    num("POLLUX_DB_MAX_OPEN_CONNS", 10, 1, 500),
		DBMaxIdleConns:    num("POLLUX_DB_MAX_IDLE_CONNS", 5, 0, 500),
		DBConnMaxLifetime: dur("POLLUX_DB_CONN_MAX_LIFETIME", 30*time.Minute),
		DBConnMaxIdleTime: dur("POLLUX_DB_CONN_MAX_IDLE_TIME", 5*time.Minute),

		IdempotencyRetention:       dur("POLLUX_IDEMPOTENCY_RETENTION", 24*time.Hour),
		IdempotencyWaitBound:       dur("POLLUX_IDEMPOTENCY_WAIT_BOUND", 2*time.Second),
		IdempotencyCleanupInterval: dur("POLLUX_IDEMPOTENCY_CLEANUP_INTERVAL", time.Hour),

		MaxBodyBytes:       int64(num("POLLUX_MAX_BODY_BYTES", 1<<20, 1024, 64<<20)),
		TrustedProxies:     list("POLLUX_TRUSTED_PROXIES"),
		CORSAllowedOrigins: list("POLLUX_CORS_ALLOWED_ORIGINS"),
	}

	for _, origin := range cfg.CORSAllowedOrigins {
		if origin == "*" {
			problems = append(problems, "POLLUX_CORS_ALLOWED_ORIGINS must not contain '*'")
		}
	}
	for _, proxy := range cfg.TrustedProxies {
		if proxy == "*" || proxy == "0.0.0.0/0" || proxy == "::/0" {
			problems = append(problems, "POLLUX_TRUSTED_PROXIES must not trust all proxies")
		}
	}

	if len(problems) > 0 {
		return nil, errors.New(strings.Join(problems, "; "))
	}
	return cfg, nil
}
