---
to: generated/.pollux-go-staging/internal/database/postgres.go
force: true
---
// Code generated by Pollux (go backend). DO NOT EDIT.
package database

import (
	"context"
	"database/sql"
	"time"

	"github.com/jackc/pgx/v5/stdlib"
	_ "github.com/jackc/pgx/v5/stdlib" // pgx database/sql driver
	"github.com/uptrace/bun"
	"github.com/uptrace/bun/dialect/pgdialect"

	"pollux-go/internal/config"
)

var _ = stdlib.GetDefaultDriver // keep the pgx stdlib dependency explicit

// Open creates the single sql.DB/bun.DB pair for the process, applies the
// configured pool limits and verifies readiness with a bounded ping.
func Open(ctx context.Context, cfg *config.Config) (*bun.DB, error) {
	sqldb, err := sql.Open("pgx", cfg.DatabaseURL)
	if err != nil {
		return nil, err
	}
	sqldb.SetMaxOpenConns(cfg.DBMaxOpenConns)
	sqldb.SetMaxIdleConns(cfg.DBMaxIdleConns)
	sqldb.SetConnMaxLifetime(cfg.DBConnMaxLifetime)
	sqldb.SetConnMaxIdleTime(cfg.DBConnMaxIdleTime)

	pingCtx, cancel := context.WithTimeout(ctx, 5*time.Second)
	defer cancel()
	if err := sqldb.PingContext(pingCtx); err != nil {
		_ = sqldb.Close()
		return nil, err
	}

	return bun.NewDB(sqldb, pgdialect.New()), nil
}

// Ping is the bounded readiness check.
func Ping(ctx context.Context, db *bun.DB) error {
	pingCtx, cancel := context.WithTimeout(ctx, 2*time.Second)
	defer cancel()
	return db.PingContext(pingCtx)
}
