---
to: generated/.pollux-go-staging/internal/httperr/error.go
force: true
---
// Code generated by Pollux (go backend). DO NOT EDIT.
package httperr

import (
	"context"
	"errors"
	"net/http"

	"github.com/jackc/pgx/v5/pgconn"
)

// Code is the stable public error taxonomy shared with the TypeScript
// backend (src/lib/generated-crud.ts).
type Code string

const (
	Unauthenticated    Code = "UNAUTHENTICATED"
	Forbidden          Code = "FORBIDDEN"
	ValidationFailed   Code = "VALIDATION_FAILED"
	NotFound           Code = "NOT_FOUND"
	Conflict           Code = "CONFLICT"
	ReferenceConflict  Code = "REFERENCE_CONFLICT"
	StaleWrite         Code = "STALE_WRITE"
	RateLimited        Code = "RATE_LIMITED"
	ServiceUnavailable Code = "SERVICE_UNAVAILABLE"
	Internal           Code = "INTERNAL"
)

// Public Portuguese messages, identical to the TypeScript contract.
var messages = map[Code]string{
	Unauthenticated:    "Sessão expirada. Faça login novamente.",
	Forbidden:          "Você não tem permissão para esta operação.",
	ValidationFailed:   "Dados inválidos. Verifique os campos e tente novamente.",
	NotFound:           "Registro não encontrado.",
	Conflict:           "Já existe um registro com estes dados.",
	ReferenceConflict:  "Existem registros utilizados em outras tabelas - Nenhuma exclusão foi realizada",
	StaleWrite:         "Este registro foi alterado por outro usuário. Recarregue os dados.",
	RateLimited:        "Muitas solicitações. Aguarde um instante e tente novamente.",
	ServiceUnavailable: "Serviço temporariamente indisponível. Tente novamente.",
	Internal:           "Erro inesperado. Tente novamente ou contate o suporte.",
}

var retryable = map[Code]bool{
	RateLimited:        true,
	ServiceUnavailable: true,
}

var statuses = map[Code]int{
	Unauthenticated:    http.StatusUnauthorized,
	Forbidden:          http.StatusForbidden,
	ValidationFailed:   http.StatusBadRequest,
	NotFound:           http.StatusNotFound,
	Conflict:           http.StatusConflict,
	ReferenceConflict:  http.StatusConflict,
	StaleWrite:         http.StatusConflict,
	RateLimited:        http.StatusTooManyRequests,
	ServiceUnavailable: http.StatusServiceUnavailable,
	Internal:           http.StatusInternalServerError,
}

// E is the internal error carrier. The cause stays server-side; only the
// code, public message and field errors are ever serialized.
type E struct {
	Code        Code
	Message     string
	FieldErrors map[string][]string
	cause       error
}

func (e *E) Error() string { return string(e.Code) + ": " + e.Message }
func (e *E) Unwrap() error { return e.cause }

func (e *E) Retryable() bool  { return retryable[e.Code] }
func (e *E) HTTPStatus() int  { return statuses[e.Code] }
func (e *E) Cause() error     { return e.cause }
func Message(code Code) string { return messages[code] }

type Option func(*E)

func WithMessage(message string) Option {
	return func(e *E) { e.Message = message }
}

func WithFieldErrors(fieldErrors map[string][]string) Option {
	return func(e *E) { e.FieldErrors = fieldErrors }
}

func WithCause(cause error) Option {
	return func(e *E) { e.cause = cause }
}

func New(code Code, opts ...Option) *E {
	e := &E{Code: code, Message: messages[code]}
	for _, opt := range opts {
		opt(e)
	}
	return e
}

func isTransientSQLState(code string) bool {
	return code == "40001" || code == "40P01" ||
		(len(code) >= 2 && code[:2] == "08") || code == "57P03"
}

// Map classifies any error into the public taxonomy. SQLSTATE codes, never
// message substrings. Context cancellation is handled explicitly.
func Map(err error) *E {
	if err == nil {
		return nil
	}

	var typed *E
	if errors.As(err, &typed) {
		return typed
	}

	if errors.Is(err, context.DeadlineExceeded) || errors.Is(err, context.Canceled) {
		return New(ServiceUnavailable, WithCause(err))
	}

	var pgErr *pgconn.PgError
	if errors.As(err, &pgErr) {
		switch {
		case pgErr.Code == "23505":
			return New(Conflict, WithCause(err))
		case pgErr.Code == "23503":
			return New(ReferenceConflict, WithCause(err))
		case pgErr.Code == "23502" || pgErr.Code == "23514" ||
			pgErr.Code == "22P02" || pgErr.Code == "22003" || pgErr.Code == "22001":
			return New(ValidationFailed, WithCause(err))
		case isTransientSQLState(pgErr.Code):
			return New(ServiceUnavailable, WithCause(err))
		default:
			return New(Internal, WithCause(err))
		}
	}

	return New(Internal, WithCause(err))
}
