---
to: generated/.pollux-go-staging/internal/httperr/error_test.go
force: true
---
// Code generated by Pollux (go backend). DO NOT EDIT.
package httperr

import (
	"context"
	"errors"
	"fmt"
	"net/http"
	"strings"
	"testing"

	"github.com/jackc/pgx/v5/pgconn"
)

func TestMapSQLStates(t *testing.T) {
	cases := map[string]Code{
		"23505": Conflict,
		"23503": ReferenceConflict,
		"23502": ValidationFailed,
		"23514": ValidationFailed,
		"22P02": ValidationFailed,
		"22003": ValidationFailed,
		"22001": ValidationFailed,
		"40001": ServiceUnavailable,
		"40P01": ServiceUnavailable,
		"08006": ServiceUnavailable,
		"57P03": ServiceUnavailable,
		"42703": Internal,
	}
	for sqlstate, expected := range cases {
		err := fmt.Errorf("wrapped: %w", &pgconn.PgError{Code: sqlstate, Message: "raw db detail"})
		mapped := Map(err)
		if mapped.Code != expected {
			t.Fatalf("SQLSTATE %s: expected %s, got %s", sqlstate, expected, mapped.Code)
		}
		if strings.Contains(mapped.Message, "raw db detail") {
			t.Fatalf("SQLSTATE %s leaked db text into public message", sqlstate)
		}
	}
}

func TestMapContextAndUnknown(t *testing.T) {
	if Map(context.DeadlineExceeded).Code != ServiceUnavailable {
		t.Fatal("deadline must map to SERVICE_UNAVAILABLE")
	}
	if Map(context.Canceled).Code != ServiceUnavailable {
		t.Fatal("cancellation must map to SERVICE_UNAVAILABLE")
	}
	mapped := Map(errors.New("secret internal detail"))
	if mapped.Code != Internal {
		t.Fatal("unknown errors must map to INTERNAL")
	}
	if strings.Contains(mapped.Message, "secret") {
		t.Fatal("internal detail leaked into public message")
	}
}

func TestMapPassthroughAndStatus(t *testing.T) {
	original := New(StaleWrite)
	if Map(fmt.Errorf("wrap: %w", original)) != original {
		t.Fatal("typed errors must pass through")
	}
	if New(StaleWrite).HTTPStatus() != http.StatusConflict {
		t.Fatal("stale write must be 409")
	}
	if New(Unauthenticated).HTTPStatus() != http.StatusUnauthorized {
		t.Fatal("unauthenticated must be 401")
	}
	if !New(ServiceUnavailable).Retryable() || New(Forbidden).Retryable() {
		t.Fatal("retryable flags wrong")
	}
}
