---
to: generated/.pollux-go-staging/internal/idempotency/idempotency.go
force: true
---
// Code generated by Pollux (go backend). DO NOT EDIT.
package idempotency

import (
	"bytes"
	"context"
	"crypto/sha256"
	"database/sql"
	"encoding/hex"
	"encoding/json"
	"errors"
	"time"

	"github.com/google/uuid"
	"github.com/uptrace/bun"

	"pollux-go/internal/httperr"
)

// Idempotency for the v2 contract (test-fixtures/pollux/api/contract.md):
// every POST/PATCH/DELETE requires an Idempotency-Key. A key is scoped by
// (actorId, clientId, method, canonicalPath, key). The record is inserted —
// state in_progress, SHA-256 canonical body hash — inside the SAME database
// transaction that performs the mutation, and completed (status + exact
// response envelope bytes) before that transaction commits. PostgreSQL's
// unique index makes a concurrent duplicate INSERT wait for the first
// transaction, so the mutation can never run twice concurrently.
//
// Interim client identity: until the SPEC-003 PKCE token service ships,
// ClientID carries the bearer subject (actor id). Post-PKCE, the token's
// authorized-party (azp) claim lands in ClientID; the scope column layout
// already accounts for it.

const (
	StateInProgress = "in_progress"
	StateComplete   = "complete"

	maxKeyLength = 200
)

// Package-level bounds, adjustable once at boot via Configure (entity route
// registration cannot receive config without changing the generated
// registration signature).
var (
	retention    = 24 * time.Hour
	waitBound    = 2 * time.Second
	pollInterval = 100 * time.Millisecond
)

// Configure sets the retention window and the bounded wait applied to
// concurrent in-progress duplicates. Call once at boot, before serving.
func Configure(retentionWindow, duplicateWaitBound time.Duration) {
	if retentionWindow > 0 {
		retention = retentionWindow
	}
	if duplicateWaitBound > 0 {
		waitBound = duplicateWaitBound
	}
}

// Record is the idempotency table row. The five scope columns share one
// unique constraint; response_body stores the exact envelope bytes.
type Record struct {
	bun.BaseModel `bun:"table:pollux_idempotency"`

	ID           string    `bun:"id,pk"`
	ActorID      string    `bun:"actor_id,notnull,unique:pollux_idempotency_scope"`
	ClientID     string    `bun:"client_id,notnull,unique:pollux_idempotency_scope"`
	Method       string    `bun:"method,notnull,unique:pollux_idempotency_scope"`
	Path         string    `bun:"path,notnull,unique:pollux_idempotency_scope"`
	Key          string    `bun:"idem_key,notnull,unique:pollux_idempotency_scope"`
	BodyHash     string    `bun:"body_hash,notnull"`
	State        string    `bun:"state,notnull"`
	HTTPStatus   int       `bun:"http_status"`
	ResponseBody []byte    `bun:"response_body"`
	CreatedAt    time.Time `bun:"created_at,notnull"`
	ExpiresAt    time.Time `bun:"expires_at,notnull"`
}

// EnsureSchema creates the idempotency table (and its composite unique
// constraint) when absent. The Go service owns this table; it is not part
// of the TypeScript Drizzle schema.
func EnsureSchema(ctx context.Context, db *bun.DB) error {
	_, err := db.NewCreateTable().
		Model((*Record)(nil)).
		IfNotExists().
		Exec(ctx)
	return err
}

// Scope identifies one logical submission.
type Scope struct {
	ActorID  string
	ClientID string
	Method   string
	Path     string
	Key      string
}

// ValidateKey bounds the Idempotency-Key header. A missing key is
// VALIDATION_FAILED per the contract.
func ValidateKey(key string) error {
	if key == "" {
		return httperr.New(httperr.ValidationFailed,
			httperr.WithMessage("Cabeçalho Idempotency-Key é obrigatório."),
			httperr.WithFieldErrors(map[string][]string{"Idempotency-Key": {"required"}}))
	}
	if len(key) > maxKeyLength {
		return httperr.New(httperr.ValidationFailed,
			httperr.WithFieldErrors(map[string][]string{"Idempotency-Key": {"too_long"}}))
	}
	return nil
}

// BodyHash hashes the canonical JSON body: object keys sorted (Go sorts map
// keys by Unicode code point — identical to the contract's UTF-16 code-unit
// order for all BMP field names), number literals preserved via json.Number,
// and an absent body hashing the empty string.
func BodyHash(raw []byte) (string, error) {
	trimmed := bytes.TrimSpace(raw)
	if len(trimmed) == 0 {
		sum := sha256.Sum256(nil)
		return hex.EncodeToString(sum[:]), nil
	}
	decoder := json.NewDecoder(bytes.NewReader(trimmed))
	decoder.UseNumber()
	var value any
	if err := decoder.Decode(&value); err != nil {
		return "", httperr.New(httperr.ValidationFailed, httperr.WithCause(err))
	}
	canonical, err := json.Marshal(value)
	if err != nil {
		return "", httperr.New(httperr.Internal, httperr.WithCause(err))
	}
	sum := sha256.Sum256(canonical)
	return hex.EncodeToString(sum[:]), nil
}

// Outcome is the response to write: stored (replayed) or fresh.
type Outcome struct {
	Status   int
	Body     []byte
	Replayed bool
}

// Mutation runs inside the idempotency transaction and returns the HTTP
// status plus the exact response envelope bytes to store and send.
type Mutation func(ctx context.Context, tx bun.Tx) (int, []byte, error)

var errDuplicate = errors.New("idempotency: duplicate scope")

// Store executes mutations under idempotency control.
type Store struct {
	db *bun.DB
}

func NewStore(db *bun.DB) *Store { return &Store{db: db} }

// Execute performs fn exactly once per scope+body. Completed replays return
// the stored status/body with Replayed=true; a different body for the same
// scope is CONFLICT with no mutation; a concurrent in-progress duplicate
// waits within the configured bound, then replays completion or returns
// retryable SERVICE_UNAVAILABLE. A failed mutation rolls the idempotency
// record back with it, so the key stays usable for a clean retry.
func (s *Store) Execute(ctx context.Context, scope Scope, bodyHash string, fn Mutation) (*Outcome, error) {
	return s.execute(ctx, scope, bodyHash, fn, true)
}

func (s *Store) execute(ctx context.Context, scope Scope, bodyHash string, fn Mutation, retryExpired bool) (*Outcome, error) {
	now := time.Now().UTC()
	record := &Record{
		ID:        uuid.NewString(),
		ActorID:   scope.ActorID,
		ClientID:  scope.ClientID,
		Method:    scope.Method,
		Path:      scope.Path,
		Key:       scope.Key,
		BodyHash:  bodyHash,
		State:     StateInProgress,
		CreatedAt: now,
		ExpiresAt: now.Add(retention),
	}

	var outcome *Outcome
	err := s.db.RunInTx(ctx, &sql.TxOptions{}, func(ctx context.Context, tx bun.Tx) error {
		inserted, err := tx.NewInsert().
			Model(record).
			On("CONFLICT DO NOTHING").
			Exec(ctx)
		if err != nil {
			return err
		}
		affected, err := inserted.RowsAffected()
		if err != nil {
			return err
		}
		if affected == 0 {
			return errDuplicate
		}

		status, body, err := fn(ctx, tx)
		if err != nil {
			return err
		}
		completedAt := time.Now().UTC()
		_, err = tx.NewUpdate().
			Model((*Record)(nil)).
			Set("state = ?", StateComplete).
			Set("http_status = ?", status).
			Set("response_body = ?", body).
			Set("expires_at = ?", completedAt.Add(retention)).
			Where("id = ?", record.ID).
			Exec(ctx)
		if err != nil {
			return err
		}
		outcome = &Outcome{Status: status, Body: body}
		return nil
	})
	if err == nil {
		return outcome, nil
	}
	if !errors.Is(err, errDuplicate) {
		return nil, err
	}
	return s.resolveDuplicate(ctx, scope, bodyHash, fn, retryExpired)
}

// resolveDuplicate handles an existing record for the scope. The unique
// index already serialized us behind the original transaction, so a
// committed record is normally complete by the time we read it.
func (s *Store) resolveDuplicate(ctx context.Context, scope Scope, bodyHash string, fn Mutation, retryExpired bool) (*Outcome, error) {
	deadline := time.Now().Add(waitBound)
	for {
		existing := new(Record)
		err := s.db.NewSelect().
			Model(existing).
			Where("actor_id = ?", scope.ActorID).
			Where("client_id = ?", scope.ClientID).
			Where("method = ?", scope.Method).
			Where("path = ?", scope.Path).
			Where("idem_key = ?", scope.Key).
			Limit(1).
			Scan(ctx)
		if errors.Is(err, sql.ErrNoRows) {
			// The original transaction rolled back after our conflict.
			// Fail retryable rather than racing a re-insert.
			return nil, httperr.New(httperr.ServiceUnavailable)
		}
		if err != nil {
			return nil, err
		}

		if existing.State == StateComplete && retryExpired &&
			time.Now().UTC().After(existing.ExpiresAt) {
			// Expired completed record: discard and run fresh (cleanup may
			// not have swept it yet). Never touches in_progress records.
			_, err := s.db.NewDelete().
				Model((*Record)(nil)).
				Where("id = ?", existing.ID).
				Where("state = ?", StateComplete).
				Where("expires_at < ?", time.Now().UTC()).
				Exec(ctx)
			if err != nil {
				return nil, err
			}
			return s.execute(ctx, scope, bodyHash, fn, false)
		}

		if existing.BodyHash != bodyHash {
			return nil, httperr.New(httperr.Conflict,
				httperr.WithMessage("Idempotency-Key reutilizada com um corpo diferente."))
		}
		if existing.State == StateComplete {
			return &Outcome{
				Status:   existing.HTTPStatus,
				Body:     existing.ResponseBody,
				Replayed: true,
			}, nil
		}

		if time.Now().After(deadline) {
			return nil, httperr.New(httperr.ServiceUnavailable)
		}
		select {
		case <-ctx.Done():
			return nil, httperr.New(httperr.ServiceUnavailable, httperr.WithCause(ctx.Err()))
		case <-time.After(pollInterval):
		}
	}
}

// Cleanup deletes only expired COMPLETED records; live in_progress records
// are never deleted. Returns the number of rows removed.
func Cleanup(ctx context.Context, db *bun.DB) (int64, error) {
	result, err := db.NewDelete().
		Model((*Record)(nil)).
		Where("state = ?", StateComplete).
		Where("expires_at < ?", time.Now().UTC()).
		Exec(ctx)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}
