---
to: generated/.pollux-go-staging/internal/idempotency/idempotency_pg_test.go
force: true
---
// Code generated by Pollux (go backend). DO NOT EDIT.
package idempotency

import (
	"context"
	"database/sql"
	"errors"
	"fmt"
	"net/http"
	"os"
	"sync"
	"testing"
	"time"

	"github.com/google/uuid"
	"github.com/uptrace/bun"
	"github.com/uptrace/bun/dialect/pgdialect"

	_ "github.com/jackc/pgx/v5/stdlib"

	"pollux-go/internal/httperr"
)

// PostgreSQL integration tests for the idempotency machinery. They run only
// when POLLUX_TEST_DATABASE_URL is set, mirroring the entity repository
// integration tests.
func testDB(t *testing.T) *bun.DB {
	t.Helper()
	url := os.Getenv("POLLUX_TEST_DATABASE_URL")
	if url == "" {
		t.Skip("POLLUX_TEST_DATABASE_URL not set; skipping PostgreSQL integration test")
	}
	sqldb, err := sql.Open("pgx", url)
	if err != nil {
		t.Fatalf("open: %v", err)
	}
	t.Cleanup(func() { _ = sqldb.Close() })
	db := bun.NewDB(sqldb, pgdialect.New())
	if err := EnsureSchema(context.Background(), db); err != nil {
		t.Fatalf("ensure schema: %v", err)
	}
	return db
}

func testScope() Scope {
	return Scope{
		ActorID:  "actor-1",
		ClientID: "actor-1",
		Method:   http.MethodPost,
		Path:     "/api/generated/v2/testentity",
		Key:      uuid.NewString(),
	}
}

// countingMutation counts real executions; the body it returns embeds the
// execution ordinal so replays are provably the stored bytes.
func countingMutation(counter *int, mu *sync.Mutex) Mutation {
	return func(ctx context.Context, tx bun.Tx) (int, []byte, error) {
		mu.Lock()
		*counter++
		n := *counter
		mu.Unlock()
		return http.StatusCreated, []byte(fmt.Sprintf(`{"ok":true,"data":{"execution":%d}}`, n)), nil
	}
}

func TestExecuteReplaySameBody(t *testing.T) {
	db := testDB(t)
	store := NewStore(db)
	scope := testScope()
	hash, _ := BodyHash([]byte(`{"titulo":"a"}`))

	var mu sync.Mutex
	executions := 0
	first, err := store.Execute(context.Background(), scope, hash, countingMutation(&executions, &mu))
	if err != nil {
		t.Fatalf("first execute: %v", err)
	}
	if first.Replayed || first.Status != http.StatusCreated {
		t.Fatalf("first outcome unexpected: %+v", first)
	}

	replay, err := store.Execute(context.Background(), scope, hash, countingMutation(&executions, &mu))
	if err != nil {
		t.Fatalf("replay execute: %v", err)
	}
	if !replay.Replayed {
		t.Fatal("second call must be a replay")
	}
	if string(replay.Body) != string(first.Body) || replay.Status != first.Status {
		t.Fatalf("replay must return the exact stored response: %+v vs %+v", replay, first)
	}
	if executions != 1 {
		t.Fatalf("mutation ran %d times, want 1", executions)
	}
}

func TestExecuteDifferentBodyIsConflict(t *testing.T) {
	db := testDB(t)
	store := NewStore(db)
	scope := testScope()
	hashA, _ := BodyHash([]byte(`{"titulo":"original"}`))
	hashB, _ := BodyHash([]byte(`{"titulo":"diferente"}`))

	var mu sync.Mutex
	executions := 0
	if _, err := store.Execute(context.Background(), scope, hashA, countingMutation(&executions, &mu)); err != nil {
		t.Fatalf("first execute: %v", err)
	}
	_, err := store.Execute(context.Background(), scope, hashB, countingMutation(&executions, &mu))
	var typed *httperr.E
	if !errors.As(err, &typed) || typed.Code != httperr.Conflict {
		t.Fatalf("different body must be CONFLICT, got %v", err)
	}
	if executions != 1 {
		t.Fatalf("conflicting reuse must not mutate again (ran %d times)", executions)
	}
}

func TestExecuteConcurrentDuplicatesRunOnce(t *testing.T) {
	db := testDB(t)
	store := NewStore(db)
	scope := testScope()
	hash, _ := BodyHash([]byte(`{"titulo":"concorrente"}`))

	var mu sync.Mutex
	executions := 0
	slow := func(ctx context.Context, tx bun.Tx) (int, []byte, error) {
		mu.Lock()
		executions++
		mu.Unlock()
		time.Sleep(300 * time.Millisecond) // hold the transaction open
		return http.StatusCreated, []byte(`{"ok":true,"data":{"id":"one"}}`), nil
	}

	const workers = 4
	var wg sync.WaitGroup
	outcomes := make([]*Outcome, workers)
	errs := make([]error, workers)
	for i := 0; i < workers; i++ {
		wg.Add(1)
		go func(i int) {
			defer wg.Done()
			outcomes[i], errs[i] = store.Execute(context.Background(), scope, hash, slow)
		}(i)
	}
	wg.Wait()

	completed := 0
	for i := 0; i < workers; i++ {
		if errs[i] != nil {
			var typed *httperr.E
			if !errors.As(errs[i], &typed) || typed.Code != httperr.ServiceUnavailable {
				t.Fatalf("worker %d: unexpected error %v", i, errs[i])
			}
			continue
		}
		completed++
		if outcomes[i].Status != http.StatusCreated {
			t.Fatalf("worker %d: unexpected status %d", i, outcomes[i].Status)
		}
	}
	if completed == 0 {
		t.Fatal("at least one duplicate must observe the completed mutation")
	}
	if executions != 1 {
		t.Fatalf("mutation ran %d times under concurrency, want exactly 1", executions)
	}
}

func TestFailedMutationRollsBackRecord(t *testing.T) {
	db := testDB(t)
	store := NewStore(db)
	scope := testScope()
	hash, _ := BodyHash([]byte(`{"titulo":"falha"}`))

	boom := errors.New("mutation exploded")
	_, err := store.Execute(context.Background(), scope, hash,
		func(ctx context.Context, tx bun.Tx) (int, []byte, error) {
			return 0, nil, boom
		})
	if !errors.Is(err, boom) {
		t.Fatalf("expected the mutation error back, got %v", err)
	}

	// The record rolled back with the mutation; a clean retry executes.
	var mu sync.Mutex
	executions := 0
	outcome, err := store.Execute(context.Background(), scope, hash, countingMutation(&executions, &mu))
	if err != nil || outcome.Replayed || executions != 1 {
		t.Fatalf("retry after failure must execute fresh: outcome=%+v err=%v runs=%d", outcome, err, executions)
	}
}

func TestCleanupDeletesOnlyExpiredCompleted(t *testing.T) {
	db := testDB(t)
	ctx := context.Background()
	now := time.Now().UTC()

	expired := &Record{
		ID: uuid.NewString(), ActorID: "a", ClientID: "a", Method: "POST",
		Path: "/api/generated/v2/x", Key: uuid.NewString(), BodyHash: "h",
		State: StateComplete, HTTPStatus: 201, ResponseBody: []byte(`{}`),
		CreatedAt: now.Add(-48 * time.Hour), ExpiresAt: now.Add(-24 * time.Hour),
	}
	fresh := &Record{
		ID: uuid.NewString(), ActorID: "a", ClientID: "a", Method: "POST",
		Path: "/api/generated/v2/x", Key: uuid.NewString(), BodyHash: "h",
		State: StateComplete, HTTPStatus: 201, ResponseBody: []byte(`{}`),
		CreatedAt: now, ExpiresAt: now.Add(24 * time.Hour),
	}
	live := &Record{
		ID: uuid.NewString(), ActorID: "a", ClientID: "a", Method: "POST",
		Path: "/api/generated/v2/x", Key: uuid.NewString(), BodyHash: "h",
		State: StateInProgress,
		// Even a stale expiry must never delete an in_progress record.
		CreatedAt: now.Add(-48 * time.Hour), ExpiresAt: now.Add(-24 * time.Hour),
	}
	for _, rec := range []*Record{expired, fresh, live} {
		if _, err := db.NewInsert().Model(rec).Exec(ctx); err != nil {
			t.Fatalf("seed: %v", err)
		}
	}
	t.Cleanup(func() {
		_, _ = db.NewDelete().Model((*Record)(nil)).
			Where("id IN (?)", bun.In([]string{expired.ID, fresh.ID, live.ID})).Exec(ctx)
	})

	if _, err := Cleanup(ctx, db); err != nil {
		t.Fatalf("cleanup: %v", err)
	}

	remaining := 0
	for _, id := range []string{fresh.ID, live.ID} {
		exists, err := db.NewSelect().Model((*Record)(nil)).Where("id = ?", id).Exists(ctx)
		if err != nil {
			t.Fatalf("exists: %v", err)
		}
		if exists {
			remaining++
		}
	}
	if remaining != 2 {
		t.Fatal("cleanup must keep fresh completed and live in_progress records")
	}
	gone, err := db.NewSelect().Model((*Record)(nil)).Where("id = ?", expired.ID).Exists(ctx)
	if err != nil {
		t.Fatalf("exists: %v", err)
	}
	if gone {
		t.Fatal("cleanup must delete the expired completed record")
	}
}

func TestExpiredCompletedRecordExecutesFresh(t *testing.T) {
	db := testDB(t)
	store := NewStore(db)
	scope := testScope()
	hash, _ := BodyHash([]byte(`{"titulo":"expira"}`))
	now := time.Now().UTC()

	stale := &Record{
		ID: uuid.NewString(), ActorID: scope.ActorID, ClientID: scope.ClientID,
		Method: scope.Method, Path: scope.Path, Key: scope.Key, BodyHash: hash,
		State: StateComplete, HTTPStatus: 201, ResponseBody: []byte(`{"old":true}`),
		CreatedAt: now.Add(-48 * time.Hour), ExpiresAt: now.Add(-24 * time.Hour),
	}
	if _, err := db.NewInsert().Model(stale).Exec(context.Background()); err != nil {
		t.Fatalf("seed: %v", err)
	}

	var mu sync.Mutex
	executions := 0
	outcome, err := store.Execute(context.Background(), scope, hash, countingMutation(&executions, &mu))
	if err != nil {
		t.Fatalf("execute after expiry: %v", err)
	}
	if outcome.Replayed || executions != 1 {
		t.Fatalf("expired record must not replay: outcome=%+v runs=%d", outcome, executions)
	}
}
