---
to: generated/.pollux-go-staging/internal/idempotency/idempotency_test.go
force: true
---
// Code generated by Pollux (go backend). DO NOT EDIT.
package idempotency

import (
	"errors"
	"strings"
	"testing"

	"pollux-go/internal/httperr"
)

func codeOf(t *testing.T, err error) httperr.Code {
	t.Helper()
	var typed *httperr.E
	if !errors.As(err, &typed) {
		t.Fatalf("expected *httperr.E, got %T (%v)", err, err)
	}
	return typed.Code
}

func TestValidateKey(t *testing.T) {
	if err := ValidateKey("abc-123"); err != nil {
		t.Fatalf("valid key rejected: %v", err)
	}
	if codeOf(t, ValidateKey("")) != httperr.ValidationFailed {
		t.Fatal("missing key must be VALIDATION_FAILED")
	}
	if codeOf(t, ValidateKey(strings.Repeat("x", 201))) != httperr.ValidationFailed {
		t.Fatal("oversized key must be VALIDATION_FAILED")
	}
}

func TestBodyHashEmptyBody(t *testing.T) {
	// SHA-256 of the empty string per the contract.
	const emptySHA256 = "e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855"
	hash, err := BodyHash(nil)
	if err != nil {
		t.Fatalf("empty body: %v", err)
	}
	if hash != emptySHA256 {
		t.Fatalf("empty body hash = %s, want %s", hash, emptySHA256)
	}
	spaced, _ := BodyHash([]byte("  \n"))
	if spaced != emptySHA256 {
		t.Fatal("whitespace-only body must hash like the empty string")
	}
}

func TestBodyHashCanonicalKeyOrder(t *testing.T) {
	a, err := BodyHash([]byte(`{"b":1,"a":{"y":2,"x":3}}`))
	if err != nil {
		t.Fatalf("hash a: %v", err)
	}
	b, err := BodyHash([]byte(`{ "a": {"x":3, "y":2}, "b": 1 }`))
	if err != nil {
		t.Fatalf("hash b: %v", err)
	}
	if a != b {
		t.Fatal("key order and whitespace must not change the canonical hash")
	}
	c, _ := BodyHash([]byte(`{"b":2,"a":{"y":2,"x":3}}`))
	if a == c {
		t.Fatal("different values must change the hash")
	}
}

func TestBodyHashPreservesNumberLiterals(t *testing.T) {
	a, _ := BodyHash([]byte(`{"preco":"1234.50"}`))
	b, _ := BodyHash([]byte(`{"preco":"1234.5"}`))
	if a == b {
		t.Fatal("decimal string literals must hash differently")
	}
	big1, _ := BodyHash([]byte(`{"n":9007199254740993}`))
	big2, _ := BodyHash([]byte(`{"n":9007199254740992}`))
	if big1 == big2 {
		t.Fatal("64-bit integers must not collapse through float64")
	}
}

func TestBodyHashRejectsMalformedJSON(t *testing.T) {
	_, err := BodyHash([]byte(`{not json`))
	if codeOf(t, err) != httperr.ValidationFailed {
		t.Fatal("malformed body must be VALIDATION_FAILED")
	}
}
