---
to: generated/.pollux-go-staging/cmd/api/main.go
force: true
---
// Code generated by Pollux (go backend). DO NOT EDIT.
package main

import (
	"log/slog"
	"os"

	"pollux-go/internal/app"
	"pollux-go/internal/config"
)

func main() {
	logger := slog.New(slog.NewJSONHandler(os.Stdout, nil))

	cfg, err := config.Load(os.Environ())
	if err != nil {
		logger.Error("invalid configuration", "err", err.Error())
		os.Exit(1)
	}

	if err := app.Run(cfg, logger); err != nil {
		logger.Error("server exited with error", "err", err.Error())
		os.Exit(1)
	}
}
