---
to: generated/.pollux-go-staging/Makefile
force: true
---
# Code generated by Pollux (go backend). DO NOT EDIT.
.PHONY: build run test vet tidy

build:
	go build ./...

run:
	go run ./cmd/api

test:
	go test ./...

vet:
	go vet ./...

tidy:
	go mod tidy
