---
to: generated/.pollux-go-staging/internal/middleware/request_id_test.go
force: true
---
// Code generated by Pollux (go backend). DO NOT EDIT.
package middleware

import "testing"

func TestNewRequestID(t *testing.T) {
	for _, valid := range []string{
		"0198c1f2-aaaa-bbbb-cccc-1234567890ab",
		"suite-req-id-123",
		"proxy.req_42-A",
	} {
		if NewRequestID(valid) != valid {
			t.Fatalf("valid incoming id %q must be kept", valid)
		}
	}
	for _, bad := range []string{"", "has spaces here!", "<script>alert(1)</script>", "ok\nnewline-injection-attempt", "ção-unicode"} {
		got := NewRequestID(bad)
		if got == bad {
			t.Fatalf("unsafe id %q must be replaced", bad)
		}
		if !requestIDFormat.MatchString(got) {
			t.Fatalf("generated id %q not in safe format", got)
		}
	}
}
