---
to: generated/.pollux-go-staging/internal/middleware/recovery.go
force: true
---
// Code generated by Pollux (go backend). DO NOT EDIT.
package middleware

import (
	"log/slog"
	"net/http"
	"runtime/debug"

	"github.com/gin-gonic/gin"
)

// Recovery returns the same safe internal-error envelope as every other
// failure; the panic value and stack are recorded only in the server log.
func Recovery(logger *slog.Logger) gin.HandlerFunc {
	return func(c *gin.Context) {
		defer func() {
			if recovered := recover(); recovered != nil {
				logger.Error("panic recovered",
					"requestId", RequestID(c),
					"panic", recovered,
					"stack", string(debug.Stack()),
				)
				c.AbortWithStatusJSON(http.StatusInternalServerError, gin.H{
					"ok": false,
					"error": gin.H{
						"code":      "INTERNAL",
						"message":   "Erro inesperado. Tente novamente ou contate o suporte.",
						"requestId": RequestID(c),
						"retryable": false,
					},
				})
			}
		}()
		c.Next()
	}
}
