---
to: generated/.pollux-go-staging/internal/middleware/request_id.go
force: true
---
// Code generated by Pollux (go backend). DO NOT EDIT.
package middleware

import (
	"regexp"

	"github.com/gin-gonic/gin"
	"github.com/google/uuid"
)

const requestIDKey = "pollux.requestId"

// Only this safe format is accepted from the caller; anything else is
// replaced by a generated UUID. The pattern matches the v2 contract's
// sanitization rule ([A-Za-z0-9._-]{1,128}) and is a superset of the
// previous hex-only format, so v1 callers are unaffected.
var requestIDFormat = regexp.MustCompile(`^[A-Za-z0-9._-]{1,128}$`)

func NewRequestID(incoming string) string {
	if requestIDFormat.MatchString(incoming) {
		return incoming
	}
	return uuid.NewString()
}

func RequestIDMiddleware() gin.HandlerFunc {
	return func(c *gin.Context) {
		id := NewRequestID(c.GetHeader("X-Request-Id"))
		c.Set(requestIDKey, id)
		c.Writer.Header().Set("X-Request-Id", id)
		c.Next()
	}
}

func RequestID(c *gin.Context) string {
	return c.GetString(requestIDKey)
}
