---
to: generated/.pollux-go-staging/internal/middleware/timeout.go
force: true
---
// Code generated by Pollux (go backend). DO NOT EDIT.
package middleware

import (
	"context"
	"time"

	"github.com/gin-gonic/gin"
)

// Timeout bounds every request context; downstream queries and auth calls
// all receive the bounded context.
func Timeout(limit time.Duration) gin.HandlerFunc {
	return func(c *gin.Context) {
		ctx, cancel := context.WithTimeout(c.Request.Context(), limit)
		defer cancel()
		c.Request = c.Request.WithContext(ctx)
		c.Next()
	}
}
