---
to: generated/.pollux-go-staging/internal/middleware/access_log.go
force: true
---
// Code generated by Pollux (go backend). DO NOT EDIT.
package middleware

import (
	"log/slog"
	"time"

	"github.com/gin-gonic/gin"
)

const (
	entityKey    = "pollux.entity"
	actionKey    = "pollux.action"
	operationKey = "pollux.operation"
	userIDKey    = "pollux.userId"
	countKey     = "pollux.resultCount"
)

// Annotate lets routes and handlers attach safe, allowlisted log context.
func SetEntityAction(c *gin.Context, entity, action, operation string) {
	c.Set(entityKey, entity)
	c.Set(actionKey, action)
	c.Set(operationKey, operation)
}

func SetUserID(c *gin.Context, userID string)  { c.Set(userIDKey, userID) }
func SetResultCount(c *gin.Context, count int) { c.Set(countKey, count) }

// AccessLog emits one structured event per request. Data minimization: no
// bodies, query values, headers, cookies or SQL — identifiers and counts only.
func AccessLog(logger *slog.Logger) gin.HandlerFunc {
	return func(c *gin.Context) {
		start := time.Now()
		c.Next()

		attrs := []any{
			"scope", "generated-crud",
			"requestId", RequestID(c),
			"method", c.Request.Method,
			"path", c.FullPath(),
			"status", c.Writer.Status(),
			"durationMs", time.Since(start).Milliseconds(),
		}
		if entity := c.GetString(entityKey); entity != "" {
			attrs = append(attrs, "entity", entity)
		}
		if action := c.GetString(actionKey); action != "" {
			attrs = append(attrs, "action", action)
		}
		if operation := c.GetString(operationKey); operation != "" {
			attrs = append(attrs, "operation", operation)
		}
		if userID := c.GetString(userIDKey); userID != "" {
			attrs = append(attrs, "userId", userID)
		}
		if count, ok := c.Get(countKey); ok {
			attrs = append(attrs, "resultCount", count)
		}

		switch {
		case c.Writer.Status() >= 500:
			logger.Error("request completed", attrs...)
		case c.Writer.Status() >= 400:
			logger.Warn("request completed", attrs...)
		default:
			logger.Info("request completed", attrs...)
		}
	}
}
