---
to: generated/.pollux-go-staging/README.md
force: true
---
# Pollux Go backend (generated)

Generated by `./generate-pollux.sh --backend go`. Do not edit by hand —
regenerate from `_templates/pollux/go-service` and `_templates/pollux/go-entity`.

Standalone Gin + Bun + pgx CRUD service implementing the same public result
contract as the TypeScript backend (`{ ok, data } | { ok, error }` with the
stable error taxonomy and Portuguese messages).

## Routes

### v1 (unchanged legacy contract)

All v1 entity routes live below `/api/generated/v1/:entity` and authenticate
with the Better Auth session cookie:

| Operation | Method and path | Permission |
| --- | --- | --- |
| Capabilities | `GET /capabilities` | Authenticated |
| Bounded list | `GET /` | `read` |
| Server page | `POST /page` | `read` |
| Get one | `GET /:id` | `read` |
| Create | `POST /` | `create` |
| Update | `PATCH /:id` | `update` |
| Delete | `DELETE /:id` | `delete` |
| Bulk delete | `POST /bulk-delete` | `delete` |

Plus `/healthz` (process) and `/readyz` (bounded database ping).

### v2 (SPEC-003 standalone contract)

v2 routes live below `/api/generated/v2/:entity`, authenticate with
`Authorization: Bearer <token>` (forwarded verbatim to the TypeScript authz
boundary) and use the flat envelope contract from
`test-fixtures/pollux/api/contract.md`:

| Operation | Method and path | Permission | Notes |
| --- | --- | --- | --- |
| Capabilities | `GET /capabilities` | Authenticated | `{list, read, create, update, delete}` |
| List | `GET /` | `read` | strict `page`/`pageSize`/`sort`/`q`/`f_<field>[__<op>]` query |
| Get one | `GET /:id` | `read` | canonical wire record |
| Create | `POST /` | `create` | `Idempotency-Key` required, 201 |
| Update | `PATCH /:id` | `update` | `Idempotency-Key` required |
| Delete | `DELETE /:id` | `delete` | `Idempotency-Key` required, `{id, deleted: true}` |

Success: `{ok: true, data}`. Errors: flat
`{ok: false, code, message, requestId, retryable, fieldErrors?}`. Every
POST/PATCH/DELETE requires an `Idempotency-Key`; replays return the stored
response with `Idempotency-Replayed: true`; reusing a key with a different
body is `CONFLICT`. The service creates and owns the `pollux_idempotency`
table (created on boot). `If-Match`/`ETag` optimistic concurrency is not
implemented (no version column in the current schema); `STALE_WRITE` stays
reserved.

## Configuration (environment)

| Variable | Default | Notes |
| --- | --- | --- |
| `POLLUX_PORT` | `8080` | |
| `POLLUX_DATABASE_URL` | — | required |
| `POLLUX_AUTH_BASE_URL` | — | required; Better Auth base URL |
| `POLLUX_AUTH_TIMEOUT` | `3s` | |
| `POLLUX_REQUEST_TIMEOUT` | `15s` | |
| `POLLUX_SHUTDOWN_TIMEOUT` | `10s` | |
| `POLLUX_DB_MAX_OPEN_CONNS` | `10` | |
| `POLLUX_DB_MAX_IDLE_CONNS` | `5` | |
| `POLLUX_DB_CONN_MAX_LIFETIME` | `30m` | |
| `POLLUX_DB_CONN_MAX_IDLE_TIME` | `5m` | |
| `POLLUX_MAX_BODY_BYTES` | `1048576` | strict JSON, unknown fields rejected |
| `POLLUX_IDEMPOTENCY_RETENTION` | `24h` | completed idempotency records expire after this window |
| `POLLUX_IDEMPOTENCY_WAIT_BOUND` | `2s` | bounded wait for concurrent in-progress duplicates |
| `POLLUX_IDEMPOTENCY_CLEANUP_INTERVAL` | `1h` | periodic sweep of expired completed records |
| `POLLUX_TRUSTED_PROXIES` | none | trusting all proxies is forbidden |
| `POLLUX_CORS_ALLOWED_ORIGINS` | disabled | explicit allowlist only, no `*` |

Authentication and authorization stay in Better Auth: v1 forwards the
incoming session cookie and v2 forwards the incoming bearer token to
`POLLUX_AUTH_BASE_URL` (`GET /api/auth/get-session`,
`POST /api/rest/authz/has-permission`). Grant precedence is never resolved
in Go; denial fails closed, and an authz outage is retryable
`SERVICE_UNAVAILABLE`.

## Development

```bash
make test   # unit + contract tests (no database required)
make vet
make run
```

Repository integration tests run only when `POLLUX_TEST_DATABASE_URL` is set;
they are excluded from the default unit suite otherwise.
