---
to: generated/.pollux-go-staging/internal/response/result.go
force: true
---
// Code generated by Pollux (go backend). DO NOT EDIT.
package response

import (
	"net/http"

	"github.com/gin-gonic/gin"

	"pollux-go/internal/httperr"
	"pollux-go/internal/middleware"
)

// Envelope mirrors the TypeScript CrudResult contract: HTTP status codes add
// REST semantics, the JSON body keeps the same ok/data | ok/error shape.

type errorBody struct {
	Code        httperr.Code        `json:"code"`
	Message     string              `json:"message"`
	RequestID   string              `json:"requestId"`
	Retryable   bool                `json:"retryable"`
	FieldErrors map[string][]string `json:"fieldErrors,omitempty"`
}

func OK(c *gin.Context, data any) {
	c.JSON(http.StatusOK, gin.H{"ok": true, "data": data})
}

func Created(c *gin.Context, data any) {
	c.JSON(http.StatusCreated, gin.H{"ok": true, "data": data})
}

func Fail(c *gin.Context, err error) {
	e := httperr.Map(err)
	c.AbortWithStatusJSON(e.HTTPStatus(), gin.H{
		"ok": false,
		"error": errorBody{
			Code:        e.Code,
			Message:     e.Message,
			RequestID:   middleware.RequestID(c),
			Retryable:   e.Retryable(),
			FieldErrors: e.FieldErrors,
		},
	})
}
