---
to: generated/.pollux-go-staging/internal/strictjson/strictjson_test.go
force: true
---
// Code generated by Pollux (go backend). DO NOT EDIT.
package strictjson

import (
	"errors"
	"net/http/httptest"
	"strings"
	"testing"

	"pollux-go/internal/httperr"
)

type payload struct {
	Name string `json:"name"`
}

func decode(body string) error {
	r := httptest.NewRequest("POST", "/", strings.NewReader(body))
	var target payload
	return Decode(r, 1024, &target)
}

func expectValidation(t *testing.T, err error, label string) {
	t.Helper()
	var typed *httperr.E
	if !errors.As(err, &typed) || typed.Code != httperr.ValidationFailed {
		t.Fatalf("%s: expected VALIDATION_FAILED, got %v", label, err)
	}
}

func TestDecodeStrict(t *testing.T) {
	if err := decode(`{"name":"ok"}`); err != nil {
		t.Fatalf("valid body rejected: %v", err)
	}
	expectValidation(t, decode(`{"name":"x","unknown":1}`), "unknown field")
	expectValidation(t, decode(`{"name":"x"}{"name":"y"}`), "trailing JSON")
	expectValidation(t, decode(`not json`), "malformed body")
	expectValidation(t, decode(`{"name":"`+strings.Repeat("a", 5000)+`"}`), "oversized body")
}
