---
to: generated/.pollux-go-staging/internal/strictjson/strictjson.go
force: true
---
// Code generated by Pollux (go backend). DO NOT EDIT.
package strictjson

import (
	"encoding/json"
	"errors"
	"io"
	"net/http"

	"pollux-go/internal/httperr"
)

// Decode reads a bounded JSON body strictly: unknown fields are rejected,
// trailing JSON values are rejected, and oversized bodies fail as
// VALIDATION_FAILED rather than being truncated silently.
func Decode(r *http.Request, maxBytes int64, target any) error {
	reader := http.MaxBytesReader(nil, r.Body, maxBytes)
	decoder := json.NewDecoder(reader)
	decoder.DisallowUnknownFields()

	if err := decoder.Decode(target); err != nil {
		var maxErr *http.MaxBytesError
		if errors.As(err, &maxErr) {
			return httperr.New(httperr.ValidationFailed,
				httperr.WithMessage("Corpo da requisição excede o tamanho máximo permitido."),
				httperr.WithCause(err))
		}
		return httperr.New(httperr.ValidationFailed, httperr.WithCause(err))
	}
	// Reject trailing values after the first JSON document.
	if err := decoder.Decode(&struct{}{}); err != io.EOF {
		return httperr.New(httperr.ValidationFailed,
			httperr.WithMessage("Corpo da requisição contém dados após o JSON principal."))
	}
	return nil
}
