---
to: generated/.pollux-go-staging/internal/v2/authz.go
force: true
---
// Code generated by Pollux (go backend). DO NOT EDIT.
package v2

import (
	"context"
	"errors"
	"strings"

	"github.com/gin-gonic/gin"

	"pollux-go/internal/auth"
	"pollux-go/internal/httperr"
	"pollux-go/internal/middleware"
)

// v2 authentication is bearer-based: the standalone BFF adapters send
// Authorization: Bearer <access-token> and the Go service forwards that SAME
// token to the TypeScript authorization boundary
// (POST /api/rest/authz/has-permission). Grant precedence is never
// duplicated in Go; the system fails closed when the boundary is
// unavailable (retryable SERVICE_UNAVAILABLE) and returns FORBIDDEN only on
// an explicit denial.

const (
	actorKey  = "pollux.v2.actorUserId"
	tokenKey  = "pollux.v2.bearerToken"
	bearerHdr = "Authorization"
)

// BearerToken extracts the bearer credential; empty when absent/malformed.
func bearerFrom(c *gin.Context) string {
	value := strings.TrimSpace(c.GetHeader(bearerHdr))
	if len(value) < 7 || !strings.EqualFold(value[:7], "Bearer ") {
		return ""
	}
	return strings.TrimSpace(value[7:])
}

// RequireBearer authenticates the bearer token and checks the exact
// entity/action permission before any handler runs. Entity and action are
// static generated strings — a request can never choose them.
func RequireBearer(client auth.Client, entity, action, operation string) gin.HandlerFunc {
	return func(c *gin.Context) {
		middleware.SetEntityAction(c, entity, action, operation)
		token := bearerFrom(c)
		if token == "" {
			Fail(c, httperr.New(httperr.Unauthenticated))
			return
		}

		session, err := client.SessionBearer(c.Request.Context(), token)
		if err != nil {
			Fail(c, err)
			return
		}
		middleware.SetUserID(c, session.UserID)
		c.Set(actorKey, session.UserID)
		c.Set(tokenKey, token)

		if err := client.RequirePermissionBearer(c.Request.Context(), token, entity, action); err != nil {
			Fail(c, err)
			return
		}
		c.Next()
	}
}

// AuthenticateBearer resolves the session without a permission requirement
// (capabilities endpoint reports effective capabilities, including all-false).
func AuthenticateBearer(client auth.Client, entity string) gin.HandlerFunc {
	return func(c *gin.Context) {
		middleware.SetEntityAction(c, entity, "read", "v2.capabilities")
		token := bearerFrom(c)
		if token == "" {
			Fail(c, httperr.New(httperr.Unauthenticated))
			return
		}
		session, err := client.SessionBearer(c.Request.Context(), token)
		if err != nil {
			Fail(c, err)
			return
		}
		middleware.SetUserID(c, session.UserID)
		c.Set(actorKey, session.UserID)
		c.Set(tokenKey, token)
		c.Next()
	}
}

// Actor returns the authenticated user ID set by the bearer middleware.
func Actor(c *gin.Context) string { return c.GetString(actorKey) }

// Token returns the validated bearer token for downstream authz calls.
func Token(c *gin.Context) string { return c.GetString(tokenKey) }

// Capabilities is the v2 per-operation capability payload
// ({list, read, create, update, delete}).
type Capabilities struct {
	List   bool `json:"list"`
	Read   bool `json:"read"`
	Create bool `json:"create"`
	Update bool `json:"update"`
	Delete bool `json:"delete"`
}

// ResolveCapabilities resolves every operation through the TypeScript authz
// boundary with the caller's own token. Denial maps to false; an
// authentication failure or boundary outage propagates as an error so the
// caller fails closed instead of reporting misleading capabilities.
func ResolveCapabilities(ctx context.Context, client auth.Client, token, entity string) (*Capabilities, error) {
	check := func(action string) (bool, error) {
		err := client.RequirePermissionBearer(ctx, token, entity, action)
		if err == nil {
			return true, nil
		}
		var typed *httperr.E
		if errors.As(err, &typed) && typed.Code == httperr.Forbidden {
			return false, nil
		}
		return false, err
	}

	read, err := check("read")
	if err != nil {
		return nil, err
	}
	create, err := check("create")
	if err != nil {
		return nil, err
	}
	update, err := check("update")
	if err != nil {
		return nil, err
	}
	del, err := check("delete")
	if err != nil {
		return nil, err
	}
	// The list operation authorizes as the "read" action (grant flags map
	// any capability onto read; list has no separate grant flag).
	return &Capabilities{List: read, Read: read, Create: create, Update: update, Delete: del}, nil
}
