---
to: generated/.pollux-go-staging/internal/v2/body.go
force: true
---
// Code generated by Pollux (go backend). DO NOT EDIT.
package v2

import (
	"bytes"
	"encoding/json"
	"errors"
	"io"
	"net/http"

	"pollux-go/internal/httperr"
)

// ReadRawBody reads a bounded request body (raw bytes feed the idempotency
// canonical hash). Oversized bodies are VALIDATION_FAILED, never truncated.
func ReadRawBody(r *http.Request, maxBytes int64) ([]byte, error) {
	reader := http.MaxBytesReader(nil, r.Body, maxBytes)
	raw, err := io.ReadAll(reader)
	if err != nil {
		var maxErr *http.MaxBytesError
		if errors.As(err, &maxErr) {
			return nil, httperr.New(httperr.ValidationFailed,
				httperr.WithMessage("Corpo da requisição excede o tamanho máximo permitido."),
				httperr.WithCause(err))
		}
		return nil, httperr.New(httperr.ValidationFailed, httperr.WithCause(err))
	}
	return raw, nil
}

// ParseJSONObject decodes strict flat JSON: exactly one top-level object,
// no trailing content. Field-level strictness (unknown_field/not_writable)
// happens in the generated per-entity parsers.
func ParseJSONObject(raw []byte) (map[string]json.RawMessage, error) {
	decoder := json.NewDecoder(bytes.NewReader(raw))
	var object map[string]json.RawMessage
	if err := decoder.Decode(&object); err != nil {
		return nil, httperr.New(httperr.ValidationFailed,
			httperr.WithMessage("Corpo da requisição deve ser um objeto JSON."),
			httperr.WithCause(err))
	}
	if object == nil {
		return nil, httperr.New(httperr.ValidationFailed,
			httperr.WithMessage("Corpo da requisição deve ser um objeto JSON."))
	}
	if err := decoder.Decode(&struct{}{}); err != io.EOF {
		return nil, httperr.New(httperr.ValidationFailed,
			httperr.WithMessage("Corpo da requisição contém dados após o JSON principal."))
	}
	return object, nil
}
