---
to: generated/.pollux-go-staging/internal/v2/query_test.go
force: true
---
// Code generated by Pollux (go backend). DO NOT EDIT.
package v2

import (
	"errors"
	"testing"

	"pollux-go/internal/httperr"
)

func spec() ListSpec {
	return ListSpec{
		Sortable: map[string]bool{"titulo": true, "preco": true},
		FilterOps: map[string]map[string]bool{
			"titulo": {"contains": true, "eq": true},
			"preco":  {"eq": true, "gt": true, "gte": true, "lt": true, "lte": true},
			"ativo":  {"eq": true},
		},
		FilterDefaultOp: map[string]string{"titulo": "contains", "preco": "eq", "ativo": "eq"},
		DefaultPageSize: 10,
		DefaultSort:     []SortItem{{ID: "titulo", Desc: false}},
	}
}

func expectValidation(t *testing.T, err error, label string) {
	t.Helper()
	var typed *httperr.E
	if !errors.As(err, &typed) || typed.Code != httperr.ValidationFailed {
		t.Fatalf("%s: expected VALIDATION_FAILED, got %v", label, err)
	}
}

func TestParseListQueryDefaults(t *testing.T) {
	q, err := ParseListQuery(map[string][]string{}, spec())
	if err != nil {
		t.Fatalf("defaults: %v", err)
	}
	if q.Page != 1 || q.PageSize != 10 {
		t.Fatalf("defaults wrong: %+v", q)
	}
	if len(q.Sort) != 1 || q.Sort[0].ID != "titulo" {
		t.Fatalf("default sort wrong: %+v", q.Sort)
	}
}

func TestParseListQueryBounds(t *testing.T) {
	cases := map[string]map[string][]string{
		"page zero":          {"page": {"0"}},
		"page negative":      {"page": {"-2"}},
		"page not a number":  {"page": {"abc"}},
		"pageSize zero":      {"pageSize": {"0"}},
		"pageSize above max": {"pageSize": {"9999"}},
		"unknown key":        {"bogus": {"1"}},
		"undeclared filter":  {"f_naoExiste": {"1"}},
		"repeated key":       {"page": {"1", "2"}},
	}
	for label, raw := range cases {
		_, err := ParseListQuery(raw, spec())
		expectValidation(t, err, label)
	}

	q, err := ParseListQuery(map[string][]string{"page": {"3"}, "pageSize": {"500"}}, spec())
	if err != nil || q.Page != 3 || q.PageSize != 500 {
		t.Fatalf("bounds accept in-range values: %+v %v", q, err)
	}
}

func TestParseListQuerySort(t *testing.T) {
	q, err := ParseListQuery(map[string][]string{
		"sort": {`[{"id":"preco","desc":true},{"id":"titulo","desc":false}]`},
	}, spec())
	if err != nil {
		t.Fatalf("sort: %v", err)
	}
	if len(q.Sort) != 2 || q.Sort[0].ID != "preco" || !q.Sort[0].Desc {
		t.Fatalf("sort parsed wrong: %+v", q.Sort)
	}

	for label, value := range map[string]string{
		"malformed":   `not-json`,
		"unknown id":  `[{"id":"naoExiste","desc":false}]`,
		"unsortable":  `[{"id":"ativo","desc":false}]`,
		"duplicate":   `[{"id":"titulo"},{"id":"titulo","desc":true}]`,
		"extra field": `[{"id":"titulo","desc":false,"nulls":"first"}]`,
	} {
		_, err := ParseListQuery(map[string][]string{"sort": {value}}, spec())
		expectValidation(t, err, "sort "+label)
	}
}

func TestParseListQueryFilters(t *testing.T) {
	q, err := ParseListQuery(map[string][]string{
		"f_titulo":      {"ção"},
		"f_preco__gte":  {"100"},
		"f_ativo":       {"true"},
		"q":             {"busca"},
	}, spec())
	if err != nil {
		t.Fatalf("filters: %v", err)
	}
	if len(q.Filters) != 3 || q.Q != "busca" {
		t.Fatalf("filters parsed wrong: %+v", q)
	}
	ops := map[string]string{}
	for _, f := range q.Filters {
		ops[f.Field] = f.Op
	}
	if ops["titulo"] != "contains" || ops["preco"] != "gte" || ops["ativo"] != "eq" {
		t.Fatalf("operators wrong: %+v", ops)
	}

	// Operator not allowed for the scalar.
	_, err = ParseListQuery(map[string][]string{"f_ativo__contains": {"x"}}, spec())
	expectValidation(t, err, "operator not allowed")
	_, err = ParseListQuery(map[string][]string{"f_titulo__gt": {"x"}}, spec())
	expectValidation(t, err, "gt on string")
}
