---
to: generated/.pollux-go-staging/internal/v2/query.go
force: true
---
// Code generated by Pollux (go backend). DO NOT EDIT.
package v2

import (
	"encoding/json"
	"fmt"
	"strconv"
	"strings"

	"pollux-go/internal/httperr"
)

// Strict list-query parsing for the v2 contract: any query key outside
// {page, pageSize, sort, q} plus the entity's declared f_<field>[__<op>]
// filters is VALIDATION_FAILED. Bounds are fixed by the contract:
// page >= 1, pageSize in [1, 500].

const (
	MaxPageSize = 500
	maxSortLen  = 5
	maxValueLen = 500
)

// SortItem mirrors the contract's sort JSON: [{"id": string, "desc": bool}].
type SortItem struct {
	ID   string `json:"id"`
	Desc bool   `json:"desc"`
}

// Filter is one declared filter with a validated operator.
type Filter struct {
	Field string // codeName, allowlisted
	Op    string // eq | contains | gt | gte | lt | lte, allowlisted per scalar
	Value string // raw value; typed parsing happens at the entity layer
}

// ListQuery is the parsed, validated list request.
type ListQuery struct {
	Page     int
	PageSize int
	Sort     []SortItem
	Q        string
	Filters  []Filter
}

// ListSpec is the generated per-entity declaration the parser validates
// against. All keys are codeNames; request values never become identifiers.
type ListSpec struct {
	Sortable        map[string]bool
	FilterOps       map[string]map[string]bool // field -> allowed operators
	FilterDefaultOp map[string]string          // field -> default operator
	DefaultPageSize int
	DefaultSort     []SortItem
}

func validationError(field, message string) error {
	return httperr.New(httperr.ValidationFailed,
		httperr.WithFieldErrors(map[string][]string{field: {message}}))
}

// ParseListQuery validates raw query values (url.Values-shaped) against the
// spec. Unknown keys, repeated keys, out-of-bounds pages, malformed sort
// JSON and undeclared filters/operators are all VALIDATION_FAILED.
func ParseListQuery(raw map[string][]string, spec ListSpec) (*ListQuery, error) {
	out := &ListQuery{
		Page:     1,
		PageSize: spec.DefaultPageSize,
		Sort:     spec.DefaultSort,
	}
	if out.PageSize <= 0 {
		out.PageSize = 10
	}

	for key, values := range raw {
		if len(values) != 1 {
			return nil, validationError(key, "Parâmetro repetido")
		}
		value := values[0]
		if len(value) > maxValueLen {
			return nil, validationError(key, "Valor excede o tamanho máximo")
		}
		switch key {
		case "page":
			parsed, err := strconv.Atoi(value)
			if err != nil || parsed < 1 {
				return nil, validationError("page", "Página inválida")
			}
			out.Page = parsed
		case "pageSize":
			parsed, err := strconv.Atoi(value)
			if err != nil || parsed < 1 || parsed > MaxPageSize {
				return nil, validationError("pageSize",
					fmt.Sprintf("Tamanho de página fora do intervalo [1, %d]", MaxPageSize))
			}
			out.PageSize = parsed
		case "sort":
			sort, err := parseSort(value, spec.Sortable)
			if err != nil {
				return nil, err
			}
			out.Sort = sort
		case "q":
			out.Q = value
		default:
			filter, err := parseFilterKey(key, value, spec)
			if err != nil {
				return nil, err
			}
			out.Filters = append(out.Filters, *filter)
		}
	}
	return out, nil
}

func parseSort(value string, sortable map[string]bool) ([]SortItem, error) {
	var items []SortItem
	decoder := json.NewDecoder(strings.NewReader(value))
	decoder.DisallowUnknownFields()
	if err := decoder.Decode(&items); err != nil {
		return nil, validationError("sort", "Ordenação inválida: JSON malformado")
	}
	if decoder.More() {
		return nil, validationError("sort", "Ordenação inválida: conteúdo extra")
	}
	if len(items) > maxSortLen {
		return nil, validationError("sort", "Ordenação excede o número máximo de campos")
	}
	seen := map[string]bool{}
	for _, item := range items {
		if !sortable[item.ID] {
			return nil, validationError("sort",
				fmt.Sprintf("Campo de ordenação inválido: %s", item.ID))
		}
		if seen[item.ID] {
			return nil, validationError("sort", "Campos de ordenação duplicados")
		}
		seen[item.ID] = true
	}
	return items, nil
}

// parseFilterKey accepts f_<codeName> (declared default operator) or
// f_<codeName>__<op> where <op> is allowed for that field's scalar.
func parseFilterKey(key, value string, spec ListSpec) (*Filter, error) {
	if !strings.HasPrefix(key, "f_") {
		return nil, validationError(key, "Parâmetro de consulta desconhecido")
	}
	rest := strings.TrimPrefix(key, "f_")
	field := rest
	op := ""
	if idx := strings.LastIndex(rest, "__"); idx >= 0 {
		field = rest[:idx]
		op = rest[idx+2:]
	}
	ops, declared := spec.FilterOps[field]
	if !declared {
		return nil, validationError(key, "Filtro não declarado")
	}
	if op == "" {
		op = spec.FilterDefaultOp[field]
	}
	if !ops[op] {
		return nil, validationError(key, "Operador de filtro não permitido")
	}
	return &Filter{Field: field, Op: op, Value: value}, nil
}
