---
to: generated/.pollux-go-staging/internal/v2/respond.go
force: true
---
// Code generated by Pollux (go backend). DO NOT EDIT.
package v2

import (
	"encoding/json"

	"github.com/gin-gonic/gin"

	"pollux-go/internal/httperr"
	"pollux-go/internal/middleware"
)

// The v2 standalone contract (test-fixtures/pollux/api/contract.md) uses a
// FLAT error envelope — {ok, code, message, requestId, retryable,
// fieldErrors?} — distinct from the nested v1 {ok, error:{...}} shape. The
// two shapes never mix: v1 keeps internal/response, v2 uses this package.

type errorEnvelope struct {
	OK          bool                `json:"ok"`
	Code        httperr.Code        `json:"code"`
	Message     string              `json:"message"`
	RequestID   string              `json:"requestId"`
	Retryable   bool                `json:"retryable"`
	FieldErrors map[string][]string `json:"fieldErrors,omitempty"`
}

type successEnvelope struct {
	OK   bool `json:"ok"`
	Data any  `json:"data"`
}

// Envelope marshals the exact success body bytes; mutations store these
// bytes verbatim in the idempotency record so replays are byte-identical.
func Envelope(data any) ([]byte, error) {
	return json.Marshal(successEnvelope{OK: true, Data: data})
}

const jsonContentType = "application/json; charset=utf-8"

// Write emits previously marshalled success bytes with the given status.
func Write(c *gin.Context, status int, body []byte) {
	c.Data(status, jsonContentType, body)
}

// OK marshals and writes a success envelope.
func OK(c *gin.Context, status int, data any) {
	body, err := Envelope(data)
	if err != nil {
		Fail(c, httperr.New(httperr.Internal, httperr.WithCause(err)))
		return
	}
	Write(c, status, body)
}

// Fail classifies err through the shared taxonomy and writes the flat v2
// error envelope. No cause detail ever reaches the response.
func Fail(c *gin.Context, err error) {
	e := httperr.Map(err)
	c.AbortWithStatusJSON(e.HTTPStatus(), errorEnvelope{
		OK:          false,
		Code:        e.Code,
		Message:     e.Message,
		RequestID:   middleware.RequestID(c),
		Retryable:   e.Retryable(),
		FieldErrors: e.FieldErrors,
	})
}

// NotFoundEntity is mounted as the engine's NoRoute fallback for unknown
// /api/generated/v2/* paths (unknown entity codes are NOT_FOUND per the
// contract). v1 and non-API paths keep Gin's default empty 404.
func NotFoundEntity(c *gin.Context) {
	Fail(c, httperr.New(httperr.NotFound))
}
