---
to: generated/.pollux-go-staging/internal/entity/<%= h.changeCase.camel(name) %>/handler.go
force: true
---
// Code generated by Pollux (go backend). DO NOT EDIT.
package <%= h.changeCase.camel(name) %>

import (
	"github.com/gin-gonic/gin"

	"pollux-go/internal/auth"
	"pollux-go/internal/authz"
	"pollux-go/internal/middleware"
	"pollux-go/internal/response"
	"pollux-go/internal/strictjson"
)

// Handler owns HTTP translation only; the service owns business rules and
// transactions. Authorization runs in route middleware before any handler.
type Handler struct {
	service      *Service
	auth         auth.Client
	maxBodyBytes int64
}

func NewHandler(service *Service, client auth.Client, maxBodyBytes int64) *Handler {
	return &Handler{service: service, auth: client, maxBodyBytes: maxBodyBytes}
}

func (h *Handler) Capabilities(c *gin.Context) {
	caps := h.auth.Capabilities(c.Request.Context(), c.GetHeader("Cookie"), Entity)
	response.OK(c, caps)
}

func (h *Handler) List(c *gin.Context) {
	rows, err := h.service.List(c.Request.Context())
	if err != nil {
		response.Fail(c, err)
		return
	}
	middleware.SetResultCount(c, len(rows))
	response.OK(c, rows)
}

func (h *Handler) Page(c *gin.Context) {
	var input PageInput
	if err := strictjson.Decode(c.Request, h.maxBodyBytes, &input); err != nil {
		response.Fail(c, err)
		return
	}
	if err := input.Validate(); err != nil {
		response.Fail(c, err)
		return
	}
	result, err := h.service.Page(c.Request.Context(), &input)
	if err != nil {
		response.Fail(c, err)
		return
	}
	middleware.SetResultCount(c, len(result.Rows))
	response.OK(c, result)
}

func (h *Handler) Get(c *gin.Context) {
	id := c.Param("id")
	if err := ValidateID(id); err != nil {
		response.Fail(c, err)
		return
	}
	row, err := h.service.Get(c.Request.Context(), id)
	if err != nil {
		response.Fail(c, err)
		return
	}
	response.OK(c, row)
}

func (h *Handler) Create(c *gin.Context) {
	var input CreateInput
	if err := strictjson.Decode(c.Request, h.maxBodyBytes, &input); err != nil {
		response.Fail(c, err)
		return
	}
	if fieldErrors := input.Validate(); fieldErrors != nil {
		response.Fail(c, newValidationError(fieldErrors))
		return
	}
	row, err := h.service.Create(c.Request.Context(), authz.Actor(c), middleware.RequestID(c), &input)
	if err != nil {
		response.Fail(c, err)
		return
	}
	response.Created(c, row)
}

func (h *Handler) Update(c *gin.Context) {
	id := c.Param("id")
	if err := ValidateID(id); err != nil {
		response.Fail(c, err)
		return
	}
	var body UpdateBody
	if err := strictjson.Decode(c.Request, h.maxBodyBytes, &body); err != nil {
		response.Fail(c, err)
		return
	}
	expected, err := body.ParseExpected()
	if err != nil {
		response.Fail(c, err)
		return
	}
	patch, changed, fieldErrors := body.ParsePatch()
	if fieldErrors != nil {
		response.Fail(c, newValidationError(fieldErrors))
		return
	}
	row, err := h.service.Update(c.Request.Context(), authz.Actor(c), middleware.RequestID(c), id, expected, patch, changed)
	if err != nil {
		response.Fail(c, err)
		return
	}
	response.OK(c, row)
}

func (h *Handler) Delete(c *gin.Context) {
	id := c.Param("id")
	if err := ValidateID(id); err != nil {
		response.Fail(c, err)
		return
	}
	result, err := h.service.Delete(c.Request.Context(), authz.Actor(c), middleware.RequestID(c), id)
	if err != nil {
		response.Fail(c, err)
		return
	}
	response.OK(c, result)
}

func (h *Handler) BulkDelete(c *gin.Context) {
	var input BulkDeleteInput
	if err := strictjson.Decode(c.Request, h.maxBodyBytes, &input); err != nil {
		response.Fail(c, err)
		return
	}
	if err := input.Validate(); err != nil {
		response.Fail(c, err)
		return
	}
	result, err := h.service.BulkDelete(c.Request.Context(), authz.Actor(c), middleware.RequestID(c), input.IDs)
	if err != nil {
		response.Fail(c, err)
		return
	}
	response.OK(c, result)
}
