---
to: generated/.pollux-go-staging/internal/entity/<%= h.changeCase.camel(name) %>/handler_v2_test.go
force: true
---
<%
let fields = (data && data.attributes ? data.attributes : []).map(function (f) {
  return { ...f, camel: h.camelField(f.name.trim()) };
});
const hasCreatedAt = fields.some(function (f) { return f.camel === 'createdAt'; });
-%>
// Code generated by Pollux (go backend). DO NOT EDIT.
package <%= h.changeCase.camel(name) %>

import (
	"encoding/json"
	"net/http"
	"net/http/httptest"
	"strings"
	"testing"

	"github.com/gin-gonic/gin"

	"pollux-go/internal/httperr"
)

// v2 contract tests (test-fixtures/pollux/api/contract.md). The database is
// nil on purpose: every request below must be rejected before any
// repository or idempotency code runs, proving authorization, strict query
// parsing and validation precede database access.

const v2Base = "/api/generated/v2/<%= h.changeCase.camel(name) %>"

// v2Envelope is the FLAT v2 error envelope — code/message/requestId/
// retryable at the top level, unlike v1's nested error object.
type v2Envelope struct {
	OK          bool                `json:"ok"`
	Code        string              `json:"code"`
	Message     string              `json:"message"`
	RequestID   string              `json:"requestId"`
	Retryable   *bool               `json:"retryable"`
	FieldErrors map[string][]string `json:"fieldErrors"`
	Data        json.RawMessage     `json:"data"`
}

func performV2(t *testing.T, router *gin.Engine, method, path, body string, headers map[string]string) (int, v2Envelope, http.Header) {
	t.Helper()
	req := httptest.NewRequest(method, path, strings.NewReader(body))
	if body != "" {
		req.Header.Set("Content-Type", "application/json")
	}
	for key, value := range headers {
		req.Header.Set(key, value)
	}
	recorder := httptest.NewRecorder()
	router.ServeHTTP(recorder, req)

	var parsed v2Envelope
	if err := json.Unmarshal(recorder.Body.Bytes(), &parsed); err != nil {
		t.Fatalf("%s %s: invalid v2 envelope %q", method, path, recorder.Body.String())
	}
	return recorder.Code, parsed, recorder.Result().Header
}

func expectV2Error(t *testing.T, label string, status int, body v2Envelope, wantStatus int, wantCode string) {
	t.Helper()
	if status != wantStatus || body.OK || body.Code != wantCode {
		t.Fatalf("%s: expected %d %s, got %d %+v", label, wantStatus, wantCode, status, body)
	}
	if body.Message == "" || body.RequestID == "" || body.Retryable == nil {
		t.Fatalf("%s: flat envelope must carry message/requestId/retryable: %+v", label, body)
	}
	wantRetryable := wantCode == "RATE_LIMITED" || wantCode == "SERVICE_UNAVAILABLE"
	if *body.Retryable != wantRetryable {
		t.Fatalf("%s: retryable flag must match taxonomy: %+v", label, body)
	}
}

var v2Operations = []struct {
	method string
	path   string
	body   string
}{
	{http.MethodGet, v2Base, ""},
	{http.MethodGet, v2Base + "/some-id", ""},
	{http.MethodPost, v2Base, `{}`},
	{http.MethodPatch, v2Base + "/some-id", `{}`},
	{http.MethodDelete, v2Base + "/some-id", ""},
}

func TestV2EveryOperationRejectsMissingBearer(t *testing.T) {
	router := newTestRouter(&fakeAuth{})
	for _, op := range v2Operations {
		status, body, _ := performV2(t, router, op.method, op.path, op.body, nil)
		expectV2Error(t, op.method+" "+op.path+" (no token)", status, body,
			http.StatusUnauthorized, "UNAUTHENTICATED")
	}
	// Capabilities also requires authentication.
	status, body, _ := performV2(t, router, http.MethodGet, v2Base+"/capabilities", "", nil)
	expectV2Error(t, "capabilities (no token)", status, body,
		http.StatusUnauthorized, "UNAUTHENTICATED")
}

func TestV2EveryOperationRejectsInvalidSession(t *testing.T) {
	router := newTestRouter(&fakeAuth{sessionErr: httperr.New(httperr.Unauthenticated)})
	headers := map[string]string{"Authorization": "Bearer not-a-real-token"}
	for _, op := range v2Operations {
		status, body, _ := performV2(t, router, op.method, op.path, op.body, headers)
		expectV2Error(t, op.method+" "+op.path, status, body,
			http.StatusUnauthorized, "UNAUTHENTICATED")
	}
}

func TestV2EveryOperationRejectsForbidden(t *testing.T) {
	router := newTestRouter(&fakeAuth{permErr: httperr.New(httperr.Forbidden)})
	headers := map[string]string{"Authorization": "Bearer token"}
	for _, op := range v2Operations {
		status, body, _ := performV2(t, router, op.method, op.path, op.body, headers)
		expectV2Error(t, op.method+" "+op.path, status, body,
			http.StatusForbidden, "FORBIDDEN")
	}
}

func TestV2AuthzOutageFailsClosedRetryable(t *testing.T) {
	router := newTestRouter(&fakeAuth{permErr: httperr.New(httperr.ServiceUnavailable)})
	headers := map[string]string{"Authorization": "Bearer token"}
	status, body, _ := performV2(t, router, http.MethodGet, v2Base, "", headers)
	expectV2Error(t, "authz outage", status, body,
		http.StatusServiceUnavailable, "SERVICE_UNAVAILABLE")
}

func TestV2CapabilitiesFailClosedOnAuthzOutage(t *testing.T) {
	// Capabilities never guesses: a boundary outage is a retryable error,
	// not an all-true or silently-empty capability set.
	router := newTestRouter(&fakeAuth{permErr: httperr.New(httperr.ServiceUnavailable)})
	headers := map[string]string{"Authorization": "Bearer token"}
	status, body, _ := performV2(t, router, http.MethodGet, v2Base+"/capabilities", "", headers)
	expectV2Error(t, "capabilities outage", status, body,
		http.StatusServiceUnavailable, "SERVICE_UNAVAILABLE")
}

func TestV2CapabilitiesReportsDenialsAsFalse(t *testing.T) {
	router := newTestRouter(&fakeAuth{permErr: httperr.New(httperr.Forbidden)})
	headers := map[string]string{"Authorization": "Bearer token"}
	status, body, _ := performV2(t, router, http.MethodGet, v2Base+"/capabilities", "", headers)
	if status != http.StatusOK || !body.OK {
		t.Fatalf("capabilities with denials: expected 200 ok, got %d %+v", status, body)
	}
	var caps map[string]bool
	if err := json.Unmarshal(body.Data, &caps); err != nil {
		t.Fatalf("capabilities payload: %v", err)
	}
	for _, op := range []string{"list", "read", "create", "update", "delete"} {
		value, present := caps[op]
		if !present || value {
			t.Fatalf("capability %s must be reported false on denial: %+v", op, caps)
		}
	}
}

// Strict query, idempotency-key and body validation must all reject before
// the nil database is touched; a panic means data access ran first.
func TestV2ValidationPrecedesDatabase(t *testing.T) {
	router := newTestRouter(&fakeAuth{})
	auth := map[string]string{"Authorization": "Bearer token"}
	withKey := map[string]string{"Authorization": "Bearer token", "Idempotency-Key": "key-1"}

	cases := []struct {
		label   string
		method  string
		path    string
		body    string
		headers map[string]string
	}{
		{"unknown query key", http.MethodGet, v2Base + "?bogus=1", "", auth},
		{"undeclared filter", http.MethodGet, v2Base + "?f_naoExiste=1", "", auth},
		{"page zero", http.MethodGet, v2Base + "?page=0", "", auth},
		{"pageSize zero", http.MethodGet, v2Base + "?pageSize=0", "", auth},
		{"pageSize above bound", http.MethodGet, v2Base + "?pageSize=9999", "", auth},
		{"malformed sort", http.MethodGet, v2Base + "?sort=not-json", "", auth},
		{"unknown sort id", http.MethodGet, v2Base + "?sort=%5B%7B%22id%22%3A%22naoExiste%22%7D%5D", "", auth},
		{"missing Idempotency-Key on create", http.MethodPost, v2Base, `{}`, auth},
		{"missing Idempotency-Key on update", http.MethodPatch, v2Base + "/some-id", `{}`, auth},
		{"missing Idempotency-Key on delete", http.MethodDelete, v2Base + "/some-id", "", auth},
		{"oversized Idempotency-Key", http.MethodPost, v2Base, `{}`,
			map[string]string{"Authorization": "Bearer token", "Idempotency-Key": strings.Repeat("k", 201)}},
		{"non-object body", http.MethodPost, v2Base, `[1,2,3]`, withKey},
		{"malformed json body", http.MethodPost, v2Base, `{not json`, withKey},
		{"trailing content", http.MethodPost, v2Base, `{} {}`, withKey},
		{"oversized id", http.MethodPatch, v2Base + "/" + strings.Repeat("x", 200), `{}`, withKey},
	}
	for _, tc := range cases {
		status, body, _ := performV2(t, router, tc.method, tc.path, tc.body, tc.headers)
		expectV2Error(t, tc.label, status, body, http.StatusBadRequest, "VALIDATION_FAILED")
	}
}

func TestV2UnknownFieldRejectedWithFieldErrors(t *testing.T) {
	router := newTestRouter(&fakeAuth{})
	headers := map[string]string{"Authorization": "Bearer token", "Idempotency-Key": "key-2"}

	status, body, _ := performV2(t, router, http.MethodPost, v2Base,
		`{"campoInexistenteV2":1}`, headers)
	expectV2Error(t, "create unknown field", status, body, http.StatusBadRequest, "VALIDATION_FAILED")
	if len(body.FieldErrors["campoInexistenteV2"]) == 0 ||
		body.FieldErrors["campoInexistenteV2"][0] != "unknown_field" {
		t.Fatalf("unknown field must map to fieldErrors[...]=[unknown_field]: %+v", body.FieldErrors)
	}

	status, body, _ = performV2(t, router, http.MethodPatch, v2Base+"/some-id",
		`{"campoInexistenteV2":1}`, headers)
	expectV2Error(t, "update unknown field", status, body, http.StatusBadRequest, "VALIDATION_FAILED")
	if len(body.FieldErrors["campoInexistenteV2"]) == 0 {
		t.Fatalf("update unknown field must map to fieldErrors: %+v", body.FieldErrors)
	}
}

<% if (hasCreatedAt) { -%>
func TestV2ServerManagedFieldsNotWritable(t *testing.T) {
	router := newTestRouter(&fakeAuth{})
	headers := map[string]string{"Authorization": "Bearer token", "Idempotency-Key": "key-3"}
	status, body, _ := performV2(t, router, http.MethodPost, v2Base,
		`{"createdAt":"2020-01-01T00:00:00.000Z"}`, headers)
	expectV2Error(t, "server-managed field", status, body, http.StatusBadRequest, "VALIDATION_FAILED")
	if len(body.FieldErrors["createdAt"]) == 0 || body.FieldErrors["createdAt"][0] != "not_writable" {
		t.Fatalf("known non-writable field must map to not_writable: %+v", body.FieldErrors)
	}
}

<% } -%>

func TestV2RequestIDEchoedInEnvelope(t *testing.T) {
	router := newTestRouter(&fakeAuth{})
	supplied := "suite-req-id-123"
	status, body, headers := performV2(t, router, http.MethodGet, v2Base, "",
		map[string]string{"X-Request-Id": supplied})
	expectV2Error(t, "request id echo", status, body, http.StatusUnauthorized, "UNAUTHENTICATED")
	if body.RequestID != supplied {
		t.Fatalf("error envelope must echo the request id: %+v", body)
	}
	if headers.Get("X-Request-Id") != supplied {
		t.Fatalf("response header must echo the request id: %q", headers.Get("X-Request-Id"))
	}
}

func TestV2UnknownEntityIsNotFound(t *testing.T) {
	// NoRoute-level behavior is wired in app.NewEngine; at the entity level
	// an unknown sub-path under this entity must also be NOT_FOUND-safe.
	router := newTestRouter(&fakeAuth{})
	req := httptest.NewRequest(http.MethodGet, "/api/generated/v2/naoExisteEntidade", nil)
	req.Header.Set("Authorization", "Bearer token")
	recorder := httptest.NewRecorder()
	router.ServeHTTP(recorder, req)
	if recorder.Code != http.StatusNotFound {
		t.Fatalf("unknown entity must be 404, got %d", recorder.Code)
	}
}
