---
to: generated/.pollux-go-staging/internal/entity/<%= h.changeCase.camel(name) %>/handler_v2.go
force: true
---
<%
const SYSTEM = ['id','createdAt','createdById','updatedAt','updatedById','deletedAt'];
let fields = (data && data.attributes ? data.attributes : []).map(function (f) {
  return { ...f, camel: h.camelField(f.name.trim()), column: f.name.trim(), dataType: (f.dataType || 'text').trim().toLowerCase() };
});
const hasUpdatedAt = fields.some(function (f) { return f.camel === 'updatedAt'; });
const hasUpdatedById = fields.some(function (f) { return f.camel === 'updatedById'; });
-%>
// Code generated by Pollux (go backend). DO NOT EDIT.
package <%= h.changeCase.camel(name) %>

import (
	"context"
	"net/http"
<% if (hasUpdatedAt) { -%>
	"time"
<% } -%>

	"github.com/gin-gonic/gin"
	"github.com/uptrace/bun"

	"pollux-go/internal/audit"
	"pollux-go/internal/auth"
	"pollux-go/internal/httperr"
	"pollux-go/internal/idempotency"
	"pollux-go/internal/middleware"
	v2 "pollux-go/internal/v2"
)

// HandlerV2 serves the standalone /api/generated/v2 contract for this
// entity. It shares the repository and audit trail with v1 but has its own
// DTOs, envelopes and idempotent mutation path; v1 behavior is untouched.
type HandlerV2 struct {
	db           *bun.DB
	repo         Repository
	auth         auth.Client
	store        *idempotency.Store
	maxBodyBytes int64
}

func NewHandlerV2(db *bun.DB, client auth.Client, maxBodyBytes int64) *HandlerV2 {
	return &HandlerV2{db: db, auth: client, store: idempotency.NewStore(db), maxBodyBytes: maxBodyBytes}
}

const v2BasePath = "/api/generated/v2/" + Entity

// v2ListPayload is the contract list envelope payload.
type v2ListPayload struct {
	Rows         []map[string]any `json:"rows"`
	TotalRows    int              `json:"totalRows"`
	Page         int              `json:"page"`
	PageSize     int              `json:"pageSize"`
	Capabilities *v2.Capabilities `json:"capabilities"`
}

// v2DeletePayload is the contract deletion confirmation.
type v2DeletePayload struct {
	ID      string `json:"id"`
	Deleted bool   `json:"deleted"`
}

func (h *HandlerV2) capabilities(c *gin.Context) (*v2.Capabilities, error) {
	return v2.ResolveCapabilities(c.Request.Context(), h.auth, v2.Token(c), Entity)
}

func (h *HandlerV2) Capabilities(c *gin.Context) {
	caps, err := h.capabilities(c)
	if err != nil {
		v2.Fail(c, err)
		return
	}
	v2.OK(c, http.StatusOK, caps)
}

func (h *HandlerV2) List(c *gin.Context) {
	query, err := v2.ParseListQuery(c.Request.URL.Query(), v2ListSpec)
	if err != nil {
		v2.Fail(c, err)
		return
	}
	rows, total, err := h.repo.V2Page(c.Request.Context(), h.db, query)
	if err != nil {
		v2.Fail(c, err)
		return
	}
	caps, err := h.capabilities(c)
	if err != nil {
		v2.Fail(c, err)
		return
	}
	middleware.SetResultCount(c, len(rows))
	v2.OK(c, http.StatusOK, &v2ListPayload{
		Rows:         v2WireRows(rows),
		TotalRows:    total,
		Page:         query.Page,
		PageSize:     query.PageSize,
		Capabilities: caps,
	})
}

func (h *HandlerV2) Get(c *gin.Context) {
	id := c.Param("id")
	if err := ValidateID(id); err != nil {
		v2.Fail(c, err)
		return
	}
	row, err := h.repo.Get(c.Request.Context(), h.db, id)
	if err != nil {
		v2.Fail(c, err)
		return
	}
	v2.OK(c, http.StatusOK, v2WireRecord(row))
}

// mutationScope builds the idempotency scope. Interim client identity: the
// bearer subject (actor id) stands in for the authorized-party client id
// until the SPEC-003 PKCE token service ships (the azp claim lands here).
func (h *HandlerV2) mutationScope(c *gin.Context, method, path, key string) idempotency.Scope {
	actor := v2.Actor(c)
	return idempotency.Scope{
		ActorID:  actor,
		ClientID: actor,
		Method:   method,
		Path:     path,
		Key:      key,
	}
}

func writeOutcome(c *gin.Context, outcome *idempotency.Outcome) {
	if outcome.Replayed {
		c.Header("Idempotency-Replayed", "true")
	}
	v2.Write(c, outcome.Status, outcome.Body)
}

func (h *HandlerV2) Create(c *gin.Context) {
	key := c.GetHeader("Idempotency-Key")
	if err := idempotency.ValidateKey(key); err != nil {
		v2.Fail(c, err)
		return
	}
	raw, err := v2.ReadRawBody(c.Request, h.maxBodyBytes)
	if err != nil {
		v2.Fail(c, err)
		return
	}
	object, err := v2.ParseJSONObject(raw)
	if err != nil {
		v2.Fail(c, err)
		return
	}
	input, fieldErrors := v2ParseCreate(object)
	if fieldErrors != nil {
		v2.Fail(c, newValidationError(fieldErrors))
		return
	}
	hash, err := idempotency.BodyHash(raw)
	if err != nil {
		v2.Fail(c, err)
		return
	}

	actor := v2.Actor(c)
	requestID := middleware.RequestID(c)
	scope := h.mutationScope(c, http.MethodPost, v2BasePath, key)
	outcome, err := h.store.Execute(c.Request.Context(), scope, hash,
		func(ctx context.Context, tx bun.Tx) (int, []byte, error) {
			model := buildModel(input, actor)
			if err := h.repo.Insert(ctx, tx, model); err != nil {
				return 0, nil, err
			}
			recordID := model.PrimaryKey()
			if err := audit.Insert(ctx, tx, audit.Event{
				RequestID:     requestID,
				ActorUserID:   actor,
				Entity:        Entity,
				Operation:     "create",
				RecordID:      &recordID,
				ChangedFields: input.ChangedFields(),
			}); err != nil {
				return 0, nil, err
			}
			body, err := v2.Envelope(v2WireRecord(model))
			if err != nil {
				return 0, nil, err
			}
			return http.StatusCreated, body, nil
		})
	if err != nil {
		v2.Fail(c, err)
		return
	}
	writeOutcome(c, outcome)
}

func (h *HandlerV2) Update(c *gin.Context) {
	id := c.Param("id")
	if err := ValidateID(id); err != nil {
		v2.Fail(c, err)
		return
	}
	key := c.GetHeader("Idempotency-Key")
	if err := idempotency.ValidateKey(key); err != nil {
		v2.Fail(c, err)
		return
	}
	raw, err := v2.ReadRawBody(c.Request, h.maxBodyBytes)
	if err != nil {
		v2.Fail(c, err)
		return
	}
	object, err := v2.ParseJSONObject(raw)
	if err != nil {
		v2.Fail(c, err)
		return
	}
	patch, changed, fieldErrors := v2ParsePatch(object)
	if fieldErrors != nil {
		v2.Fail(c, newValidationError(fieldErrors))
		return
	}
	if len(patch) == 0 {
		v2.Fail(c, httperr.New(httperr.ValidationFailed,
			httperr.WithMessage("Nenhuma alteração enviada.")))
		return
	}
	hash, err := idempotency.BodyHash(raw)
	if err != nil {
		v2.Fail(c, err)
		return
	}

	actor := v2.Actor(c)
	requestID := middleware.RequestID(c)
	scope := h.mutationScope(c, http.MethodPatch, v2BasePath+"/"+id, key)
	outcome, err := h.store.Execute(c.Request.Context(), scope, hash,
		func(ctx context.Context, tx bun.Tx) (int, []byte, error) {
			current, err := h.repo.GetForUpdate(ctx, tx, id)
			if err != nil {
				return 0, nil, err
			}
			_ = current
<% if (hasUpdatedAt) { -%>
			patch["updated_at"] = time.Now().UTC()
<% } -%>
<% if (hasUpdatedById) { -%>
			patch["updated_by_id"] = actor
<% } -%>
			if err := h.repo.UpdateColumns(ctx, tx, id, patch); err != nil {
				return 0, nil, err
			}
			updated, err := h.repo.Get(ctx, tx, id)
			if err != nil {
				return 0, nil, err
			}
			recordID := id
			if err := audit.Insert(ctx, tx, audit.Event{
				RequestID:     requestID,
				ActorUserID:   actor,
				Entity:        Entity,
				Operation:     "update",
				RecordID:      &recordID,
				ChangedFields: changed,
			}); err != nil {
				return 0, nil, err
			}
			body, err := v2.Envelope(v2WireRecord(updated))
			if err != nil {
				return 0, nil, err
			}
			return http.StatusOK, body, nil
		})
	if err != nil {
		v2.Fail(c, err)
		return
	}
	writeOutcome(c, outcome)
}

func (h *HandlerV2) Delete(c *gin.Context) {
	id := c.Param("id")
	if err := ValidateID(id); err != nil {
		v2.Fail(c, err)
		return
	}
	key := c.GetHeader("Idempotency-Key")
	if err := idempotency.ValidateKey(key); err != nil {
		v2.Fail(c, err)
		return
	}
	raw, err := v2.ReadRawBody(c.Request, h.maxBodyBytes)
	if err != nil {
		v2.Fail(c, err)
		return
	}
	hash, err := idempotency.BodyHash(raw)
	if err != nil {
		v2.Fail(c, err)
		return
	}

	actor := v2.Actor(c)
	requestID := middleware.RequestID(c)
	scope := h.mutationScope(c, http.MethodDelete, v2BasePath+"/"+id, key)
	outcome, err := h.store.Execute(c.Request.Context(), scope, hash,
		func(ctx context.Context, tx bun.Tx) (int, []byte, error) {
			affected, err := h.repo.Delete(ctx, tx, id)
			if err != nil {
				return 0, nil, err
			}
			if affected == 0 {
				return 0, nil, httperr.New(httperr.NotFound)
			}
			recordID := id
			if err := audit.Insert(ctx, tx, audit.Event{
				RequestID:   requestID,
				ActorUserID: actor,
				Entity:      Entity,
				Operation:   "delete",
				RecordID:    &recordID,
			}); err != nil {
				return 0, nil, err
			}
			body, err := v2.Envelope(&v2DeletePayload{ID: id, Deleted: true})
			if err != nil {
				return 0, nil, err
			}
			return http.StatusOK, body, nil
		})
	if err != nil {
		v2.Fail(c, err)
		return
	}
	writeOutcome(c, outcome)
}
