---
to: generated/.pollux-go-staging/internal/entity/<%= h.changeCase.camel(name) %>/handler_test.go
force: true
---
// Code generated by Pollux (go backend). DO NOT EDIT.
package <%= h.changeCase.camel(name) %>

import (
	"context"
	"encoding/json"
	"net/http"
	"net/http/httptest"
	"strings"
	"testing"

	"github.com/gin-gonic/gin"

	"pollux-go/internal/auth"
	"pollux-go/internal/httperr"
	"pollux-go/internal/middleware"
)

// fakeAuth lets contract tests run without a live Better Auth server. The
// database is nil on purpose: every request below must be rejected before
// any repository code runs, proving authorization and validation precede
// database access.
type fakeAuth struct {
	sessionErr error
	permErr    error
}

func (f *fakeAuth) Session(context.Context, string) (*auth.Session, error) {
	if f.sessionErr != nil {
		return nil, f.sessionErr
	}
	return &auth.Session{UserID: "user-1"}, nil
}

func (f *fakeAuth) RequirePermission(context.Context, string, string, string) error {
	return f.permErr
}

func (f *fakeAuth) Capabilities(context.Context, string, string) auth.Capabilities {
	return auth.Capabilities{CanRead: true}
}

// The bearer (v2) methods reuse the same failure knobs.
func (f *fakeAuth) SessionBearer(context.Context, string) (*auth.Session, error) {
	if f.sessionErr != nil {
		return nil, f.sessionErr
	}
	return &auth.Session{UserID: "user-1"}, nil
}

func (f *fakeAuth) RequirePermissionBearer(context.Context, string, string, string) error {
	return f.permErr
}

func newTestRouter(client auth.Client) *gin.Engine {
	gin.SetMode(gin.TestMode)
	engine := gin.New()
	engine.Use(middleware.RequestIDMiddleware())
	RegisterRoutes(engine.Group("/api/generated"), nil, client, nil)
	return engine
}

type envelope struct {
	OK    bool `json:"ok"`
	Error *struct {
		Code      string `json:"code"`
		Message   string `json:"message"`
		RequestID string `json:"requestId"`
		Retryable bool   `json:"retryable"`
	} `json:"error"`
}

func perform(t *testing.T, router *gin.Engine, method, path, body string) (int, envelope) {
	t.Helper()
	var reader *strings.Reader
	if body == "" {
		reader = strings.NewReader("")
	} else {
		reader = strings.NewReader(body)
	}
	req := httptest.NewRequest(method, path, reader)
	if body != "" {
		req.Header.Set("Content-Type", "application/json")
	}
	recorder := httptest.NewRecorder()
	router.ServeHTTP(recorder, req)

	var parsed envelope
	if err := json.Unmarshal(recorder.Body.Bytes(), &parsed); err != nil {
		t.Fatalf("%s %s: invalid envelope %q", method, path, recorder.Body.String())
	}
	return recorder.Code, parsed
}

var operations = []struct {
	method string
	path   string
	body   string
}{
	{http.MethodGet, "/api/generated/v1/<%= h.changeCase.camel(name) %>", ""},
	{http.MethodPost, "/api/generated/v1/<%= h.changeCase.camel(name) %>/page", `{"page":1,"perPage":10}`},
	{http.MethodGet, "/api/generated/v1/<%= h.changeCase.camel(name) %>/some-id", ""},
	{http.MethodPost, "/api/generated/v1/<%= h.changeCase.camel(name) %>", `{}`},
	{http.MethodPatch, "/api/generated/v1/<%= h.changeCase.camel(name) %>/some-id", `{"data":{}}`},
	{http.MethodDelete, "/api/generated/v1/<%= h.changeCase.camel(name) %>/some-id", ""},
	{http.MethodPost, "/api/generated/v1/<%= h.changeCase.camel(name) %>/bulk-delete", `{"ids":["a"]}`},
}

func TestEveryOperationRejectsAnonymous(t *testing.T) {
	router := newTestRouter(&fakeAuth{sessionErr: httperr.New(httperr.Unauthenticated)})
	for _, op := range operations {
		status, body := perform(t, router, op.method, op.path, op.body)
		if status != http.StatusUnauthorized || body.OK || body.Error == nil || body.Error.Code != "UNAUTHENTICATED" {
			t.Fatalf("%s %s: expected 401 UNAUTHENTICATED, got %d %+v", op.method, op.path, status, body)
		}
		if body.Error.RequestID == "" {
			t.Fatalf("%s %s: missing requestId", op.method, op.path)
		}
	}
}

func TestEveryOperationRejectsForbidden(t *testing.T) {
	router := newTestRouter(&fakeAuth{permErr: httperr.New(httperr.Forbidden)})
	for _, op := range operations {
		status, body := perform(t, router, op.method, op.path, op.body)
		if status != http.StatusForbidden || body.OK || body.Error == nil || body.Error.Code != "FORBIDDEN" {
			t.Fatalf("%s %s: expected 403 FORBIDDEN, got %d %+v", op.method, op.path, status, body)
		}
	}
}

func TestCapabilitiesRequiresOnlyAuthentication(t *testing.T) {
	router := newTestRouter(&fakeAuth{})
	status, body := perform(t, router, http.MethodGet, "/api/generated/v1/<%= h.changeCase.camel(name) %>/capabilities", "")
	if status != http.StatusOK || !body.OK {
		t.Fatalf("capabilities: expected 200 ok, got %d %+v", status, body)
	}

	anonymous := newTestRouter(&fakeAuth{sessionErr: httperr.New(httperr.Unauthenticated)})
	status, body = perform(t, anonymous, http.MethodGet, "/api/generated/v1/<%= h.changeCase.camel(name) %>/capabilities", "")
	if status != http.StatusUnauthorized || body.OK {
		t.Fatalf("capabilities anonymous: expected 401, got %d %+v", status, body)
	}
}

// Validation failures below must return 400 before the nil database is ever
// touched; a panic here means validation ran after data access.
func TestValidationPrecedesDatabase(t *testing.T) {
	router := newTestRouter(&fakeAuth{})
	base := "/api/generated/v1/<%= h.changeCase.camel(name) %>"
	cases := []struct {
		label  string
		method string
		path   string
		body   string
	}{
		{"page unknown JSON field", http.MethodPost, base + "/page", `{"page":1,"perPage":10,"bogus":1}`},
		{"page invalid sort field", http.MethodPost, base + "/page", `{"page":1,"perPage":10,"sort":[{"id":"not_a_column","desc":true}]}`},
		{"page perPage above bound", http.MethodPost, base + "/page", `{"page":1,"perPage":101}`},
		{"create unknown field", http.MethodPost, base, `{"definitelyNotAField":1}`},
		{"update unknown patch key", http.MethodPatch, base + "/some-id", `{"data":{"definitelyNotAField":1}}`},
		{"update oversized id", http.MethodPatch, base + "/" + strings.Repeat("x", 200), `{"data":{}}`},
		{"bulk delete empty", http.MethodPost, base + "/bulk-delete", `{"ids":[]}`},
		{"bulk delete duplicate ids", http.MethodPost, base + "/bulk-delete", `{"ids":["a","a"]}`},
		{"malformed json", http.MethodPost, base + "/page", `{not json`},
	}
	for _, tc := range cases {
		status, body := perform(t, router, tc.method, tc.path, tc.body)
		if status != http.StatusBadRequest || body.OK || body.Error == nil || body.Error.Code != "VALIDATION_FAILED" {
			t.Fatalf("%s: expected 400 VALIDATION_FAILED, got %d %+v", tc.label, status, body)
		}
	}
}
