---
to: generated/.pollux-go-staging/internal/entity/<%= h.changeCase.camel(name) %>/model.go
force: true
---
<%
const SYSTEM = ['id','createdAt','createdById','updatedAt','updatedById','deletedAt'];
let fields = (data && data.attributes ? data.attributes : []).map(function (f) {
  return { ...f, camel: h.camelField(f.name.trim()), column: f.name.trim(), dataType: (f.dataType || 'text').trim().toLowerCase() };
});
fields.forEach(function (f) { f.go = h.changeCase.pascal(f.camel); });
function goBase(t) {
  switch (t) {
    case 'smallint': case 'integer': return 'int32';
    case 'bigint': return 'int64';
    case 'real': return 'float32';
    case 'double': return 'float64';
    case 'boolean': return 'bool';
    case 'date': case 'timestamp': case 'timestamptz': return 'time.Time';
    default: return 'string';
  }
}
function goType(f) { const b = goBase(f.dataType); return f.isNullable === true ? '*' + b : b; }
const hasTime = fields.some(function (f) { return goBase(f.dataType) === 'time.Time'; });
const pk = fields.filter(function (f) { return f.isPrimaryKey === true; })[0];
function bunTag(f) {
  let tag = f.column;
  if (f.isPrimaryKey === true) tag += ',pk';
  if (f.camel === 'createdAt' || f.camel === 'updatedAt') tag += ',nullzero,default:now()';
  return tag;
}
-%>
// Code generated by Pollux (go backend). DO NOT EDIT.
package <%= h.changeCase.camel(name) %>

import (
<% if (hasTime) { -%>
	"time"

<% } -%>
	"github.com/uptrace/bun"
)

const (
	// Entity and Table are static generated identifiers; request values
	// never become SQL identifiers.
	Entity = "<%= h.changeCase.camel(name) %>"
	Table  = "<%= data.dbName || name %>"
)

// Model mirrors the PostgreSQL table. JSON properties use the same
// camelCase names as the TypeScript backend; columns keep metadata names.
type Model struct {
	bun.BaseModel `bun:"table:<%= data.dbName || name %>" json:"-"`

<% fields.forEach(function (f) { -%>
	<%= f.go %> <%= goType(f) %> `bun:"<%= bunTag(f) %>" json:"<%= f.camel %>"`
<% }) -%>
}

// PrimaryKey returns the row identifier.
func (m *Model) PrimaryKey() string { return <%= pk && goBase(pk.dataType) === 'string' ? 'm.' + pk.go : 'string(m.' + (pk ? pk.go : 'ID') + ')' %> }
