---
to: generated/.pollux-go-staging/internal/entity/<%= h.changeCase.camel(name) %>/repository.go
force: true
---
<%
let fields = (data && data.attributes ? data.attributes : []).map(function (f) {
  return { ...f, camel: h.camelField(f.name.trim()), column: f.name.trim(), dataType: (f.dataType || 'text').trim().toLowerCase() };
});
const pk = fields.filter(function (f) { return f.isPrimaryKey === true; })[0];
const pkColumn = pk ? pk.column : 'id';
-%>
// Code generated by Pollux (go backend). DO NOT EDIT.
package <%= h.changeCase.camel(name) %>

import (
	"context"
	"database/sql"
	"errors"
	"strconv"
	"strings"

	"github.com/uptrace/bun"

	"pollux-go/internal/httperr"
)

const pkColumn = "<%= pkColumn %>"

// Repository owns every Bun query for this entity. All identifiers come
// from generated allowlists; every query receives the request context.
type Repository struct{}

func escapeLike(value string) string {
	replacer := strings.NewReplacer(`\`, `\\`, `%`, `\%`, `_`, `\_`)
	return replacer.Replace(value)
}

func applyWhere(query *bun.SelectQuery, input *PageInput) (*bun.SelectQuery, error) {
	q := strings.TrimSpace(input.Q)
	if q != "" && len(searchableColumns) > 0 {
		pattern := "%" + escapeLike(q) + "%"
		query = query.WhereGroup(" AND ", func(group *bun.SelectQuery) *bun.SelectQuery {
			for _, column := range searchableColumns {
				group = group.WhereOr("? ILIKE ?", bun.Ident(column), pattern)
			}
			return group
		})
	}

	for _, filter := range input.Filters {
		if len(filter.Value) == 0 {
			continue
		}
		column := filterableColumns[filter.ID]
		switch filterKinds[filter.ID] {
		case "boolean":
			values := make([]bool, 0, len(filter.Value))
			for _, raw := range filter.Value {
				values = append(values, raw == "true")
			}
			query = query.Where("? IN (?)", bun.Ident(column), bun.In(values))
		case "number":
			parsed, err := strconv.ParseFloat(filter.Value[0], 64)
			if err != nil {
				return nil, httperr.New(httperr.ValidationFailed,
					httperr.WithFieldErrors(map[string][]string{"filters": {"Valor de filtro numérico inválido"}}))
			}
			query = query.Where("? = ?", bun.Ident(column), parsed)
		case "text":
			query = query.Where("? ILIKE ?", bun.Ident(column), "%"+escapeLike(filter.Value[0])+"%")
		}
	}
	return query, nil
}

// List is the bounded client-table read: ordered by primary key, capped.
func (Repository) List(ctx context.Context, db bun.IDB) ([]Model, error) {
	rows := []Model{}
	err := db.NewSelect().Model(&rows).
		OrderExpr("? ASC", bun.Ident(pkColumn)).
		Limit(10000).
		Scan(ctx)
	return rows, err
}

// Page runs the allowlisted server-side page query; the count uses the
// identical where clause.
func (Repository) Page(ctx context.Context, db bun.IDB, input *PageInput) ([]Model, int, error) {
	rows := []Model{}
	query := db.NewSelect().Model(&rows)

	query, err := applyWhere(query, input)
	if err != nil {
		return nil, 0, err
	}

	for _, item := range input.Sort {
		column := sortableColumns[item.ID]
		if item.Desc {
			query = query.OrderExpr("? DESC", bun.Ident(column))
		} else {
			query = query.OrderExpr("? ASC", bun.Ident(column))
		}
	}
	// Deterministic tiebreaker.
	query = query.OrderExpr("? ASC", bun.Ident(pkColumn))

	total, err := query.
		Limit(input.PerPage).
		Offset((input.Page - 1) * input.PerPage).
		ScanAndCount(ctx)
	if err != nil {
		return nil, 0, err
	}
	return rows, total, nil
}

func (Repository) Get(ctx context.Context, db bun.IDB, id string) (*Model, error) {
	row := new(Model)
	err := db.NewSelect().Model(row).
		Where("? = ?", bun.Ident(pkColumn), id).
		Limit(1).
		Scan(ctx)
	if errors.Is(err, sql.ErrNoRows) {
		return nil, httperr.New(httperr.NotFound)
	}
	if err != nil {
		return nil, err
	}
	return row, nil
}

// GetForUpdate locks the current row inside the transaction.
func (Repository) GetForUpdate(ctx context.Context, tx bun.IDB, id string) (*Model, error) {
	row := new(Model)
	err := tx.NewSelect().Model(row).
		Where("? = ?", bun.Ident(pkColumn), id).
		Limit(1).
		For("UPDATE").
		Scan(ctx)
	if errors.Is(err, sql.ErrNoRows) {
		return nil, httperr.New(httperr.NotFound)
	}
	if err != nil {
		return nil, err
	}
	return row, nil
}

func (Repository) Insert(ctx context.Context, tx bun.IDB, model *Model) error {
	_, err := tx.NewInsert().Model(model).Returning("*").Exec(ctx)
	return err
}

// UpdateColumns applies an allowlisted column patch to one row.
func (Repository) UpdateColumns(ctx context.Context, tx bun.IDB, id string, patch map[string]any) error {
	_, err := tx.NewUpdate().
		Model(&patch).
		Table(Table).
		Where("? = ?", bun.Ident(pkColumn), id).
		Exec(ctx)
	return err
}

func (Repository) Delete(ctx context.Context, tx bun.IDB, id string) (int64, error) {
	result, err := tx.NewDelete().
		Model((*Model)(nil)).
		Where("? = ?", bun.Ident(pkColumn), id).
		Exec(ctx)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

func (Repository) BulkDelete(ctx context.Context, tx bun.IDB, ids []string) (int64, error) {
	result, err := tx.NewDelete().
		Model((*Model)(nil)).
		Where("? IN (?)", bun.Ident(pkColumn), bun.In(ids)).
		Exec(ctx)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}
