---
to: generated/.pollux-go-staging/internal/entity/<%= h.changeCase.camel(name) %>/repository_pg_test.go
force: true
---
// Code generated by Pollux (go backend). DO NOT EDIT.
package <%= h.changeCase.camel(name) %>

import (
	"context"
	"database/sql"
	"os"
	"testing"

	"github.com/uptrace/bun"
	"github.com/uptrace/bun/dialect/pgdialect"

	_ "github.com/jackc/pgx/v5/stdlib"
)

// PostgreSQL integration tests run only when POLLUX_TEST_DATABASE_URL is
// set; otherwise they are skipped and stay separated from the unit suite.
func testDB(t *testing.T) *bun.DB {
	t.Helper()
	url := os.Getenv("POLLUX_TEST_DATABASE_URL")
	if url == "" {
		t.Skip("POLLUX_TEST_DATABASE_URL not set; skipping PostgreSQL integration test")
	}
	sqldb, err := sql.Open("pgx", url)
	if err != nil {
		t.Fatalf("open: %v", err)
	}
	t.Cleanup(func() { _ = sqldb.Close() })
	return bun.NewDB(sqldb, pgdialect.New())
}

func TestPageBoundsIntegration(t *testing.T) {
	db := testDB(t)
	repo := Repository{}
	input := &PageInput{Page: 1, PerPage: 10}
	rows, total, err := repo.Page(context.Background(), db, input)
	if err != nil {
		t.Fatalf("page: %v", err)
	}
	if len(rows) > 10 {
		t.Fatalf("page exceeded perPage: %d", len(rows))
	}
	if total < len(rows) {
		t.Fatalf("total %d smaller than page rows %d", total, len(rows))
	}
}

func TestListBoundIntegration(t *testing.T) {
	db := testDB(t)
	repo := Repository{}
	rows, err := repo.List(context.Background(), db)
	if err != nil {
		t.Fatalf("list: %v", err)
	}
	if len(rows) > 10000 {
		t.Fatalf("list exceeded bound: %d", len(rows))
	}
}
