---
to: generated/.pollux-go-staging/internal/entity/<%= h.changeCase.camel(name) %>/routes.go
force: true
---
// Code generated by Pollux (go backend). DO NOT EDIT.
package <%= h.changeCase.camel(name) %>

import (
	"log/slog"

	"github.com/gin-gonic/gin"
	"github.com/uptrace/bun"

	"pollux-go/internal/auth"
	"pollux-go/internal/authz"
	"pollux-go/internal/httperr"
	v2 "pollux-go/internal/v2"
)

// newValidationError adapts field errors to the shared taxonomy.
func newValidationError(fieldErrors map[string][]string) error {
	return httperr.New(httperr.ValidationFailed, httperr.WithFieldErrors(fieldErrors))
}

// RegisterRoutes mounts this entity below /api/generated: the unchanged v1
// contract at /v1/<entity> (cookie session) and the SPEC-003 standalone v2
// contract at /v2/<entity> (bearer token, flat envelopes, idempotent
// mutations). Entity and action strings are static generated values;
// authorization middleware runs before every handler and the database is
// never touched on denial.
func RegisterRoutes(root *gin.RouterGroup, db *bun.DB, client auth.Client, logger *slog.Logger) {
	_ = logger
	handler := NewHandler(NewService(db), client, 1<<20)

	group := root.Group("/v1/<%= h.changeCase.camel(name) %>")
	group.GET("/capabilities", authz.Authenticate(client, Entity), handler.Capabilities)
	group.GET("", authz.Require(client, Entity, "read", "list"), handler.List)
	group.POST("/page", authz.Require(client, Entity, "read", "page"), handler.Page)
	group.GET("/:id", authz.Require(client, Entity, "read", "get"), handler.Get)
	group.POST("", authz.Require(client, Entity, "create", "add"), handler.Create)
	group.PATCH("/:id", authz.Require(client, Entity, "update", "update"), handler.Update)
	group.DELETE("/:id", authz.Require(client, Entity, "delete", "delete"), handler.Delete)
	group.POST("/bulk-delete", authz.Require(client, Entity, "delete", "bulkDelete"), handler.BulkDelete)

	handlerV2 := NewHandlerV2(db, client, 1<<20)

	groupV2 := root.Group("/v2/<%= h.changeCase.camel(name) %>")
	groupV2.GET("/capabilities", v2.AuthenticateBearer(client, Entity), handlerV2.Capabilities)
	groupV2.GET("", v2.RequireBearer(client, Entity, "read", "v2.list"), handlerV2.List)
	groupV2.GET("/:id", v2.RequireBearer(client, Entity, "read", "v2.get"), handlerV2.Get)
	groupV2.POST("", v2.RequireBearer(client, Entity, "create", "v2.create"), handlerV2.Create)
	groupV2.PATCH("/:id", v2.RequireBearer(client, Entity, "update", "v2.update"), handlerV2.Update)
	groupV2.DELETE("/:id", v2.RequireBearer(client, Entity, "delete", "v2.delete"), handlerV2.Delete)
}
