---
to: generated/.pollux-go-staging/internal/entity/<%= h.changeCase.camel(name) %>/service.go
force: true
---
<%
const SYSTEM = ['id','createdAt','createdById','updatedAt','updatedById','deletedAt'];
let fields = (data && data.attributes ? data.attributes : []).map(function (f) {
  return { ...f, camel: h.camelField(f.name.trim()), column: f.name.trim(), dataType: (f.dataType || 'text').trim().toLowerCase() };
});
fields.forEach(function (f) { f.go = h.changeCase.pascal(f.camel); });
const isSystem = function (f) { return SYSTEM.indexOf(f.camel) !== -1; };
const addFields = fields.filter(function (f) { return f.fnrIsinFormAdd === true && !isSystem(f); });
const hasCreatedById = fields.some(function (f) { return f.camel === 'createdById'; });
const hasUpdatedById = fields.some(function (f) { return f.camel === 'updatedById'; });
const hasUpdatedAt = fields.some(function (f) { return f.camel === 'updatedAt'; });
const createdByNullable = fields.some(function (f) { return f.camel === 'createdById' && f.isNullable === true; });
const updatedByNullable = fields.some(function (f) { return f.camel === 'updatedById' && f.isNullable === true; });
const pk = fields.filter(function (f) { return f.isPrimaryKey === true; })[0];
-%>
// Code generated by Pollux (go backend). DO NOT EDIT.
package <%= h.changeCase.camel(name) %>

import (
	"context"
	"database/sql"
<% if (hasUpdatedAt) { -%>
	"time"
<% } -%>

	"github.com/google/uuid"
	"github.com/uptrace/bun"

	"pollux-go/internal/audit"
	"pollux-go/internal/httperr"
)

// Service owns business rules and transaction boundaries. Authorization has
// already happened at the route boundary before any service method runs.
type Service struct {
	db   *bun.DB
	repo Repository
}

func NewService(db *bun.DB) *Service {
	return &Service{db: db}
}

// PageResult mirrors the TypeScript page contract.
type PageResult struct {
	Rows      []Model `json:"rows"`
	Total     int     `json:"total"`
	Page      int     `json:"page"`
	PerPage   int     `json:"perPage"`
	PageCount int     `json:"pageCount"`
}

// DeleteResult mirrors the TypeScript deletion contract.
type DeleteResult struct {
	DeletedCount int64 `json:"deletedCount"`
}

func (s *Service) List(ctx context.Context) ([]Model, error) {
	return s.repo.List(ctx, s.db)
}

func (s *Service) Page(ctx context.Context, input *PageInput) (*PageResult, error) {
	rows, total, err := s.repo.Page(ctx, s.db, input)
	if err != nil {
		return nil, err
	}
	pageCount := 0
	if total > 0 {
		pageCount = (total + input.PerPage - 1) / input.PerPage
	}
	return &PageResult{
		Rows:      rows,
		Total:     total,
		Page:      input.Page,
		PerPage:   input.PerPage,
		PageCount: pageCount,
	}, nil
}

func (s *Service) Get(ctx context.Context, id string) (*Model, error) {
	return s.repo.Get(ctx, s.db, id)
}

// buildModel constructs the persistence model from the allowlisted DTO.
// Actor fields come from the session; timestamps come from the database.
func buildModel(in *CreateInput, actor string) *Model {
	_ = actor
	model := &Model{<%= pk ? pk.go : 'ID' %>: uuid.NewString()}
<% addFields.forEach(function (f) { -%>
<% if (f.isNullable === true) { -%>
	model.<%= f.go %> = in.<%= f.go %>
<% } else { -%>
	if in.<%= f.go %> != nil {
		model.<%= f.go %> = *in.<%= f.go %>
	}
<% } -%>
<% }) -%>
<% if (hasCreatedById) { -%>
	model.CreatedById = <%- createdByNullable ? '&actor' : 'actor' %>
<% } -%>
<% if (hasUpdatedById) { -%>
	model.UpdatedById = <%- updatedByNullable ? '&actor' : 'actor' %>
<% } -%>
	return model
}

func (s *Service) Create(ctx context.Context, actor, requestID string, in *CreateInput) (*Model, error) {
	model := buildModel(in, actor)
	err := s.db.RunInTx(ctx, &sql.TxOptions{}, func(ctx context.Context, tx bun.Tx) error {
		if err := s.repo.Insert(ctx, tx, model); err != nil {
			return err
		}
		recordID := model.PrimaryKey()
		return audit.Insert(ctx, tx, audit.Event{
			RequestID:     requestID,
			ActorUserID:   actor,
			Entity:        Entity,
			Operation:     "create",
			RecordID:      &recordID,
			ChangedFields: in.ChangedFields(),
		})
	})
	if err != nil {
		return nil, err
	}
	return model, nil
}

<% if (hasUpdatedAt) { -%>
func staleWrite(current *Model, expected ExpectedUpdatedAt) bool {
	if !expected.Present {
		return false
	}
	currentValue := current.UpdatedAt
	if currentValue == nil && expected.Value == nil {
		return false
	}
	if currentValue == nil || expected.Value == nil {
		return true
	}
	return currentValue.Truncate(time.Millisecond).UnixMilli() != expected.Value.Truncate(time.Millisecond).UnixMilli()
}

<% } -%>
func (s *Service) Update(ctx context.Context, actor, requestID, id string, expected ExpectedUpdatedAt, patch map[string]any, changed []string) (*Model, error) {
	if len(patch) == 0 {
		return nil, httperr.New(httperr.ValidationFailed,
			httperr.WithMessage("Nenhuma alteração enviada."))
	}

	var updated *Model
	err := s.db.RunInTx(ctx, &sql.TxOptions{}, func(ctx context.Context, tx bun.Tx) error {
		current, err := s.repo.GetForUpdate(ctx, tx, id)
		if err != nil {
			return err
		}
<% if (hasUpdatedAt) { -%>
		if staleWrite(current, expected) {
			return httperr.New(httperr.StaleWrite)
		}
		patch["updated_at"] = time.Now().UTC()
<% } else { -%>
		_ = expected
		_ = current
<% } -%>
<% if (hasUpdatedById) { -%>
		patch["updated_by_id"] = actor
<% } -%>
		if err := s.repo.UpdateColumns(ctx, tx, id, patch); err != nil {
			return err
		}
		updated, err = s.repo.Get(ctx, tx, id)
		if err != nil {
			return err
		}
		recordID := id
		return audit.Insert(ctx, tx, audit.Event{
			RequestID:     requestID,
			ActorUserID:   actor,
			Entity:        Entity,
			Operation:     "update",
			RecordID:      &recordID,
			ChangedFields: changed,
		})
	})
	if err != nil {
		return nil, err
	}
	return updated, nil
}

func (s *Service) Delete(ctx context.Context, actor, requestID, id string) (*DeleteResult, error) {
	var result *DeleteResult
	err := s.db.RunInTx(ctx, &sql.TxOptions{}, func(ctx context.Context, tx bun.Tx) error {
		affected, err := s.repo.Delete(ctx, tx, id)
		if err != nil {
			return err
		}
		if affected == 0 {
			return httperr.New(httperr.NotFound)
		}
		recordID := id
		if err := audit.Insert(ctx, tx, audit.Event{
			RequestID:   requestID,
			ActorUserID: actor,
			Entity:      Entity,
			Operation:   "delete",
			RecordID:    &recordID,
		}); err != nil {
			return err
		}
		result = &DeleteResult{DeletedCount: affected}
		return nil
	})
	if err != nil {
		return nil, err
	}
	return result, nil
}

// BulkDelete is atomic: when any requested row is missing, the whole
// transaction rolls back and nothing is deleted.
func (s *Service) BulkDelete(ctx context.Context, actor, requestID string, ids []string) (*DeleteResult, error) {
	var result *DeleteResult
	err := s.db.RunInTx(ctx, &sql.TxOptions{}, func(ctx context.Context, tx bun.Tx) error {
		affected, err := s.repo.BulkDelete(ctx, tx, ids)
		if err != nil {
			return err
		}
		if affected != int64(len(ids)) {
			return httperr.New(httperr.NotFound,
				httperr.WithMessage("Alguns registros não foram encontrados - Nenhuma exclusão foi realizada"))
		}
		if err := audit.Insert(ctx, tx, audit.Event{
			RequestID:   requestID,
			ActorUserID: actor,
			Entity:      Entity,
			Operation:   "bulk_delete",
			RecordCount: int(affected),
		}); err != nil {
			return err
		}
		result = &DeleteResult{DeletedCount: affected}
		return nil
	})
	if err != nil {
		return nil, err
	}
	return result, nil
}
