---
to: generated/.pollux-go-staging/internal/entity/<%= h.changeCase.camel(name) %>/v2.go
force: true
---
<%
const SYSTEM = ['id','createdAt','createdById','updatedAt','updatedById','deletedAt'];
let fields = (data && data.attributes ? data.attributes : []).map(function (f) {
  return { ...f, camel: h.camelField(f.name.trim()), column: f.name.trim(), dataType: (f.dataType || 'text').trim().toLowerCase() };
});
fields.forEach(function (f) { f.go = h.changeCase.pascal(f.camel); });
const isSystem = function (f) { return SYSTEM.indexOf(f.camel) !== -1; };
const addFields = fields.filter(function (f) { return f.fnrIsinFormAdd === true && !isSystem(f); });
const updFields = fields.filter(function (f) { return f.fedIsinFormUpd === true && !isSystem(f); });
const pk = fields.filter(function (f) { return f.isPrimaryKey === true; })[0];
const pkCamel = pk ? pk.camel : 'id';
function goBase(t) {
  switch (t) {
    case 'smallint': case 'integer': return 'int32';
    case 'bigint': return 'int64';
    case 'real': return 'float32';
    case 'double': return 'float64';
    case 'boolean': return 'bool';
    case 'date': case 'timestamp': case 'timestamptz': return 'time.Time';
    default: return 'string';
  }
}
// Contract scalar (test-fixtures/pollux/api/contract.json wireEncodingByScalar).
function scalar(f) {
  switch (f.dataType) {
    case 'uuid': return 'uuid';
    case 'char': case 'varchar': return 'varchar';
    case 'text': return 'text';
    case 'boolean': return 'boolean';
    case 'smallint': case 'integer': case 'bigint': return 'integer';
    case 'real': case 'double': return 'float';
    case 'numeric': return 'numeric';
    case 'date': return 'date';
    case 'time': case 'timetz': return 'time';
    case 'timestamp': case 'timestamptz': return 'timestamp';
    default: return 'text';
  }
}
const stringFamily = ['uuid', 'varchar', 'text'];
// Operator table by contract scalar (contract.json filterOperatorsByScalar).
function opsFor(f) {
  const s = scalar(f);
  if (s === 'uuid' || s === 'boolean') return ['eq'];
  if (s === 'varchar' || s === 'text') return ['contains', 'eq'];
  return ['eq', 'gt', 'gte', 'lt', 'lte'];
}
function defaultOp(f) {
  const s = scalar(f);
  return (s === 'varchar' || s === 'text') ? 'contains' : 'eq';
}
// Declared v2 filters: visible grid columns, never the primary key.
const filterable = fields.filter(function (f) { return f.grdIsinGrid === true && !f.isPrimaryKey; });
// q searches the visible string/varchar/text columns (contract semantics).
const searchable = fields.filter(function (f) {
  const s = scalar(f);
  return f.grdIsinGrid === true && (s === 'varchar' || s === 'text');
});
const wireHasTime = fields.some(function (f) { return goBase(f.dataType) === 'time.Time'; });
const dtoTimeFields = addFields.concat(updFields).filter(function (f) { return goBase(f.dataType) === 'time.Time'; });
const numericAdd = addFields.filter(function (f) { return f.dataType === 'numeric'; });
const numericUpd = updFields.filter(function (f) { return f.dataType === 'numeric'; });
const filterScalars = filterable.map(scalar);
const needStrconv = filterScalars.some(function (s) { return ['integer', 'float', 'numeric'].indexOf(s) !== -1; });
const filterNeedsTime = filterScalars.some(function (s) { return ['date', 'timestamp'].indexOf(s) !== -1; });
// The "time" package identifier is referenced only by DTO/filter parsing;
// wire formatting calls methods on time.Time values without naming the
// package. Import accordingly, but emit the format consts whenever any
// time-family field exists.
const needTime = dtoTimeFields.length > 0 || filterNeedsTime;
const needTimeConsts = wireHasTime || needTime;
const needStrings = numericAdd.length > 0 || numericUpd.length > 0;
function jsonTmp(f) {
  // JSON decoding target for the wire value of a DTO field.
  if (goBase(f.dataType) === 'time.Time') return '*string';
  return '*' + goBase(f.dataType);
}
-%>
// Code generated by Pollux (go backend). DO NOT EDIT.
package <%= h.changeCase.camel(name) %>

import (
	"context"
	"encoding/json"
<% if (needStrconv) { -%>
	"strconv"
<% } -%>
<% if (needStrings) { -%>
	"strings"
<% } -%>
<% if (needTime) { -%>
	"time"
<% } -%>

	"github.com/uptrace/bun"

	"pollux-go/internal/httperr"
	v2 "pollux-go/internal/v2"
)

// v2 standalone contract (test-fixtures/pollux/api/contract.md) for this
// entity: generated allowlists, wire codecs and query execution. All
// identifiers are static generated strings; request values never become
// SQL identifiers.

// v2ModelFields distinguishes "known but not writable" from "unknown".
var v2ModelFields = map[string]bool{
<% fields.forEach(function (f) { -%>
	"<%= f.camel %>": true,
<% }) -%>
}

var v2SortColumns = map[string]string{
<% fields.forEach(function (f) { -%>
	"<%= f.camel %>": "<%= f.column %>",
<% }) -%>
}

var v2FilterColumns = map[string]string{
<% filterable.forEach(function (f) { -%>
	"<%= f.camel %>": "<%= f.column %>",
<% }) -%>
}

var v2FilterScalars = map[string]string{
<% filterable.forEach(function (f) { -%>
	"<%= f.camel %>": "<%= scalar(f) %>",
<% }) -%>
}

var v2SearchColumns = []string{
<% searchable.forEach(function (f) { -%>
	"<%= f.column %>",
<% }) -%>
}

// v2ListSpec drives the shared strict query parser.
var v2ListSpec = v2.ListSpec{
	Sortable: func() map[string]bool {
		out := make(map[string]bool, len(v2SortColumns))
		for field := range v2SortColumns {
			out[field] = true
		}
		return out
	}(),
	FilterOps: map[string]map[string]bool{
<% filterable.forEach(function (f) { -%>
		"<%= f.camel %>": {<%- opsFor(f).map(function (op) { return '"' + op + '": true'; }).join(', ') %>},
<% }) -%>
	},
	FilterDefaultOp: map[string]string{
<% filterable.forEach(function (f) { -%>
		"<%= f.camel %>": "<%= defaultOp(f) %>",
<% }) -%>
	},
	DefaultPageSize: 10,
	DefaultSort:     []v2.SortItem{{ID: "<%= pkCamel %>", Desc: false}},
}

<% if (needTimeConsts) { -%>
const (
	v2DateFormat      = "2006-01-02"
	v2TimestampFormat = "2006-01-02T15:04:05.000Z07:00"
)

<% } -%>
// v2WireRecord encodes the canonical record: numeric stays a decimal string,
// date is YYYY-MM-DD, timestamp is ISO-8601 UTC, null stays null.
func v2WireRecord(m *Model) map[string]any {
	record := map[string]any{}
<% fields.forEach(function (f) { -%>
<% if (f.dataType === 'date') { -%>
<% if (f.isNullable === true) { -%>
	if m.<%= f.go %> != nil {
		record["<%= f.camel %>"] = m.<%= f.go %>.Format(v2DateFormat)
	} else {
		record["<%= f.camel %>"] = nil
	}
<% } else { -%>
	record["<%= f.camel %>"] = m.<%= f.go %>.Format(v2DateFormat)
<% } -%>
<% } else if (f.dataType === 'timestamp' || f.dataType === 'timestamptz') { -%>
<% if (f.isNullable === true) { -%>
	if m.<%= f.go %> != nil {
		record["<%= f.camel %>"] = m.<%= f.go %>.UTC().Format(v2TimestampFormat)
	} else {
		record["<%= f.camel %>"] = nil
	}
<% } else { -%>
	record["<%= f.camel %>"] = m.<%= f.go %>.UTC().Format(v2TimestampFormat)
<% } -%>
<% } else { -%>
	record["<%= f.camel %>"] = m.<%= f.go %>
<% } -%>
<% }) -%>
	return record
}

func v2WireRows(models []Model) []map[string]any {
	rows := make([]map[string]any, 0, len(models))
	for i := range models {
		rows = append(rows, v2WireRecord(&models[i]))
	}
	return rows
}

<% if (dtoTimeFields.length > 0) { -%>
func v2ParseWireTime(value *string, dataType string) (*time.Time, bool) {
	if value == nil {
		return nil, true
	}
	layout := v2TimestampFormat
	if dataType == "date" {
		layout = v2DateFormat
	}
	parsed, err := time.Parse(layout, *value)
	if err != nil && dataType != "date" {
		// Accept any valid RFC3339 timestamp, not only the canonical form.
		parsed, err = time.Parse(time.RFC3339, *value)
	}
	if err != nil {
		return nil, false
	}
	return &parsed, true
}

<% } -%>
// v2ParseCreate decodes a strict flat JSON object into the create DTO.
// Unknown fields, non-writable fields and wire-type mismatches map to
// fieldErrors; the shared CreateInput.Validate then applies field rules.
func v2ParseCreate(raw map[string]json.RawMessage) (*CreateInput, map[string][]string) {
	in := &CreateInput{}
	fieldErrors := map[string][]string{}
	for key, value := range raw {
		switch key {
<% addFields.forEach(function (f) { -%>
		case "<%= f.camel %>":
			var parsed <%= jsonTmp(f) %>
			if err := json.Unmarshal(value, &parsed); err != nil {
				addFieldError(fieldErrors, key, "Valor inválido para o tipo do campo")
				continue
			}
<% if (goBase(f.dataType) === 'time.Time') { -%>
			converted, ok := v2ParseWireTime(parsed, "<%= f.dataType === 'date' ? 'date' : 'timestamp' %>")
			if !ok {
				addFieldError(fieldErrors, key, "<%= f.dataType === 'date' ? 'Data inválida (use YYYY-MM-DD)' : 'Data/hora inválida (use ISO-8601)' %>")
				continue
			}
			in.<%= f.go %> = converted
<% } else { -%>
			in.<%= f.go %> = parsed
<% } -%>
<% } ) -%>
		default:
			if v2ModelFields[key] {
				addFieldError(fieldErrors, key, "not_writable")
			} else {
				addFieldError(fieldErrors, key, "unknown_field")
			}
		}
	}
<% numericAdd.forEach(function (f) { -%>
	// Contract: an empty numeric input must be null, never ""/0.
	if in.<%= f.go %> != nil && strings.TrimSpace(*in.<%= f.go %>) == "" {
		addFieldError(fieldErrors, "<%= f.camel %>", "Número vazio: envie null")
	}
<% }) -%>
	if len(fieldErrors) > 0 {
		return nil, fieldErrors
	}
	if errs := in.Validate(); errs != nil {
		return nil, errs
	}
	return in, nil
}

// v2ParsePatch decodes a strict flat JSON PATCH body into a column patch.
// Fields outside the update allowlist are rejected, never stripped.
func v2ParsePatch(raw map[string]json.RawMessage) (map[string]any, []string, map[string][]string) {
	patch := map[string]any{}
	var changed []string
	fieldErrors := map[string][]string{}
	for key, value := range raw {
		switch key {
<% updFields.forEach(function (f) { -%>
		case "<%= f.camel %>":
			var parsed <%= jsonTmp(f) %>
			if err := json.Unmarshal(value, &parsed); err != nil {
				addFieldError(fieldErrors, key, "Valor inválido para o tipo do campo")
				continue
			}
<% if (goBase(f.dataType) === 'time.Time') { -%>
			converted, ok := v2ParseWireTime(parsed, "<%= f.dataType === 'date' ? 'date' : 'timestamp' %>")
			if !ok {
				addFieldError(fieldErrors, key, "<%= f.dataType === 'date' ? 'Data inválida (use YYYY-MM-DD)' : 'Data/hora inválida (use ISO-8601)' %>")
				continue
			}
<% if (f.isNullable !== true) { -%>
			if converted == nil {
				addFieldError(fieldErrors, key, "Campo não pode ser nulo")
				continue
			}
			patch["<%= f.column %>"] = *converted
<% } else { -%>
			patch["<%= f.column %>"] = converted
<% } -%>
<% } else { -%>
<% if (f.isNullable !== true) { -%>
			if parsed == nil {
				addFieldError(fieldErrors, key, "Campo não pode ser nulo")
				continue
			}
<% } -%>
<% if (f.dataType === 'numeric') { -%>
			if parsed != nil && strings.TrimSpace(*parsed) == "" {
				addFieldError(fieldErrors, key, "Número vazio: envie null")
				continue
			}
			if parsed != nil && !numericPattern.MatchString(strings.TrimSpace(*parsed)) {
				addFieldError(fieldErrors, key, "Número inválido")
				continue
			}
<% } -%>
<% if (f.dataType === 'smallint') { -%>
			if parsed != nil && (*parsed < -32768 || *parsed > 32767) {
				addFieldError(fieldErrors, key, "Valor fora do intervalo permitido")
				continue
			}
<% } -%>
<% if (f.isNullable === true) { -%>
			patch["<%= f.column %>"] = parsed
<% } else { -%>
			patch["<%= f.column %>"] = *parsed
<% } -%>
<% } -%>
			changed = append(changed, key)
<% }) -%>
		default:
			if v2ModelFields[key] {
				addFieldError(fieldErrors, key, "not_writable")
			} else {
				addFieldError(fieldErrors, key, "unknown_field")
			}
		}
	}
	if len(fieldErrors) > 0 {
		return nil, nil, fieldErrors
	}
	return patch, changed, nil
}

var v2SQLOps = map[string]string{
	"eq":  "=",
	"gt":  ">",
	"gte": ">=",
	"lt":  "<",
	"lte": "<=",
}

func v2FilterError(field, message string) error {
	return httperr.New(httperr.ValidationFailed,
		httperr.WithFieldErrors(map[string][]string{"f_" + field: {message}}))
}

// v2ApplyQuery applies q search and declared typed filters. Columns and
// operators come exclusively from generated allowlists.
func v2ApplyQuery(query *bun.SelectQuery, list *v2.ListQuery) (*bun.SelectQuery, error) {
	if list.Q != "" && len(v2SearchColumns) > 0 {
		pattern := "%" + escapeLike(list.Q) + "%"
		query = query.WhereGroup(" AND ", func(group *bun.SelectQuery) *bun.SelectQuery {
			for _, column := range v2SearchColumns {
				group = group.WhereOr("? ILIKE ?", bun.Ident(column), pattern)
			}
			return group
		})
	}

	for _, filter := range list.Filters {
		column := v2FilterColumns[filter.Field]
		sqlOp := v2SQLOps[filter.Op]
		switch v2FilterScalars[filter.Field] {
		case "varchar", "text":
			if filter.Op == "contains" {
				query = query.Where("? ILIKE ?", bun.Ident(column), "%"+escapeLike(filter.Value)+"%")
			} else {
				query = query.Where("? = ?", bun.Ident(column), filter.Value)
			}
		case "uuid":
			query = query.Where("?::text = ?", bun.Ident(column), filter.Value)
		case "boolean":
			if filter.Value != "true" && filter.Value != "false" {
				return nil, v2FilterError(filter.Field, "Valor booleano inválido")
			}
			query = query.Where("? = ?", bun.Ident(column), filter.Value == "true")
<% if (needStrconv) { -%>
		case "integer":
			parsed, err := strconv.ParseInt(filter.Value, 10, 64)
			if err != nil {
				return nil, v2FilterError(filter.Field, "Número inteiro inválido")
			}
			query = query.Where("? "+sqlOp+" ?", bun.Ident(column), parsed)
		case "float", "numeric":
			parsed, err := strconv.ParseFloat(filter.Value, 64)
			if err != nil {
				return nil, v2FilterError(filter.Field, "Número inválido")
			}
			query = query.Where("? "+sqlOp+" ?", bun.Ident(column), parsed)
<% } -%>
<% if (filterNeedsTime) { -%>
		case "date":
			parsed, err := time.Parse(v2DateFormat, filter.Value)
			if err != nil {
				return nil, v2FilterError(filter.Field, "Data inválida (use YYYY-MM-DD)")
			}
			query = query.Where("? "+sqlOp+" ?", bun.Ident(column), parsed)
		case "timestamp":
			parsed, err := time.Parse(time.RFC3339, filter.Value)
			if err != nil {
				return nil, v2FilterError(filter.Field, "Data/hora inválida (use ISO-8601)")
			}
			query = query.Where("? "+sqlOp+" ?", bun.Ident(column), parsed)
<% } -%>
		case "time":
			query = query.Where("? "+sqlOp+" ?", bun.Ident(column), filter.Value)
		}
	}
	return query, nil
}

// V2Page runs the validated v2 list query; the count reuses the identical
// where clause (accurate totalRows even past the last page).
func (Repository) V2Page(ctx context.Context, db bun.IDB, list *v2.ListQuery) ([]Model, int, error) {
	rows := []Model{}
	query := db.NewSelect().Model(&rows)

	query, err := v2ApplyQuery(query, list)
	if err != nil {
		return nil, 0, err
	}

	for _, item := range list.Sort {
		column := v2SortColumns[item.ID]
		if item.Desc {
			query = query.OrderExpr("? DESC", bun.Ident(column))
		} else {
			query = query.OrderExpr("? ASC", bun.Ident(column))
		}
	}
	query = query.OrderExpr("? ASC", bun.Ident(pkColumn))

	total, err := query.
		Limit(list.PageSize).
		Offset((list.Page - 1) * list.PageSize).
		ScanAndCount(ctx)
	if err != nil {
		return nil, 0, err
	}
	return rows, total, nil
}
