---
to: generated/.pollux-go-staging/internal/entity/<%= h.changeCase.camel(name) %>/validation.go
force: true
---
<%
const SYSTEM = ['id','createdAt','createdById','updatedAt','updatedById','deletedAt'];
let fields = (data && data.attributes ? data.attributes : []).map(function (f) {
  return { ...f, camel: h.camelField(f.name.trim()), column: f.name.trim(), dataType: (f.dataType || 'text').trim().toLowerCase() };
});
fields.forEach(function (f) { f.go = h.changeCase.pascal(f.camel); });
const isSystem = function (f) { return SYSTEM.indexOf(f.camel) !== -1; };
const addFields = fields.filter(function (f) { return f.fnrIsinFormAdd === true && !isSystem(f); });
const updFields = fields.filter(function (f) { return f.fedIsinFormUpd === true && !isSystem(f); });
const searchTypes = ['text', 'varchar', 'char', 'uuid', 'time', 'timetz'];
const numberTypes = ['smallint', 'integer', 'bigint', 'real', 'double', 'numeric'];
const filterable = fields.filter(function (f) { return f.grdIsinGrid === true && !f.isPrimaryKey; });
function goBase(t) {
  switch (t) {
    case 'smallint': case 'integer': return 'int32';
    case 'bigint': return 'int64';
    case 'real': return 'float32';
    case 'double': return 'float64';
    case 'boolean': return 'bool';
    case 'date': case 'timestamp': case 'timestamptz': return 'time.Time';
    default: return 'string';
  }
}
function filterKind(f) {
  if (f.dataType === 'boolean') return 'boolean';
  if (numberTypes.indexOf(f.dataType) !== -1) return 'number';
  if (searchTypes.indexOf(f.dataType) !== -1) return 'text';
  return '';
}
const searchable = fields.filter(function (f) {
  return searchTypes.indexOf(f.dataType) !== -1 && f.camel !== 'id' && f.camel !== 'createdById' && f.camel !== 'updatedById';
});
const hasTimeDTO = addFields.concat(updFields).some(function (f) { return goBase(f.dataType) === 'time.Time'; });
const hasNumericDTO = addFields.concat(updFields).some(function (f) { return f.dataType === 'numeric'; });
const hasSmallint = addFields.concat(updFields).some(function (f) { return f.dataType === 'smallint'; });
const mandatory = function (f, flag) { return f[flag] === 'sim'; };
-%>
// Code generated by Pollux (go backend). DO NOT EDIT.
package <%= h.changeCase.camel(name) %>

import (
	"encoding/json"
	"fmt"
<% if (hasNumericDTO) { -%>
	"regexp"
<% } -%>
	"strings"
	"time"

	"github.com/gin-gonic/gin/binding"

	"pollux-go/internal/httperr"
)

// Generated allowlists: camelCase JSON names to PostgreSQL column names.
// Request values never become SQL identifiers.
var sortableColumns = map[string]string{
<% fields.forEach(function (f) { -%>
	"<%= f.camel %>": "<%= f.column %>",
<% }) -%>
}

var filterableColumns = map[string]string{
<% filterable.forEach(function (f) { if (!filterKind(f)) return; -%>
	"<%= f.camel %>": "<%= f.column %>",
<% }) -%>
}

var filterKinds = map[string]string{
<% filterable.forEach(function (f) { if (!filterKind(f)) return; -%>
	"<%= f.camel %>": "<%= filterKind(f) %>",
<% }) -%>
}

var searchableColumns = []string{
<% searchable.forEach(function (f) { -%>
	"<%= f.column %>",
<% }) -%>
}

var updatableColumns = map[string]string{
<% updFields.forEach(function (f) { -%>
	"<%= f.camel %>": "<%= f.column %>",
<% }) -%>
}
<% if (hasNumericDTO) { -%>

var numericPattern = regexp.MustCompile(`^-?\d+(\.\d+)?$`)
<% } -%>

// CreateInput accepts only metadata-allowlisted fields. Every field is a
// pointer so presence, explicit null and value stay distinguishable. System
// fields cannot be mass-assigned: they are not part of this DTO.
type CreateInput struct {
<% addFields.forEach(function (f) { -%>
	<%= f.go %> *<%= goBase(f.dataType) %> `json:"<%= f.camel %>"`
<% }) -%>
}

func addFieldError(fieldErrors map[string][]string, field, message string) {
	fieldErrors[field] = append(fieldErrors[field], message)
}

// Validate returns per-field errors; nil means the input is acceptable.
func (in *CreateInput) Validate() map[string][]string {
	fieldErrors := map[string][]string{}
<% addFields.forEach(function (f) { -%>
<% if (mandatory(f, 'fnrMandatory')) { -%>
<% if (goBase(f.dataType) === 'string') { -%>
	if in.<%= f.go %> == nil || strings.TrimSpace(*in.<%= f.go %>) == "" {
		addFieldError(fieldErrors, "<%= f.camel %>", "Campo obrigatório")
	}
<% } else { -%>
	if in.<%= f.go %> == nil {
		addFieldError(fieldErrors, "<%= f.camel %>", "Campo obrigatório")
	}
<% } -%>
<% } -%>
<% if (f.dataType === 'numeric') { -%>
	if in.<%= f.go %> != nil && strings.TrimSpace(*in.<%= f.go %>) != "" && !numericPattern.MatchString(strings.TrimSpace(*in.<%= f.go %>)) {
		addFieldError(fieldErrors, "<%= f.camel %>", "Número inválido")
	}
<% } -%>
<% if (f.dataType === 'smallint') { -%>
	if in.<%= f.go %> != nil && (*in.<%= f.go %> < -32768 || *in.<%= f.go %> > 32767) {
		addFieldError(fieldErrors, "<%= f.camel %>", "Valor fora do intervalo permitido")
	}
<% } -%>
<% if (['char','varchar','text','time','timetz','uuid'].indexOf(f.dataType) !== -1) { -%>
	if in.<%= f.go %> != nil && len(*in.<%= f.go %>) > 10000 {
		addFieldError(fieldErrors, "<%= f.camel %>", "Valor excede o tamanho máximo")
	}
<% } -%>
<% }) -%>
	if len(fieldErrors) == 0 {
		return nil
	}
	return fieldErrors
}

// ChangedFields lists the provided JSON property names for the audit event.
func (in *CreateInput) ChangedFields() []string {
	var changed []string
<% addFields.forEach(function (f) { -%>
	if in.<%= f.go %> != nil {
		changed = append(changed, "<%= f.camel %>")
	}
<% }) -%>
	return changed
}

// UpdateBody carries the optimistic-concurrency token and the patch. Patch
// keys are validated against the update allowlist; explicit null and
// omission stay distinguishable.
type UpdateBody struct {
	ExpectedUpdatedAt json.RawMessage            `json:"expectedUpdatedAt"`
	Data              map[string]json.RawMessage `json:"data"`
}

// ExpectedUpdatedAt is a tri-state token: absent (no check), explicit null
// (row must have NULL updated_at) or a timestamp.
type ExpectedUpdatedAt struct {
	Present bool
	Value   *time.Time
}

func (b *UpdateBody) ParseExpected() (ExpectedUpdatedAt, error) {
	raw := strings.TrimSpace(string(b.ExpectedUpdatedAt))
	if raw == "" {
		return ExpectedUpdatedAt{}, nil
	}
	if raw == "null" {
		return ExpectedUpdatedAt{Present: true}, nil
	}
	var value time.Time
	if err := json.Unmarshal(b.ExpectedUpdatedAt, &value); err != nil {
		return ExpectedUpdatedAt{}, httperr.New(httperr.ValidationFailed,
			httperr.WithFieldErrors(map[string][]string{"expectedUpdatedAt": {"Data inválida"}}))
	}
	return ExpectedUpdatedAt{Present: true, Value: &value}, nil
}

// ParsePatch validates every patch key against the allowlist and decodes it
// into a column-keyed patch. Unknown or system fields are rejected, never
// silently stripped.
func (b *UpdateBody) ParsePatch() (map[string]any, []string, map[string][]string) {
	patch := map[string]any{}
	var changed []string
	fieldErrors := map[string][]string{}

	for key, raw := range b.Data {
		column, allowed := updatableColumns[key]
		if !allowed {
			addFieldError(fieldErrors, key, "Campo não permitido")
			continue
		}
		switch key {
<% updFields.forEach(function (f) { -%>
		case "<%= f.camel %>":
			var value *<%= goBase(f.dataType) %>
			if err := json.Unmarshal(raw, &value); err != nil {
				addFieldError(fieldErrors, key, "Valor inválido")
				continue
			}
<% if (f.isNullable !== true) { -%>
			if value == nil {
				addFieldError(fieldErrors, key, "Campo não pode ser nulo")
				continue
			}
<% } -%>
<% if (f.dataType === 'numeric') { -%>
			if value != nil && strings.TrimSpace(*value) != "" && !numericPattern.MatchString(strings.TrimSpace(*value)) {
				addFieldError(fieldErrors, key, "Número inválido")
				continue
			}
<% } -%>
<% if (f.dataType === 'smallint') { -%>
			if value != nil && (*value < -32768 || *value > 32767) {
				addFieldError(fieldErrors, key, "Valor fora do intervalo permitido")
				continue
			}
<% } -%>
<% if (f.isNullable === true) { -%>
			patch[column] = value
<% } else { -%>
			patch[column] = *value
<% } -%>
			changed = append(changed, key)
<% }) -%>
		default:
			addFieldError(fieldErrors, key, "Campo não permitido")
		}
	}

	if len(fieldErrors) > 0 {
		return nil, nil, fieldErrors
	}
	return patch, changed, nil
}

// SortItem and FilterItem mirror the tablecn page input.
type SortItem struct {
	ID   string `json:"id"`
	Desc bool   `json:"desc"`
}

type FilterItem struct {
	ID    string   `json:"id"`
	Value []string `json:"value"`
}

// PageInput is bounded (SPEC-002 §4 semantics): validator/v10 runs through
// the Gin binding validator, supplemented by generated cross-field checks.
type PageInput struct {
	Page    int          `json:"page" binding:"required,min=1,max=1000000"`
	PerPage int          `json:"perPage" binding:"required,min=1,max=100"`
	Sort    []SortItem   `json:"sort" binding:"omitempty,max=3"`
	Q       string       `json:"q" binding:"omitempty,max=200"`
	Filters []FilterItem `json:"filters" binding:"omitempty,max=20"`
}

// Validate rejects invalid sort/filter fields; they are never ignored.
func (p *PageInput) Validate() error {
	if err := binding.Validator.ValidateStruct(p); err != nil {
		return httperr.New(httperr.ValidationFailed, httperr.WithCause(err))
	}

	seenSort := map[string]bool{}
	for _, item := range p.Sort {
		if _, ok := sortableColumns[item.ID]; !ok {
			return httperr.New(httperr.ValidationFailed,
				httperr.WithFieldErrors(map[string][]string{"sort": {fmt.Sprintf("Campo de ordenação inválido: %s", item.ID)}}))
		}
		if seenSort[item.ID] {
			return httperr.New(httperr.ValidationFailed,
				httperr.WithFieldErrors(map[string][]string{"sort": {"Campos de ordenação duplicados"}}))
		}
		seenSort[item.ID] = true
	}

	seenFilter := map[string]bool{}
	for _, filter := range p.Filters {
		if _, ok := filterableColumns[filter.ID]; !ok {
			return httperr.New(httperr.ValidationFailed,
				httperr.WithFieldErrors(map[string][]string{"filters": {fmt.Sprintf("Campo de filtro inválido: %s", filter.ID)}}))
		}
		if seenFilter[filter.ID] {
			return httperr.New(httperr.ValidationFailed,
				httperr.WithFieldErrors(map[string][]string{"filters": {"Filtros duplicados"}}))
		}
		seenFilter[filter.ID] = true
		if len(filter.Value) > 50 {
			return httperr.New(httperr.ValidationFailed,
				httperr.WithFieldErrors(map[string][]string{"filters": {"Lista de valores excede o limite"}}))
		}
		for _, value := range filter.Value {
			if len(value) > 200 {
				return httperr.New(httperr.ValidationFailed,
					httperr.WithFieldErrors(map[string][]string{"filters": {"Valor de filtro excede o limite"}}))
			}
		}
	}
	return nil
}

// BulkDeleteInput accepts 1-100 unique IDs.
type BulkDeleteInput struct {
	IDs []string `json:"ids" binding:"required,min=1,max=100"`
}

func (b *BulkDeleteInput) Validate() error {
	if err := binding.Validator.ValidateStruct(b); err != nil {
		return httperr.New(httperr.ValidationFailed, httperr.WithCause(err))
	}
	seen := map[string]bool{}
	for _, id := range b.IDs {
		if id == "" || len(id) > 128 {
			return httperr.New(httperr.ValidationFailed,
				httperr.WithFieldErrors(map[string][]string{"ids": {"ID inválido"}}))
		}
		if seen[id] {
			return httperr.New(httperr.ValidationFailed,
				httperr.WithFieldErrors(map[string][]string{"ids": {"IDs duplicados na exclusão em lote"}}))
		}
		seen[id] = true
	}
	return nil
}

// ValidateID bounds a path identifier.
func ValidateID(id string) error {
	if id == "" || len(id) > 128 {
		return httperr.New(httperr.ValidationFailed,
			httperr.WithFieldErrors(map[string][]string{"id": {"ID inválido"}}))
	}
	return nil
}
