// SPEC-002 — start-ui-vite parity bridge.
//
// The existing start-ui-vite generators (scripts/gen-entity.mjs for the
// native /manager vertical, _templates/pollux via gen-all/gen-backend for
// the legacy-style /generated pages) remain the compatibility surface and
// are NOT rewritten here. This module exposes the normalized entity model
// as a *compatibility projection* carrying exactly the derived values those
// generators compute from raw metadata (route slugs, code identifiers,
// labels, raw db types), so golden tests can prove the normalization
// pipeline reproduces current output before any generator adopts it.
//
// Generation for this target keeps flowing through the existing CLI verbs
// (`pollux gen-entity` / `gen-all` / `gen-backend`), which operate in-place
// on this repository. The adapter below is therefore a *reference* adapter:
// it resolves and reports, but refuses plan/render — start-ui-vite is not a
// standalone workspace target.
import { ERROR_CODES, SkeletonError } from '../errors.mjs';

/** Adapter id recorded by skeletons/start-ui-vite/skeleton.json. */
export const START_UI_VITE_TARGET_ID = 'pollux-tanstack-start';

const toPascal = (camel) => camel.charAt(0).toUpperCase() + camel.slice(1);

/**
 * Project a normalized PolluxEntityModel onto the value surface the existing
 * start-ui-vite generators derive from raw metadata:
 *
 * - `name` / `camel` / `Pascal` / `plural` mirror scripts/gen-entity.mjs
 *   (toCamel/toPascal/pluralSlug) and the _templates/pollux route naming;
 * - `gridTitle` mirrors the gridTitle-or-name fallback;
 * - per-attribute `camel` mirrors h.camelField / toCamel(a.name), `dataType`
 *   is the raw legacy dbType the templates branch on, `label` preserves the
 *   source Portuguese label text.
 *
 * @param {object} model frozen PolluxEntityModel (modelVersion "1")
 */
export function toCompatProjection(model) {
  const camel = model.entity.id.replace(/_([a-z0-9])/g, (_, c) =>
    c.toUpperCase()
  );
  return {
    name: model.entity.id,
    camel,
    Pascal: toPascal(camel),
    plural: model.entity.routes.plural,
    table: model.entity.table,
    gridTitle: model.entity.titles.list,
    routes: {
      generated: `/generated/${model.entity.id}`,
      generatedServer: `/generated-server/${model.entity.id}`,
      manager: `/manager/${model.entity.routes.plural}`,
    },
    attrs: model.fields.map((field) => ({
      name: field.sourceName,
      camel: field.codeName,
      Pascal: toPascal(field.codeName),
      dataType: field.dbType,
      nullable: field.nullable,
      isPrimaryKey: field.primaryKey,
      label: field.label,
      inGrid: field.visibility.list,
      inAdd: field.visibility.create,
      inEdit: field.visibility.update,
    })),
  };
}

/**
 * Reference adapter for the in-place start-ui-vite target. `inspect` reports
 * the delegation surface; `plan`/`render`/`format`/`verify` refuse: this
 * target is generated by the existing generators in this repository, not by
 * the workspace pipeline.
 */
export const startUiViteCompatAdapter = {
  id: START_UI_VITE_TARGET_ID,
  version: '1.0.0',
  capabilities: ['export', 'operation'],
  inspect(workspace, manifest) {
    return {
      workspace,
      manifest,
      mode: 'reference-in-place',
      delegatesTo: [
        'scripts/gen-entity.mjs',
        '_templates/pollux (pollux gen-all / gen-backend)',
      ],
    };
  },
  plan() {
    throw refuseStandalone('plan');
  },
  render() {
    throw refuseStandalone('render');
  },
  format() {
    throw refuseStandalone('format');
  },
  verify() {
    throw refuseStandalone('verify');
  },
};

const refuseStandalone = (stage) =>
  new SkeletonError(
    ERROR_CODES.TARGET_UNSUPPORTED,
    `start-ui-vite is an in-place reference target; '${stage}' is served by the existing generators (pollux gen-entity / gen-all / gen-backend), not the workspace pipeline`,
    {
      details: { target: START_UI_VITE_TARGET_ID, stage },
      hint: 'use `pollux gen-entity <name>` or `pollux gen-all` inside this repository',
    }
  );
