// SPEC-008 — TanStack Start target adapter ('tanstack-start', EXPERIMENTAL).
//
// Lifecycle per scripts/pollux/targets/protocol.mjs:
//   inspect -> plan -> render -> format -> verify
//
// The workspace skeleton is `skeletons/tanstack-start` (React 19 + Vite +
// TanStack Start, Node server output via Nitro). Routing is file-based:
// generated pages under src/routes/manager/<plural>/ are registered by the
// framework's own route-tree generator (`tsr generate` / the Start vite
// plugin), so no handwritten route registry exists to preserve. The
// handwritten shell hooks are:
//
//   - src/routes/__root.tsx (handwritten) collects
//     src/generated/pollux/nav/*.ts sidebar fragments via import.meta.glob;
//   - src/routes/api/pollux/$.ts (generated, shared) collects
//     src/generated/pollux/registry/*.ts allowlist fragments the same way.
//
// There is deliberately NO aggregate generated registry file: the ownership
// record (`.pollux/generated.json`) binds every generated path to exactly one
// entity, so a file whose content depended on the whole entity set could not
// be replanned by a second entity without an OWNERSHIP_CONFLICT.
// (src/routeTree.gen.ts IS an aggregate, but it is framework-owned build
// output — regenerated by tsr/vite, never planned by this adapter.)
//
// Determinism: plans are pure functions of the frozen PolluxEntityModel plus
// the static template files under _templates/pollux-targets/{tanstack-start,
// shared} (read once at module load). Identical inputs plan identical bytes,
// so the protocol's plan hashes are stable.
//
// Shared-file ownership: proxy/auth/runtime/ui files are identical for every
// entity. They are planned (and therefore owned, per the protocol's
// per-entity ownership record) by the FIRST entity generated into the
// workspace; while another entity owns them this adapter skips planning them
// and the imports resolve against the owner's copies. EXPERIMENTAL
// limitation: `generate --all` over several entities plans from one shared
// pre-state — generate entities one at a time on this target.
import { spawnSync } from 'node:child_process';
import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

import { hasOwnershipHeader, ownerOfPath } from '../ownership.mjs';

const HERE = path.dirname(fileURLToPath(import.meta.url));
const REPO_ROOT = path.resolve(HERE, '../../../..');
const TEMPLATE_DIR = path.join(
  REPO_ROOT,
  '_templates/pollux-targets/tanstack-start/workspace'
);
const SHARED_DIR = path.join(REPO_ROOT, '_templates/pollux-targets/shared');

const readTemplate = (dir, name) =>
  fs.readFileSync(path.join(dir, name), 'utf8');

// Static sources, read once (module-load) for deterministic planning.
const TPL = {
  listPage: readTemplate(TEMPLATE_DIR, 'list.tsx.tpl'),
  newPage: readTemplate(TEMPLATE_DIR, 'new.tsx.tpl'),
  editPage: readTemplate(TEMPLATE_DIR, 'edit.tsx.tpl'),
  apiProxy: readTemplate(TEMPLATE_DIR, 'api-proxy.ts'),
  authStub: readTemplate(TEMPLATE_DIR, 'auth-stub.ts'),
  mutationHook: readTemplate(TEMPLATE_DIR, 'use-pollux-mutation.ts'),
  baseUrl: readTemplate(TEMPLATE_DIR, 'base-url.ts'),
};

const SHARED_RUNTIME_FILES = [
  'api-types.ts',
  'client.ts',
  'codecs.ts',
  'errors-pt.ts',
  'query.ts',
];
const SHARED_UI_FILES = [
  'capability-gate.tsx',
  'data-table.tsx',
  'delete-confirm.tsx',
  'entity-form.tsx',
  'states.tsx',
];

// Copies of the SPEC-003 shared templates. Runtime files keep their relative
// layout (src/lib/pollux/runtime); UI files move to src/components/pollux and
// get their runtime imports rewritten to the lib location. This is the ONLY
// transformation — field semantics stay single-sourced in the shared files.
const sharedRuntime = Object.fromEntries(
  SHARED_RUNTIME_FILES.map((name) => [
    `src/lib/pollux/runtime/${name}`,
    readTemplate(path.join(SHARED_DIR, 'runtime'), name),
  ])
);
const sharedUi = Object.fromEntries(
  SHARED_UI_FILES.map((name) => [
    `src/components/pollux/${name}`,
    readTemplate(path.join(SHARED_DIR, 'ui'), name).replaceAll(
      "'../runtime/",
      "'../../lib/pollux/runtime/"
    ),
  ])
);

/** Files identical for every entity (see ownership note above). */
const SHARED_OUTPUTS = {
  'src/routes/api/pollux/$.ts': TPL.apiProxy,
  'src/routes/api/pollux/auth.$action.ts': TPL.authStub,
  'src/lib/pollux/use-pollux-mutation.ts': TPL.mutationHook,
  'src/lib/pollux/base-url.ts': TPL.baseUrl,
  // Framework-neutral BFF auth core; imported ONLY by the server-route
  // modules above — TanStack Start strips server handlers from the client
  // bundle, and the matrix secret scan proves no server-only name leaks.
  'src/lib/pollux/bff-core.server.ts': readTemplate(
    path.join(SHARED_DIR, 'runtime'),
    'bff-core.ts'
  ),
  ...sharedRuntime,
  ...sharedUi,
};

const pascalCase = (id) =>
  id
    .split('_')
    .filter(Boolean)
    .map((part) => part[0].toUpperCase() + part.slice(1))
    .join('');

const TS_BY_SCALAR = {
  uuid: 'string',
  string: 'string',
  varchar: 'string',
  text: 'string',
  boolean: 'boolean',
  integer: 'number',
  float: 'number',
  numeric: 'string',
  date: 'string',
  time: 'string',
  timestamp: 'string',
};

const requiredOn = (model, codeName, operation) =>
  model.validation.some(
    (entry) =>
      entry.field === codeName &&
      entry.rules.some(
        (rule) => rule.rule === 'required' && rule.on.includes(operation)
      )
  );

/** EntitySpec projection (shared runtime api-types contract). */
const buildSpecObject = (model) => ({
  id: model.entity.id,
  titles: { ...model.entity.titles },
  fields: model.fields.map((field) => ({
    codeName: field.codeName,
    label: field.label,
    scalarType: field.scalarType,
    nullable: field.nullable,
    primaryKey: field.primaryKey,
    mutability: field.mutability,
    requiredOnCreate: requiredOn(model, field.codeName, 'create'),
    requiredOnUpdate: requiredOn(model, field.codeName, 'update'),
    maxLength: field.constraints.length ?? null,
    visibility: { ...field.visibility },
  })),
  sortableFields: [...model.list.sortableFields],
  filterableFields: [...model.list.filterableFields],
  pageSizes: [...model.list.pageSizes],
  defaultPageSize: model.list.defaultPageSize,
  defaultSort: model.list.defaultSort.map((s) => ({
    id: s.field,
    desc: s.direction === 'desc',
  })),
});

const buildSpecTs = (model) => {
  const pascal = pascalCase(model.entity.id);
  const rowFields = model.fields
    .map(
      (field) =>
        `  ${field.codeName}: ${TS_BY_SCALAR[field.scalarType]}${
          field.nullable ? ' | null' : ''
        };`
    )
    .join('\n');
  const spec = JSON.stringify(buildSpecObject(model), null, 2);
  return [
    `// EntitySpec projection for '${model.entity.id}' (PolluxEntityModel v${model.modelVersion}).`,
    `// Labels/titles preserve the source metadata text (Portuguese).`,
    `import type { EntitySpec, WireRecord } from '../../../lib/pollux/runtime/api-types';`,
    ``,
    `// Intersection with WireRecord keeps the row assignable to the shared`,
    `// client/form contracts while exposing typed field access.`,
    `export type ${pascal}Row = WireRecord & {`,
    rowFields,
    `};`,
    ``,
    `export const ${model.entity.id}Spec: EntitySpec = ${spec};`,
    ``,
  ].join('\n');
};

const buildNavTs = (model) =>
  [
    `// Sidebar registry fragment — consumed by the handwritten`,
    `// src/routes/__root.tsx via import.meta.glob('../generated/pollux/nav/*.ts').`,
    `export const navEntry = {`,
    `  to: ${JSON.stringify(`/manager/${model.entity.routes.plural}`)},`,
    `  label: ${JSON.stringify(model.entity.titles.list)},`,
    `} as const;`,
    ``,
  ].join('\n');

const buildRegistryTs = (model) => {
  const queryKeys = [];
  for (const codeName of model.list.filterableFields) {
    queryKeys.push(`f_${codeName}`);
    for (const op of model.list.filterOperators[codeName] ?? []) {
      queryKeys.push(`f_${codeName}__${op}`);
    }
  }
  const methods = Object.fromEntries(
    ['list', 'read', 'create', 'update', 'delete'].map((op) => [
      op,
      model.operations[op].enabled,
    ])
  );
  return [
    `// Proxy allowlist registry fragment — consumed by`,
    `// src/routes/api/pollux/$.ts via import.meta.glob. The proxy only`,
    `// forwards requests for entities/methods/query keys declared here.`,
    `export const registryEntry = {`,
    `  entity: ${JSON.stringify(model.entity.id)},`,
    `  methods: ${JSON.stringify(methods)},`,
    `  queryKeys: ${JSON.stringify(queryKeys)},`,
    `} as const;`,
    ``,
  ].join('\n');
};

const applyTokens = (template, tokens) => {
  let out = template;
  for (const [token, value] of Object.entries(tokens)) {
    out = out.replaceAll(token, value);
  }
  return out;
};

const FORBIDDEN_IMPORTS = [
  // Cross-framework imports must never reach TanStack Start output.
  /from\s+['"]next(\/|['"])/,
  /from\s+['"]react-router['"]/,
  /from\s+['"]@react-router\//,
  /from\s+['"]astro(\/|['"])/,
  /from\s+['"]@astrojs\//,
];

const walkFiles = (dir, out = []) => {
  for (const entry of fs.readdirSync(dir, { withFileTypes: true })) {
    const abs = path.join(dir, entry.name);
    if (entry.isDirectory()) walkFiles(abs, out);
    else if (entry.isFile()) out.push(abs);
  }
  return out;
};

export const adapter = {
  id: 'tanstack-start',
  version: '0.1.0',
  // Capability level 'standalone-crud': entities that need report/operation
  // surfaces are rejected at plan time by the protocol capability check.
  capabilities: [],

  inspect(workspace, manifest) {
    return {
      workspace,
      provenance: manifest?.provenance ?? null,
      generated: manifest?.generated ?? null,
    };
  },

  plan(model, context) {
    const entity = model.entity.id;
    const plural = model.entity.routes.plural;
    const pascal = pascalCase(entity);
    const pk = model.fields.find((f) => f.primaryKey);
    const subject =
      model.fields.find(
        (f) =>
          !f.primaryKey &&
          f.visibility.list &&
          ['string', 'varchar', 'text'].includes(f.scalarType)
      ) ?? pk;
    const tokens = {
      __ENTITY__: entity,
      __PASCAL__: pascal,
      __PLURAL__: plural,
      __PK__: pk.codeName,
      __SUBJECT_FIELD__: subject.codeName,
      __TITLE_LIST_JSON__: JSON.stringify(model.entity.titles.list),
      __TITLE_CREATE_JSON__: JSON.stringify(model.entity.titles.create),
      __TITLE_UPDATE_JSON__: JSON.stringify(model.entity.titles.update),
    };

    const outputs = [
      {
        path: `src/routes/manager/${plural}/index.tsx`,
        content: applyTokens(TPL.listPage, tokens),
      },
      {
        path: `src/routes/manager/${plural}/new.tsx`,
        content: applyTokens(TPL.newPage, tokens),
      },
      {
        path: `src/routes/manager/${plural}/$id.edit.tsx`,
        content: applyTokens(TPL.editPage, tokens),
      },
      {
        path: `src/generated/pollux/${entity}/spec.ts`,
        content: buildSpecTs(model),
      },
      {
        path: `src/generated/pollux/nav/${entity}.ts`,
        content: buildNavTs(model),
      },
      {
        path: `src/generated/pollux/registry/${entity}.ts`,
        content: buildRegistryTs(model),
      },
    ];

    // Shared files: planned only while no OTHER entity owns them (see the
    // ownership note in the module header).
    for (const [relPath, content] of Object.entries(SHARED_OUTPUTS)) {
      const owner = ownerOfPath(context.generated, relPath);
      if (owner === null || owner === entity) {
        outputs.push({ path: relPath, content });
      }
    }
    return { outputs };
  },

  render(plan, staging) {
    for (const op of plan.operations) {
      if (op.action === 'remove' || op.action === 'preserve') continue;
      const file = path.join(staging, op.path);
      fs.mkdirSync(path.dirname(file), { recursive: true });
      fs.writeFileSync(file, plan.contents.get(op.path));
    }
    return { ok: true };
  },

  // No-op BY DESIGN: emitted content is already in its final shape and the
  // protocol requires formatting to be a fixpoint of the planned bytes (the
  // plan hash must equal the staged hash). No workspace formatter runs here;
  // running one would have to be replicated at plan time anyway.
  format() {
    return { ok: true };
  },

  // Structural verification of the staged tree. A full typecheck
  // (`tsr generate && tsc --noEmit`) needs an installed workspace
  // (node_modules + a regenerated route tree) which the bare staging tree
  // never has — when a test stages into a full installed workspace copy the
  // check runs; otherwise the workspace-level `pnpm typecheck` covers it
  // after publication (the SPEC-008 canonical verification order).
  verify(staging) {
    const problems = [];
    for (const abs of walkFiles(staging)) {
      const rel = path.relative(staging, abs).split(path.sep).join('/');
      const content = fs.readFileSync(abs, 'utf8');
      if (content.length === 0) {
        problems.push(`empty staged file: ${rel}`);
        continue;
      }
      const ext = path.extname(rel);
      if (['.ts', '.tsx'].includes(ext)) {
        if (!hasOwnershipHeader(content)) {
          problems.push(`missing ownership header: ${rel}`);
        }
        for (const pattern of FORBIDDEN_IMPORTS) {
          if (pattern.test(content)) {
            problems.push(`forbidden framework import in ${rel} (${pattern})`);
          }
        }
        // Escaped-entity regression guard (the '<%= %>' class of bug): raw
        // generated code must never carry HTML entities.
        if (content.includes('&#39;') || content.includes('&quot;')) {
          problems.push(`HTML-escaped entity in generated code: ${rel}`);
        }
      }
    }
    // Optional full typecheck when the staging tree is an installed workspace.
    if (
      fs.existsSync(path.join(staging, 'node_modules')) &&
      fs.existsSync(path.join(staging, 'tsconfig.json'))
    ) {
      const result = spawnSync('pnpm', ['typecheck'], {
        cwd: staging,
        encoding: 'utf8',
      });
      if (result.status !== 0) {
        problems.push(
          `workspace typecheck failed:\n${result.stdout}${result.stderr}`
        );
      }
    }
    return { ok: problems.length === 0, problems };
  },
};

export const adapters = [adapter];
export default adapter;
