// AUTO-GENERATED by scripts/gen-entity.mjs — do not edit by hand.
export type GeneratedNavItem = {
  entity: string;
  to: string;
  labelKey: string;
};

export const generatedNavItems: GeneratedNavItem[] = [
  { entity: 'act', to: '/manager/acts', labelKey: 'act:manager.list.title' },
  { entity: 'apk', to: '/manager/apks', labelKey: 'apk:manager.list.title' },
  {
    entity: 'apkloc',
    to: '/manager/apklocs',
    labelKey: 'apkloc:manager.list.title',
  },
  { entity: 'asg', to: '/manager/asgs', labelKey: 'asg:manager.list.title' },
  { entity: 'aut', to: '/manager/auts', labelKey: 'aut:manager.list.title' },
  {
    entity: 'clbloc',
    to: '/manager/clblocs',
    labelKey: 'clbloc:manager.list.title',
  },
  { entity: 'cola', to: '/manager/colas', labelKey: 'cola:manager.list.title' },
  {
    entity: 'fortestsonly',
    to: '/manager/fortestsonlys',
    labelKey: 'fortestsonly:manager.list.title',
  },
  { entity: 'gal', to: '/manager/gals', labelKey: 'gal:manager.list.title' },
  { entity: 'gen', to: '/manager/gens', labelKey: 'gen:manager.list.title' },
  { entity: 'grc', to: '/manager/grcs', labelKey: 'grc:manager.list.title' },
  {
    entity: 'grcpeo',
    to: '/manager/grcpeos',
    labelKey: 'grcpeo:manager.list.title',
  },
  { entity: 'grp', to: '/manager/grps', labelKey: 'grp:manager.list.title' },
  {
    entity: 'lechis',
    to: '/manager/lechises',
    labelKey: 'lechis:manager.list.title',
  },
  {
    entity: 'lecrev',
    to: '/manager/lecrevs',
    labelKey: 'lecrev:manager.list.title',
  },
  { entity: 'lect', to: '/manager/lects', labelKey: 'lect:manager.list.title' },
  {
    entity: 'lecusr',
    to: '/manager/lecusrs',
    labelKey: 'lecusr:manager.list.title',
  },
  {
    entity: 'lenhea',
    to: '/manager/lenheas',
    labelKey: 'lenhea:manager.list.title',
  },
  {
    entity: 'lenitm',
    to: '/manager/lenitms',
    labelKey: 'lenitm:manager.list.title',
  },
  { entity: 'loc', to: '/manager/locs', labelKey: 'loc:manager.list.title' },
  { entity: 'loca', to: '/manager/locas', labelKey: 'loca:manager.list.title' },
  {
    entity: 'locsme',
    to: '/manager/locsmes',
    labelKey: 'locsme:manager.list.title',
  },
  {
    entity: 'logupd',
    to: '/manager/logupds',
    labelKey: 'logupd:manager.list.title',
  },
  {
    entity: 'menhea',
    to: '/manager/menheas',
    labelKey: 'menhea:manager.list.title',
  },
  {
    entity: 'menlog',
    to: '/manager/menlogs',
    labelKey: 'menlog:manager.list.title',
  },
  {
    entity: 'menpeo',
    to: '/manager/menpeos',
    labelKey: 'menpeo:manager.list.title',
  },
  {
    entity: 'menres',
    to: '/manager/menreses',
    labelKey: 'menres:manager.list.title',
  },
  {
    entity: 'msgusr',
    to: '/manager/msgusrs',
    labelKey: 'msgusr:manager.list.title',
  },
  { entity: 'msit', to: '/manager/msits', labelKey: 'msit:manager.list.title' },
  {
    entity: 'peosme',
    to: '/manager/peosmes',
    labelKey: 'peosme:manager.list.title',
  },
  {
    entity: 'pergrp',
    to: '/manager/pergrps',
    labelKey: 'pergrp:manager.list.title',
  },
  {
    entity: 'perusr',
    to: '/manager/perusrs',
    labelKey: 'perusr:manager.list.title',
  },
  { entity: 'pesi', to: '/manager/pesis', labelKey: 'pesi:manager.list.title' },
  {
    entity: 'pesloc',
    to: '/manager/peslocs',
    labelKey: 'pesloc:manager.list.title',
  },
  {
    entity: 'pespeo',
    to: '/manager/pespeos',
    labelKey: 'pespeo:manager.list.title',
  },
  { entity: 'pesq', to: '/manager/pesqs', labelKey: 'pesq:manager.list.title' },
  { entity: 'pesr', to: '/manager/pesrs', labelKey: 'pesr:manager.list.title' },
  {
    entity: 'phrpeo',
    to: '/manager/phrpeos',
    labelKey: 'phrpeo:manager.list.title',
  },
  { entity: 'psh', to: '/manager/pshs', labelKey: 'psh:manager.list.title' },
  { entity: 'publ', to: '/manager/publs', labelKey: 'publ:manager.list.title' },
  {
    entity: 'pubpeo',
    to: '/manager/pubpeos',
    labelKey: 'pubpeo:manager.list.title',
  },
  {
    entity: 'remloc',
    to: '/manager/remlocs',
    labelKey: 'remloc:manager.list.title',
  },
  { entity: 'res', to: '/manager/reses', labelKey: 'res:manager.list.title' },
  { entity: 'site', to: '/manager/sites', labelKey: 'site:manager.list.title' },
  { entity: 'sme', to: '/manager/smes', labelKey: 'sme:manager.list.title' },
  { entity: 'spkr', to: '/manager/spkrs', labelKey: 'spkr:manager.list.title' },
  { entity: 'tct', to: '/manager/tcts', labelKey: 'tct:manager.list.title' },
  { entity: 'tle', to: '/manager/tles', labelKey: 'tle:manager.list.title' },
  { entity: 'tme', to: '/manager/tmes', labelKey: 'tme:manager.list.title' },
  { entity: 'tmf', to: '/manager/tmfs', labelKey: 'tmf:manager.list.title' },
  { entity: 'tpe', to: '/manager/tpes', labelKey: 'tpe:manager.list.title' },
  { entity: 'tpl', to: '/manager/tpls', labelKey: 'tpl:manager.list.title' },
  {
    entity: 'tplloc',
    to: '/manager/tpllocs',
    labelKey: 'tplloc:manager.list.title',
  },
  { entity: 'trf', to: '/manager/trfs', labelKey: 'trf:manager.list.title' },
  {
    entity: 'usrgrp',
    to: '/manager/usrgrps',
    labelKey: 'usrgrp:manager.list.title',
  },
];
