// SPEC-002 — resource declarations for the pollux-ui plugin snapshot.
// Every entry names canonical repo-relative source paths, the plugin-relative
// package destination, ownership, mutation policy, and compatibility.
// build-resources.mjs resolves, copies, hashes, and catalogs these.

export const RESOURCE_DECLARATIONS = [
  // ---------------------------------------------------------- templates
  {
    id: 'templates.legacy-typescript',
    kind: 'template-tree',
    sourcePaths: [
      '_templates/pollux/page',
      '_templates/pollux/serverpage',
      '_templates/pollux/form-fields',
      '_templates/pollux/partials',
    ],
    packagePath: './resources/templates/legacy-typescript',
    ownership: 'canonical-source',
    mutationPolicy: 'render',
    generatorSurfaces: ['generated', 'generated-server'],
    frameworkTargets: ['start-ui-vite'],
    supportStatus: 'supported',
    dependencies: ['generator.pollux-cli'],
    entrypoints: ['./pollux gen-entity', './pollux gen-all'],
    verification: ['./pollux check', './pollux test --suite=unit'],
  },
  {
    id: 'templates.go-backend',
    kind: 'template-tree',
    sourcePaths: [
      '_templates/pollux/go-service',
      '_templates/pollux/go-entity',
    ],
    packagePath: './resources/templates/go-backend',
    ownership: 'canonical-source',
    mutationPolicy: 'render',
    generatorSurfaces: ['go-backend'],
    frameworkTargets: [],
    supportStatus: 'supported',
    dependencies: ['generator.pollux-cli'],
    entrypoints: ['./pollux gen-backend --backend=go'],
    verification: [
      './pollux test --suite=go',
      './pollux test --suite=selection',
    ],
  },
  {
    id: 'templates.standalone-shared',
    kind: 'template-tree',
    sourcePaths: ['_templates/pollux-targets/shared'],
    packagePath: './resources/templates/standalone-shared',
    ownership: 'canonical-source',
    mutationPolicy: 'render',
    generatorSurfaces: ['standalone'],
    frameworkTargets: ['nextjs', 'react-router', 'astro', 'tanstack-start'],
    supportStatus: 'experimental',
    dependencies: [],
    entrypoints: ['./pollux generate --workspace=<path> --entity=<name>'],
    verification: ['./pollux test --suite=targets'],
  },
  {
    id: 'templates.target.nextjs',
    kind: 'template-tree',
    sourcePaths: ['_templates/pollux-targets/nextjs'],
    packagePath: './resources/templates/target/nextjs',
    ownership: 'canonical-source',
    mutationPolicy: 'render',
    generatorSurfaces: ['standalone'],
    frameworkTargets: ['nextjs'],
    supportStatus: 'experimental',
    dependencies: ['templates.standalone-shared'],
    entrypoints: ['./pollux generate --target=nextjs --workspace=<path>'],
    verification: [
      'node scripts/pollux/test/workspace-matrix.mjs --target nextjs',
    ],
  },
  {
    id: 'templates.target.react-router',
    kind: 'template-tree',
    sourcePaths: ['_templates/pollux-targets/react-router'],
    packagePath: './resources/templates/target/react-router',
    ownership: 'canonical-source',
    mutationPolicy: 'render',
    generatorSurfaces: ['standalone'],
    frameworkTargets: ['react-router'],
    supportStatus: 'experimental',
    dependencies: ['templates.standalone-shared'],
    entrypoints: ['./pollux generate --target=react-router --workspace=<path>'],
    verification: [
      'node scripts/pollux/test/workspace-matrix.mjs --target remix',
    ],
  },
  {
    id: 'templates.target.tanstack-start',
    kind: 'template-tree',
    sourcePaths: ['_templates/pollux-targets/tanstack-start'],
    packagePath: './resources/templates/target/tanstack-start',
    ownership: 'canonical-source',
    mutationPolicy: 'render',
    generatorSurfaces: ['standalone'],
    frameworkTargets: ['tanstack-start'],
    supportStatus: 'experimental',
    dependencies: ['templates.standalone-shared'],
    entrypoints: [
      './pollux generate --target=tanstack-start --workspace=<path>',
    ],
    verification: [
      'node scripts/pollux/test/workspace-matrix.mjs --target tanstack-start',
    ],
  },
  {
    id: 'templates.target.astro-react',
    kind: 'template-tree',
    sourcePaths: ['_templates/pollux-targets/astro-react'],
    packagePath: './resources/templates/target/astro-react',
    ownership: 'canonical-source',
    mutationPolicy: 'render',
    generatorSurfaces: ['standalone'],
    frameworkTargets: ['astro'],
    supportStatus: 'experimental',
    dependencies: ['templates.standalone-shared'],
    entrypoints: ['./pollux generate --target=astro-react --workspace=<path>'],
    verification: [
      'node scripts/pollux/test/workspace-matrix.mjs --target astro',
    ],
  },

  // ------------------------------------------------------------ layouts
  {
    id: 'layout.start-ui-vite',
    kind: 'layout-shell',
    sourcePaths: [
      'src/routes/__root.tsx',
      'src/layout/app',
      'src/layout/manager',
      'src/styles/app.css',
    ],
    packagePath: './resources/layouts/start-ui-vite',
    ownership: 'canonical-source',
    mutationPolicy: 'read-only',
    generatorSurfaces: ['manager'],
    frameworkTargets: ['start-ui-vite'],
    supportStatus: 'supported',
    dependencies: ['design.tokens'],
    entrypoints: [
      'src/routes/__root.tsx',
      'src/layout/manager/layout.tsx',
      'src/styles/app.css',
    ],
    verification: ['pnpm build', './pollux validate-skeletons'],
  },
  {
    id: 'layout.nextjs',
    kind: 'layout-shell',
    sourcePaths: [
      'skeletons/nextjs/app/layout.tsx',
      'skeletons/nextjs/app/globals.css',
      'skeletons/nextjs/app/tokens.css',
      'skeletons/nextjs/components',
      'skeletons/nextjs/skeleton.json',
    ],
    packagePath: './resources/layouts/nextjs',
    ownership: 'canonical-source',
    mutationPolicy: 'copy',
    generatorSurfaces: ['standalone'],
    frameworkTargets: ['nextjs'],
    supportStatus: 'experimental',
    dependencies: ['design.tokens'],
    entrypoints: [
      'skeletons/nextjs/app/layout.tsx',
      'skeletons/nextjs/components/sidebar.tsx',
      'skeletons/nextjs/components/topbar.tsx',
    ],
    verification: [
      './pollux validate-skeletons',
      'node scripts/pollux/test/workspace-matrix.mjs --target nextjs',
    ],
  },
  {
    id: 'layout.react-router',
    kind: 'layout-shell',
    sourcePaths: [
      'skeletons/remix/app/root.tsx',
      'skeletons/remix/app/app.css',
      'skeletons/remix/app/routes.ts',
      'skeletons/remix/app/routes',
      'skeletons/remix/skeleton.json',
    ],
    packagePath: './resources/layouts/react-router',
    ownership: 'canonical-source',
    mutationPolicy: 'copy',
    generatorSurfaces: ['standalone'],
    frameworkTargets: ['react-router'],
    supportStatus: 'experimental',
    dependencies: ['design.tokens'],
    entrypoints: ['skeletons/remix/app/root.tsx'],
    verification: [
      './pollux validate-skeletons',
      'node scripts/pollux/test/workspace-matrix.mjs --target remix',
    ],
  },
  {
    id: 'layout.astro',
    kind: 'layout-shell',
    sourcePaths: [
      'skeletons/astro/src/layouts',
      'skeletons/astro/src/styles',
      'skeletons/astro/skeleton.json',
    ],
    packagePath: './resources/layouts/astro',
    ownership: 'canonical-source',
    mutationPolicy: 'copy',
    generatorSurfaces: ['standalone'],
    frameworkTargets: ['astro'],
    supportStatus: 'experimental',
    dependencies: ['design.tokens'],
    entrypoints: ['skeletons/astro/src/layouts/Layout.astro'],
    verification: [
      './pollux validate-skeletons',
      'node scripts/pollux/test/workspace-matrix.mjs --target astro',
    ],
  },
  {
    id: 'layout.tanstack-start',
    kind: 'layout-shell',
    sourcePaths: [
      'skeletons/tanstack-start/src/routes/__root.tsx',
      'skeletons/tanstack-start/src/routes/index.tsx',
      'skeletons/tanstack-start/src/styles/app.css',
      'skeletons/tanstack-start/skeleton.json',
    ],
    packagePath: './resources/layouts/tanstack-start',
    ownership: 'canonical-source',
    mutationPolicy: 'copy',
    generatorSurfaces: ['standalone'],
    frameworkTargets: ['tanstack-start'],
    supportStatus: 'experimental',
    dependencies: ['design.tokens'],
    entrypoints: ['skeletons/tanstack-start/src/routes/__root.tsx'],
    verification: [
      './pollux validate-skeletons',
      'node scripts/pollux/test/workspace-matrix.mjs --target tanstack-start',
    ],
  },

  // ------------------------------------------------------- design system
  {
    id: 'design.tokens',
    kind: 'design-system',
    sourcePaths: ['skeletons/_shared/design-tokens.css'],
    packagePath: './resources/design-system/design-tokens.css',
    ownership: 'canonical-source',
    mutationPolicy: 'read-only',
    generatorSurfaces: ['manager', 'standalone'],
    frameworkTargets: [
      'start-ui-vite',
      'nextjs',
      'react-router',
      'astro',
      'tanstack-start',
    ],
    supportStatus: 'supported',
    dependencies: [],
    entrypoints: ['skeletons/_shared/design-tokens.css'],
    verification: ['./pollux validate-skeletons'],
  },

  // -------------------------------------------------- generator runtimes
  {
    id: 'generator.pollux-cli',
    kind: 'generator-entrypoint',
    sourcePaths: ['pollux', 'scripts/pollux/cli.mjs'],
    packagePath: null,
    ownership: 'invoke-only',
    mutationPolicy: 'invoke',
    generatorSurfaces: [
      'manager',
      'generated',
      'generated-server',
      'go-backend',
      'standalone',
    ],
    frameworkTargets: [
      'start-ui-vite',
      'nextjs',
      'react-router',
      'astro',
      'tanstack-start',
    ],
    supportStatus: 'supported',
    dependencies: [],
    entrypoints: ['./pollux help'],
    verification: ['./pollux test --suite=unit'],
  },

  // ---------------------------------------------------------- references
  {
    id: 'reference.agent-contract',
    kind: 'reference',
    sourcePaths: ['CLAUDE.md'],
    packagePath: './resources/references/CLAUDE.md',
    ownership: 'canonical-source',
    mutationPolicy: 'read-only',
    generatorSurfaces: [
      'manager',
      'generated',
      'generated-server',
      'go-backend',
      'standalone',
    ],
    frameworkTargets: [
      'start-ui-vite',
      'nextjs',
      'react-router',
      'astro',
      'tanstack-start',
    ],
    supportStatus: 'supported',
    dependencies: [],
    entrypoints: [],
    verification: [],
  },
  {
    id: 'reference.pollux-kb',
    kind: 'reference',
    sourcePaths: ['POLLUX-GEN-KB.md'],
    packagePath: './resources/references/POLLUX-GEN-KB.md',
    ownership: 'canonical-source',
    mutationPolicy: 'read-only',
    generatorSurfaces: [
      'manager',
      'generated',
      'generated-server',
      'go-backend',
      'standalone',
    ],
    frameworkTargets: [
      'start-ui-vite',
      'nextjs',
      'react-router',
      'astro',
      'tanstack-start',
    ],
    supportStatus: 'supported',
    dependencies: [],
    entrypoints: [],
    verification: [],
  },
  {
    id: 'reference.templates-readme',
    kind: 'reference',
    sourcePaths: ['_templates/README.md'],
    packagePath: './resources/references/templates-README.md',
    ownership: 'canonical-source',
    mutationPolicy: 'read-only',
    generatorSurfaces: ['generated', 'generated-server', 'go-backend'],
    frameworkTargets: ['start-ui-vite'],
    supportStatus: 'reference-only',
    dependencies: [],
    entrypoints: [],
    verification: [],
  },
  {
    id: 'reference.skeletons-readme',
    kind: 'reference',
    sourcePaths: ['skeletons/README.md', 'skeletons/registry.json'],
    packagePath: './resources/references/skeletons',
    ownership: 'canonical-source',
    mutationPolicy: 'read-only',
    generatorSurfaces: ['standalone'],
    frameworkTargets: ['nextjs', 'react-router', 'astro', 'tanstack-start'],
    supportStatus: 'experimental',
    dependencies: [],
    entrypoints: [],
    verification: ['./pollux validate-skeletons'],
  },
  {
    id: 'reference.ops-runbooks',
    kind: 'reference',
    sourcePaths: [
      'docs/operations/pollux-runbook.md',
      'docs/operations/pollux-skeletons-runbook.md',
      'docs/operations/pollux-generated-crud.md',
      'docs/operations/pollux-go-backend.md',
    ],
    packagePath: './resources/references/operations',
    ownership: 'canonical-source',
    mutationPolicy: 'read-only',
    generatorSurfaces: [
      'manager',
      'generated',
      'generated-server',
      'go-backend',
      'standalone',
    ],
    frameworkTargets: [
      'start-ui-vite',
      'nextjs',
      'react-router',
      'astro',
      'tanstack-start',
    ],
    supportStatus: 'reference-only',
    dependencies: [],
    entrypoints: [],
    verification: [],
  },
];
